import type { HandleKind } from "./types";

export const CONNECTION_RULES: Record<HandleKind, HandleKind[]> = {
  "event-source": [
    "endpoint-in",
    "pageload-in",
    "sse-in",
    "websocket-in",
    "page-ref-in",
  ],
  "endpoint-in": [],
  "pageload-in": [],
  "sse-in": [],
  "websocket-in": [],
  "page-ref-in": [],
  "endpoint-out": [
    "database-target",
    "action-target",
    "resource-def-in",
    "endpoint-in",
    "task-in",
    "index-in",
    "sse-in",
    "websocket-in",
    "pageload-in",
    "langgraph-in",
  ],
  "published-event-out": [
    "resource-def-in",
    "task-in",
    "sse-in",
    "websocket-in",
  ],
  "consumed-event-in": [],
  "consumed-event-out": [
    "endpoint-in",
    "resource-def-in",
    "task-in",
    "index-in",
    "sse-in",
    "websocket-in",
    "langgraph-in",
    "hook-in",
  ],
  "resource-def-in": [],
  "resource-def-out": [
    "consumed-event-in",
    "task-in",
    "sse-in",
    "websocket-in",
    "hook-in",
  ],
  "entity-column-source": ["entity-column-target"],
  "entity-column-target": [],
  "entity-top-target": [],
  "entity-bottom-source": ["entity-top-target"],
  "database-target": [],
  "database-source": ["endpoint-in", "task-in", "index-in", "entity-top-target"],
  "action-target": [],
  "task-in": [],
  "task-out": [
    "database-target",
    "action-target",
    "resource-def-in",
    "endpoint-in",
    "index-in",
    "langgraph-in",
  ],
  "index-in": [],
  "index-out": ["endpoint-in", "task-in"],
  "llm-out": ["llm-in", "step-in"],
  "llm-in": [],
  "step-out": ["step-in", "endpoint-in", "database-target"],
  "step-in": [],
  // --- LangGraph Agent (main canvas) ---
  "langgraph-in": [],
  "langgraph-out": [
    "endpoint-in",
    "task-in",
    "consumed-event-in",
    "database-target",
    "resource-def-in",
    "sse-in",
    "websocket-in",
  ],
  "auth-out": ["auth-in", "page-section-in"],
  "auth-in": [],
  "injects-plugin-out": ["payments-plugin-in", "auth-in"],
  "payments-plugin-in": [],
  "page-out": ["page-section-in", "endpoint-in", "page-in", "page-ref-in", "hook-in", "component-in"],
  "page-in": [],
  "page-section-in": ["page-in", "endpoint-in", "page-out", "hook-in", "component-in"],
  "transformer-in": [],
  "transformer-out": [
    "endpoint-in",
    "consumed-event-in",
    "task-in",
    "database-target",
    "resource-def-in",
    "langgraph-in",
    "transformer-in",
  ],
  "hook-in": [],
  "hook-out": ["hook-in", "page-in", "component-in", "endpoint-in"],
  "component-in": [],
  "component-out": ["component-in", "page-in", "slot-in"],
  "slot-in": [],
  "slot-out": ["slot-in", "component-in", "page-in"],
  unknown: [],
};

export const EDGE_TYPE_MAP: Record<string, string> = {
  "entity-column-source→entity-column-target": "foreign-key",
  "entity-bottom-source→entity-top-target": "foreign-key",
  "database-source→entity-top-target": "database-connection",
  "published-event-out→resource-def-in": "message",
  "consumed-event-out→resource-def-in": "message",
  "resource-def-out→consumed-event-in": "message",
  "published-event-out→task-in": "message",
  "consumed-event-out→task-in": "message",
  "resource-def-out→task-in": "message",
  "task-out→resource-def-in": "message",
  "endpoint-out→task-in": "connection",
  // Endpoint → Messaging broker (auto-creates a publisher, rewired in edgeSlice)
  "endpoint-out→resource-def-in": "message",
  // LangGraph invocation edges
  "endpoint-out→langgraph-in": "connection",
  "consumed-event-out→langgraph-in": "message",
  "task-out→langgraph-in": "connection",
  "langgraph-out→endpoint-in": "connection",
  "langgraph-out→task-in": "connection",
  "langgraph-out→consumed-event-in": "message",
  // Auth & Page wiring edges
  "auth-out→auth-in": "identity-connection",
  "injects-plugin-out→payments-plugin-in": "identity-connection",
  "injects-plugin-out→auth-in": "identity-connection",
  "page-out→page-section-in": "connection",
  "page-section-in→page-in": "connection",
  "page-out→page-in": "connection",
  "event-source→page-ref-in": "connection",
  "page-out→page-ref-in": "connection",
  "transformer-out→endpoint-in": "connection",
  "transformer-out→consumed-event-in": "connection",
  "transformer-out→task-in": "connection",
  "transformer-out→database-target": "connection",
  "transformer-out→transformer-in": "transformer-reference",
  // Frontend Hook & Component wiring edges
  "endpoint-out→hook-in": "connection",
  "resource-def-out→hook-in": "message",
  "hook-out→hook-in": "reference",
  "hook-out→page-in": "connection",
  "hook-out→component-in": "connection",
  "component-out→component-in": "reference",
  "component-out→page-in": "connection",
  "slot-out→slot-in": "connection",
};

export const WEB_PAGE_EVENTS = [
  "pageLoad",
  "click",
  "hover",
  "drag",
  "dblclick",
  "keydown",
  "keyup",
  "submit",
  "change",
  "focus",
  "blur",
  "mouseenter",
  "mouseleave",
  "sse",
  "websocket",
  "navigateToPage",
  "other",
] as const;
