// ═══════════════════════════════════════════════════════════════════════════
// MODULE:  compileExternalNodes  (thin orchestrator)
// LAYER:   compilers
// PURPOSE: Compiles all external API nodes into a shared package.
//
// DELEGATES TO:
//   external/httpBodyCompiler.ts        — JSON body compilation + type utils
//   external/externalFunctionEmitter.ts — per-node TypeScript function file
//
// EMITS:
//   packages/external-apis/src/<fnName>.ts   (one per external node)
//   packages/external-apis/src/index.ts      (barrel re-exports)
//   packages/external-apis/package.json
//   packages/external-apis/tsconfig.json
// ═══════════════════════════════════════════════════════════════════════════

import { BackendNode, BackendEdge } from "@/types/canvas";
import { CompiledFile, ReusableFunction } from "@workspace/canvas/types";
import { toPascalCase, toVarName } from "./utils";
import { generateExternalFunctionFile } from "./external/externalFunctionEmitter";

// Re-export so existing imports from this file continue to work
export { generateExternalFunctionFile } from "./external/externalFunctionEmitter";

export interface CompiledExternalResult {
  /** Files to write into packages/external-apis/ */
  files: CompiledFile[];
  /** ReusableFunction metadata for each compiled tool — used by route generators for imports */
  reusableFunctions: ReusableFunction[];
  /** The global package name, e.g. "@workspace/external-apis" */
  globalPackageName?: string;
}

const GLOBAL_EXTERNAL_PKG = "@workspace/external-apis";

/**
 * Compiles all external API nodes into a shared package:
 * `packages/external-apis/`
 *
 * Exports typed async functions for each external node that can be called
 * directly or imported into route handlers.
 *
 * @param allNodes - All canvas nodes (filters to `type === "external"`).
 * @param allEdges - All canvas edges (reserved for future use).
 * @returns        - {@link CompiledExternalResult}
 *
 * @debugTag compile-external-nodes
 */
export function compileExternalNodes(
  allNodes: BackendNode[],
  allEdges: BackendEdge[] = [],
): CompiledExternalResult {
  // Silence unused-parameter lint while keeping the signature consistent
  void allEdges;

  const externalNodes = allNodes.filter((n) => n.type === "external");

  if (externalNodes.length === 0) {
    return { files: [], reusableFunctions: [] };
  }

  const allFiles: CompiledFile[] = [];
  const allReusable: ReusableFunction[] = [];
  const barrelExports: string[] = [];

  externalNodes.forEach((node) => {
    const rawFnName = node.data?.functionName || node.data?.label || "callExternalApi";
    const fnName = toVarName(rawFnName);
    const Pascal = toPascalCase(fnName);
    const inputTypeName = `${Pascal}Input`;
    const outputTypeName = `${Pascal}Output`;

    // ✦ Delegate per-node file generation to the emitter sub-module
    const file = generateExternalFunctionFile(node);

    // ✦ emits: packages/external-apis/src/<fnName>.ts
    allFiles.push({
      filename: `packages/external-apis/${file.filename}`,
      language: file.language,
      content: file.content,
    });

    barrelExports.push(`export * from "./${fnName}";`);

    allReusable.push({
      name: fnName,
      importPath: GLOBAL_EXTERNAL_PKG,
      signature: `${fnName}(input: ${inputTypeName}): Promise<${outputTypeName}>`,
      targetName: node.data?.label ?? fnName,
      kind: "custom",
    });
  });

  // ✦ emits: packages/external-apis/src/index.ts
  allFiles.push({
    filename: "packages/external-apis/src/index.ts",
    language: "typescript",
    content: `/**\n * External API Calling Tools (@workspace/external-apis)\n * Auto-generated by Dezign2App Monorepo Compiler\n */\n\n${barrelExports.join("\n")}\n`,
  });

  // ✦ emits: packages/external-apis/package.json
  allFiles.push({
    filename: "packages/external-apis/package.json",
    language: "json",
    content: JSON.stringify(
      {
        name: GLOBAL_EXTERNAL_PKG,
        version: "0.0.1",
        private: true,
        type: "module",
        main: "src/index.ts",
        types: "src/index.ts",
        exports: {
          ".": "./src/index.ts",
          "./*": "./src/*.ts",
        },
        scripts: { build: "tsc", "check-types": "tsc --noEmit" },
        devDependencies: {
          "@workspace/typescript-config": "workspace:*",
          typescript: "^5.3.3",
        },
      },
      null,
      2,
    ),
  });

  // ✦ emits: packages/external-apis/tsconfig.json
  allFiles.push({
    filename: "packages/external-apis/tsconfig.json",
    language: "json",
    content: JSON.stringify(
      {
        extends: "@workspace/typescript-config/base.json",
        compilerOptions: { outDir: "./dist", rootDir: "./src" },
        include: ["src/**/*"],
      },
      null,
      2,
    ),
  });

  return {
    files: allFiles,
    reusableFunctions: allReusable,
    globalPackageName: GLOBAL_EXTERNAL_PKG,
  };
}
