import type { CompileContext } from "../types";
import { toCamelCase, toPascalCase, getEnvKey } from "../utils";

/**
 * Builds `src/index.ts` for package mode.
 *
 * Exports the compiled graph instance plus the state types so any workspace
 * service can do:
 *   import { chatGraph, ChatStateType } from "@workspace/<name>";
 */
export function buildLibIndexFile(ctx: CompileContext): string {
  const graphVarName = `${toCamelCase(ctx.graphId)}Graph`;
  const schemaName = `${toPascalCase(ctx.graphId)}State`;

  return `/**
 * @workspace package — LangGraph agent compiled by Dezign2App Studio
 * Import the graph and state types from this package in any service.
 *
 * @example
 *   import { ${graphVarName}, type ${schemaName}Type } from "${ctx.input.packageName || `@workspace/${toCamelCase(ctx.graphId)}`}";
 */
export { ${graphVarName} } from "./graph";
export type { ${schemaName}Type, ${schemaName}UpdateType } from "./state";
`;
}

/**
 * Builds `package.json` for package mode (workspace package).
 *
 * Includes:
 * - `"exports"` field for proper ESM resolution
 * - `"main"` / `"types"` for CommonJS fallback consumers
 * - `"peerDependencies"` so workspace services share one copy of langgraph
 */
export function buildLibPackageJson(
  pkgId: string,
  deps: Record<string, string>,
  packageName?: string,
): string {
  const devDependencies: Record<string, string> = {
    "@workspace/typescript-config": "workspace:*",
    "@types/node": "^20.11.0",
    typescript: "^5.3.3",
  };

  // Move langgraph / core to peerDeps so the consuming service provides them
  const peerDependencies: Record<string, string> = {};
  const runtimeDeps: Record<string, string> = {};

  const PEER_PKGS = new Set([
    "@langchain/langgraph",
    "@langchain/core",
    "zod",
  ]);

  for (const [pkg, ver] of Object.entries(deps)) {
    if (PEER_PKGS.has(pkg)) {
      peerDependencies[pkg] = ver;
    } else {
      runtimeDeps[pkg] = ver;
    }
  }

  const resolvedPkgName =
    packageName ||
    (pkgId.startsWith("@")
      ? pkgId
      : `@workspace/${pkgId}`);

  return JSON.stringify(
    {
      name: resolvedPkgName,
      version: "0.0.1",
      private: true,
      description: `Compiled LangGraph agent — ${pkgId} (generated by Dezign2App Studio)`,
      main: "src/index.ts",
      types: "src/index.ts",
      exports: {
        ".": {
          types: "./src/index.ts",
          import: "./src/index.ts",
          require: "./src/index.ts",
          default: "./src/index.ts",
        },
      },
      scripts: {
        build: "tsc",
        "check-types": "tsc --noEmit",
      },
      dependencies: runtimeDeps,
      peerDependencies,
      devDependencies,
    },
    null,
    2,
  );
}

/**
 * Builds `tsconfig.json` for package mode.
 * Extends the workspace base config.
 */
export function buildLibTsConfig(): string {
  return JSON.stringify(
    {
      extends: "@workspace/typescript-config/base.json",
      compilerOptions: {
        outDir: "./dist",
        rootDir: "./src",
        declaration: true,
        declarationMap: true,
        lib: ["ES2022"],
      },
      include: ["src/**/*"],
      exclude: ["dist", "node_modules"],
    },
    null,
    2,
  );
}

/**
 * Builds `README.md` for package mode.
 */
export function buildLibReadme(
  ctx: CompileContext,
  pkgId: string,
): string {
  const graphVarName = `${toCamelCase(ctx.graphId)}Graph`;
  const schemaName = `${toPascalCase(ctx.graphId)}State`;
  const envVars = ctx.llmNodes
    .map((l) => getEnvKey(l.data))
    .filter((v): v is string => v !== null)
    .filter((v, i, a) => a.indexOf(v) === i);

  return `# @workspace/${pkgId}

Reusable **LangGraph v1.x** package for **${ctx.input.graphLabel || pkgId}**, compiled by Dezign2App Studio.

## Usage in another service

Add to your service's \`package.json\`:
\`\`\`json
{
  "dependencies": {
    "@workspace/${pkgId}": "workspace:*"
  }
}
\`\`\`

Then import in your code:
\`\`\`typescript
import { ${graphVarName} } from "@workspace/${pkgId}";
import type { ${schemaName}Type } from "@workspace/${pkgId}";

const result = await ${graphVarName}.invoke({
  messages: [{ role: "user", content: "Hello!" }],
}${ctx.hasMemory ? `,\n  { configurable: { thread_id: "session-1" } }` : ""});
\`\`\`

## Build

From the **monorepo root**:
\`\`\`bash
pnpm --filter @workspace/${pkgId} build
\`\`\`

${envVars.length > 0 ? `## Environment Variables\n\nCreate a \`.env\` file:\n\`\`\`env\n${envVars.map((v) => `${v}=your_key_here`).join("\n")}\n\`\`\`\n` : ""}
## Graph Overview
- **Nodes (${ctx.agentNodes.length + ctx.stepNodes.length}):** ${[...ctx.agentNodes.map((a) => a.data.name || a.data.label), ...ctx.stepNodes.map((s) => s.data.label)].filter(Boolean).join(", ") || "Default pipeline"}
- **Tools (${ctx.toolNodes.length}):** ${ctx.toolNodes.map((t) => t.data.name).filter(Boolean).join(", ") || "None"}
- **LLM Providers:** ${[...new Set(ctx.llmNodes.map((l) => l.data.provider))].join(", ") || "Default"}
`;
}
