import type { CompileContext } from "../types";
import { toCamelCase, toPascalCase, getEnvKey } from "../utils";

/**
 * Builds `src/index.ts` for package mode.
 *
 * Exports the compiled graph instance plus the state types so any workspace
 * service can do:
 *   import { chatGraph, ChatStateType } from "@workspace/<name>";
 */
export function buildLibIndexFile(ctx: CompileContext): string {
  const graphVarName = `${toCamelCase(ctx.graphId)}Graph`;
  const schemaName = `${toPascalCase(ctx.graphId)}State`;
  const targetNodeId = ctx.input.targetNodeId;
  const altVarName = targetNodeId
    ? `${targetNodeId.replace(/[^a-zA-Z0-9]/g, "")}Graph`
    : "";

  const extraExports: string[] = [];
  if (altVarName && altVarName !== graphVarName) {
    extraExports.push(`export { ${graphVarName} as ${altVarName} } from "./graph.js";`);
  }
  if (graphVarName !== "agentGraph" && altVarName !== "agentGraph") {
    extraExports.push(`export { ${graphVarName} as agentGraph } from "./graph.js";`);
  }
  extraExports.push(`export default ${graphVarName};`);

  return `/**
 * @workspace package — LangGraph agent compiled by Dezign2App Studio
 * Import the graph and state types from this package in any service.
 *
 * @example
 *   import { ${graphVarName}, type ${schemaName}Type } from "${ctx.input.packageName || `@workspace/${toCamelCase(ctx.graphId)}`}";
 */
export { ${graphVarName} } from "./graph.js";
${extraExports.join("\n")}
export type { ${schemaName}Type, ${schemaName}UpdateType } from "./state.js";
`;
}

/**
 * Builds `package.json` for package mode (workspace package).
 *
 * Includes:
 * - `"exports"` field for proper ESM resolution
 * - `"main"` / `"types"` for CommonJS fallback consumers
 * - `"peerDependencies"` so workspace services share one copy of langgraph
 */
export function buildLibPackageJson(
  pkgId: string,
  deps: Record<string, string>,
  packageName?: string,
): string {
  const devDependencies: Record<string, string> = {
    "@types/node": "^22.0.0",
    tsx: "^4.19.0",
    typescript: "^5.7.0",
  };

  // Move langgraph / core to peerDeps so the consuming service provides them
  const peerDependencies: Record<string, string> = {};
  const runtimeDeps: Record<string, string> = {};

  const PEER_PKGS = new Set([
    "@langchain/langgraph",
    "@langchain/core",
    "zod",
  ]);

  for (const [pkg, ver] of Object.entries(deps)) {
    if (PEER_PKGS.has(pkg)) {
      peerDependencies[pkg] = ver;
    } else {
      runtimeDeps[pkg] = ver;
    }
  }

  const resolvedPkgName =
    packageName ||
    (pkgId.startsWith("@")
      ? pkgId
      : `@workspace/${pkgId.startsWith("langgraph-") ? pkgId : `langgraph-${pkgId}`}`);

  return JSON.stringify(
    {
      name: resolvedPkgName,
      version: "0.0.1",
      private: true,
      description: `Compiled LangGraph agent — ${pkgId} (generated by Dezign2App Studio)`,
      type: "module",
      exports: {
        ".": {
          import: "./dist/index.js",
          types: "./dist/index.d.ts",
        },
      },
      main: "./dist/index.js",
      types: "./dist/index.d.ts",
      scripts: {
        build: "tsc",
        dev: "tsx watch src/index.ts",
        typecheck: "tsc --noEmit",
      },
      dependencies: runtimeDeps,
      peerDependencies,
      devDependencies,
    },
    null,
    2,
  );
}

/**
 * Builds `tsconfig.json` for package mode.
 * Emits declarations so consuming packages get full type information.
 */
export function buildLibTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        lib: ["ES2022"],
        types: ["node"],
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        outDir: "./dist",
        rootDir: "./src",
        declaration: true,
        declarationMap: true,
        sourceMap: true,
      },
      include: ["src/**/*"],
      exclude: ["dist", "node_modules"],
    },
    null,
    2,
  );
}

/**
 * Builds `README.md` for package mode.
 */
export function buildLibReadme(
  ctx: CompileContext,
  pkgId: string,
): string {
  const graphVarName = `${toCamelCase(ctx.graphId)}Graph`;
  const schemaName = `${toPascalCase(ctx.graphId)}State`;
  const envVars = ctx.llmNodes
    .map((l) => getEnvKey(l.data))
    .filter((v): v is string => v !== null)
    .filter((v, i, a) => a.indexOf(v) === i);

  return `# @workspace/${pkgId}

Reusable **LangGraph v1.x** package for **${ctx.input.graphLabel || pkgId}**, compiled by Dezign2App Studio.

## Usage in another service

Add to your service's \`package.json\`:
\`\`\`json
{
  "dependencies": {
    "@workspace/${pkgId}": "workspace:*"
  }
}
\`\`\`

Then import in your code:
\`\`\`typescript
import { ${graphVarName} } from "@workspace/${pkgId}";
import type { ${schemaName}Type } from "@workspace/${pkgId}";

const result = await ${graphVarName}.invoke({
  messages: [{ role: "user", content: "Hello!" }],
}${ctx.hasMemory ? `,\n  { configurable: { thread_id: "session-1" } }` : ""});
\`\`\`

## Build

From the **monorepo root**:
\`\`\`bash
pnpm --filter @workspace/${pkgId} build
\`\`\`

${envVars.length > 0 ? `## Environment Variables\n\nCreate a \`.env\` file:\n\`\`\`env\n${envVars.map((v) => `${v}=your_key_here`).join("\n")}\n\`\`\`\n` : ""}
## Graph Overview
- **Nodes (${ctx.agentNodes.length + ctx.stepNodes.length}):** ${[...ctx.agentNodes.map((a) => a.data.name || a.data.label), ...ctx.stepNodes.map((s) => s.data.label)].filter(Boolean).join(", ") || "Default pipeline"}
- **Tools (${ctx.toolNodes.length}):** ${ctx.toolNodes.map((t) => t.data.name).filter(Boolean).join(", ") || "None"}
- **LLM Providers:** ${[...new Set(ctx.llmNodes.map((l) => l.data.provider))].join(", ") || "Default"}
`;
}
