import React from "react";
import { Settings, Zap, FunctionSquare, ChevronDown, ChevronUp } from "lucide-react";
import { useBackendCanvasStore } from "@/lib/stores/backendCanvasStore";
import { BackendNodeData, DbOperationFunction } from "@workspace/canvas/types";
import { generateDefaultDbOperations, getEntityDbOperations } from "@/lib/utils/entityOperationsHelper";
import { cn } from "@workspace/ui/lib/utils";

interface DbOperationsListProps {
  nodeId: string;
  data: BackendNodeData;
  updateNode: (id: string, changes: Partial<{ data: BackendNodeData }>) => void;
}

export const DbOperationsList: React.FC<DbOperationsListProps> = ({
  nodeId,
  data,
}) => {
  const setActiveConfigItem = useBackendCanvasStore((s) => s.setActiveConfigItem);
  const allNodes = useBackendCanvasStore((s) => s.nodes);
  const [isExpanded, setIsExpanded] = React.useState(false);

  const columns = data.columns || [];
  const indexes = data.indexes || [];

  // Fallback to auto-generated operations if not explicitly initialized
  const parentDb = allNodes.find((n) => n.id === data.databaseId);
  const engine = parentDb?.data?.dbEngine || "sqlite";
  const dbOps: DbOperationFunction[] = getEntityDbOperations({ data }, allNodes, engine);

  const activeOps = dbOps.filter((op) => op.enabled !== false);

  const openConfig = (e: React.MouseEvent) => {
    e.stopPropagation();
    setActiveConfigItem({
      type: "entityFunctions",
      id: nodeId,
      nodeId: nodeId,
    });
  };

  return (
    <div className="border-t border-border/40 nodrag">
      <div
        className="px-3 py-1.5 bg-secondary/30 text-[10px] font-bold text-muted-foreground uppercase tracking-wider flex justify-between items-center group cursor-pointer hover:bg-secondary/50 transition-colors"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <div className="flex items-center gap-1.5">
          <FunctionSquare size={12} className="text-muted-foreground" />
          <span>DB Operations ({activeOps.length})</span>
        </div>
        <div className="flex items-center gap-1">
          <div
            className="p-1 rounded hover:bg-background text-muted-foreground hover:text-foreground transition-all cursor-pointer"
            title="Manage DB Operations"
            onClick={openConfig}
          >
            <Settings size={12} />
          </div>
          {isExpanded ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
        </div>
      </div>

      {isExpanded && (
        <div className="flex flex-col divide-y divide-border/20 max-h-[180px] overflow-y-auto">
          {dbOps.map((op) => {
            const isEnabled = op.enabled !== false;
            const isPaginated = op.pagination?.enabled;
            return (
              <div
                key={op.id}
                className={cn(
                  "px-3 py-1.5 flex items-center justify-between text-xs hover:bg-secondary/20 transition-colors cursor-pointer group/op",
                  !isEnabled && "opacity-40 line-through",
                )}
                onClick={openConfig}
              >
                <div className="flex items-center gap-2 overflow-hidden flex-1 min-w-0">
                  <span className="px-1.5 py-0.5 rounded text-[9px] font-mono font-semibold uppercase shrink-0 bg-secondary text-secondary-foreground border border-border/40">
                    {op.kind === "fetchByIndex" ? "INDEX" : op.kind}
                  </span>
                  <span className="font-mono text-[11px] truncate font-medium text-foreground">
                    {op.name}
                  </span>
                  {isPaginated && (
                    <span
                      className="px-1 py-0.2 text-[8px] font-mono rounded bg-muted/60 text-muted-foreground shrink-0 border border-border/30"
                      title={`Paginated (${op.pagination?.mode || "offset"}, limit: ${op.pagination?.defaultLimit || 20})`}
                    >
                      PAGE
                    </span>
                  )}
                </div>
                {op.isAutoGenerated && (
                  <span
                    className="text-[9px] text-muted-foreground/60 shrink-0 ml-1 flex items-center gap-0.5"
                    title="Auto-generated operation"
                  >
                    <Zap size={9} className="text-muted-foreground/70" />
                  </span>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
