import React from "react";
import { BackendNode, RedisDataStructure } from "@/types/canvas";
import { generateRedisOperations } from "@/lib/utils/entityOperationsHelper";
import { Input } from "@workspace/ui/components/input";
import { Badge } from "@workspace/ui/components/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@workspace/ui/components/select";
import {
  DatabaseZap,
  Key,
  Layers,
  Sparkles,
  Clock,
  Radio,
  MapPin,
  ListOrdered,
  List,
  Binary,
  Share2,
} from "lucide-react";

export interface RedisConfigProps {
  id: string;
  data: BackendNode["data"];
  updateNode: (id: string, changes: Partial<BackendNode>) => void;
}

export const REDIS_DATA_STRUCTURE_OPTIONS: Array<{
  value: RedisDataStructure;
  label: string;
  icon: React.ComponentType<{ className?: string; size?: number }>;
  desc: string;
}> = [
  { value: "hash", label: "Hash", icon: Layers, desc: "Field-value mapping (HSET, HGET)" },
  { value: "string", label: "String / Counter", icon: DatabaseZap, desc: "Raw string, number or binary" },
  { value: "json", label: "RedisJSON", icon: Sparkles, desc: "Native nested JSON document" },
  { value: "set", label: "Set", icon: Share2, desc: "Unordered collection of unique strings" },
  { value: "list", label: "List", icon: List, desc: "Ordered collection of strings (LPUSH/RPUSH)" },
  { value: "zset", label: "Sorted Set (ZSet)", icon: ListOrdered, desc: "Ranked collection by score (ZADD)" },
  { value: "geo", label: "Geospatial (GEO)", icon: MapPin, desc: "Longitude & latitude points" },
  { value: "stream", label: "Stream", icon: Radio, desc: "Append-only log with consumer groups" },
  { value: "bitfield", label: "Bitfield", icon: Binary, desc: "Packed subfields with bit offsets" },
  { value: "bitmap", label: "Bitmap", icon: Binary, desc: "Boolean bit array flags" },
  { value: "hyperloglog", label: "HyperLogLog", icon: DatabaseZap, desc: "Probabilistic cardinality estimation" },
];

/**
 * Extracts `{var}` parameter names from key template string
 */
export function extractKeyTemplateParams(template: string): string[] {
  const matches = template.match(/\{([^}]+)\}/g);
  if (!matches) return [];
  return matches.map((m) => m.replace(/[{}]/g, "").trim()).filter(Boolean);
}

/**
 * Auto-derives wildcard pattern (e.g. user:*:profile) from keyTemplate
 */
export function deriveKeyPattern(template: string): string {
  if (!template) return "*";
  return template.replace(/\{[^}]+\}/g, "*");
}

/**
 * Auto-derives namespace prefix from keyTemplate (before first parameter or colon)
 */
export function deriveNamespace(template: string): string {
  if (!template) return "default";
  const colonIdx = template.indexOf(":");
  const braceIdx = template.indexOf("{");
  if (colonIdx !== -1 && (braceIdx === -1 || colonIdx < braceIdx)) {
    return template.slice(0, colonIdx);
  }
  if (braceIdx !== -1) {
    return template.slice(0, braceIdx).replace(/[:_.-]+$/, "") || "default";
  }
  return template;
}

export const RedisConfig: React.FC<RedisConfigProps> = React.memo(({
  id,
  data,
  updateNode,
}) => {
  const structure: RedisDataStructure = data.redisDataStructure || "hash";
  const template = data.keyTemplate ?? "";
  const clusterTagParam = data.clusterHashTagParam;

  const [localTemplate, setLocalTemplate] = React.useState(template);

  React.useEffect(() => {
    setLocalTemplate(template);
  }, [template]);

  const commitTemplate = React.useCallback(
    (val: string) => {
      if (val === (data.keyTemplate ?? "")) return;
      const newParams = extractKeyTemplateParams(val);
      const newClusterTag =
        clusterTagParam && newParams.includes(clusterTagParam)
          ? clusterTagParam
          : newParams[0] || undefined;

      updateNode(id, {
        data: {
          ...data,
          keyTemplate: val,
          clusterHashTagParam: newClusterTag,
        },
      });
    },
    [id, data, clusterTagParam, updateNode],
  );

  const keyPattern = deriveKeyPattern(localTemplate);
  const params = extractKeyTemplateParams(localTemplate);
  const ttl = data.ttl || { value: 3600, unit: "s" };
  const strategy = data.cacheStrategy || "Cache Aside";

  const handleStructureChange = React.useCallback(
    (val: RedisDataStructure) => {
      const customOps = (data.dbOperations || []).filter((op) => !op.isAutoGenerated);
      const newDefaults = generateRedisOperations(data.label || "Cache", {
        ...data,
        redisDataStructure: val,
      });
      updateNode(id, {
        data: {
          ...data,
          redisDataStructure: val,
          dbOperations: data.dbOperations ? [...newDefaults, ...customOps] : undefined,
        },
      });
    },
    [id, data, updateNode],
  );

  return (
    <div className="flex flex-col gap-1.5 p-2 bg-muted/20 border-b border-border/40 nodrag">
      {/* Key Template Input & Auto-Pattern Display */}
      <div className="flex flex-col gap-1">
        <div className="flex items-center justify-between text-[10px]">
          <span className="font-semibold text-muted-foreground uppercase tracking-wider flex items-center gap-1.5">
            <Key size={11} className="text-amber-500" /> Key Template
          </span>
          <code
            className="text-[10px] font-mono font-medium px-1.5 py-0.5 rounded bg-background/80 text-foreground/80 border border-border/50 max-w-[170px] truncate"
            title={`Scan Pattern: ${keyPattern}`}
          >
            {keyPattern}
          </code>
        </div>
        <Input
          className="h-7 text-xs font-mono font-medium bg-background border-border/60 focus-visible:ring-primary/30"
          placeholder="e.g. user:{id}:profile"
          value={localTemplate}
          onChange={(e) => setLocalTemplate(e.target.value)}
          onBlur={() => commitTemplate(localTemplate)}
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              commitTemplate(localTemplate);
            }
          }}
        />
        {/* Cluster Hash Tag Badge & Variable Chips */}
        {params.length > 0 && (
          <div className="flex items-center gap-1 flex-wrap pt-0.5">
            {params.map((param) => {
              const isClusterTag = clusterTagParam === param;
              return (
                <Badge
                  key={param}
                  variant="outline"
                  className={`text-[10px] px-1.5 py-0.5 font-mono font-medium cursor-pointer transition-colors ${
                    isClusterTag
                      ? "bg-primary/15 border-primary/40 text-primary"
                      : "bg-background/60 text-muted-foreground border-border/50 hover:border-border"
                  }`}
                  title={
                    isClusterTag
                      ? "Redis Cluster Hash Tag (forces shard co-location)"
                      : "Click to set as Cluster Hash Tag"
                  }
                  onClick={() => {
                    commitTemplate(localTemplate);
                    updateNode(id, {
                      data: {
                        ...data,
                        keyTemplate: localTemplate,
                        clusterHashTagParam: isClusterTag ? undefined : param,
                      },
                    });
                  }}
                >
                  {isClusterTag ? `{${param}} ⚡` : param}
                </Badge>
              );
            })}
          </div>
        )}
      </div>

      {/* Badges Strip (Structure, TTL, Strategy) */}
      <div className="flex items-center justify-between gap-1 pt-1 border-t border-border/30 text-[10px] text-muted-foreground">
        <div className="flex items-center gap-1">
          <Select
            value={structure}
            onValueChange={(val: RedisDataStructure) => handleStructureChange(val)}
          >
            <SelectTrigger className="nodrag h-6 text-[10px] w-auto gap-1 px-2 font-medium bg-background border-border/60">
              <SelectValue>
                {structure === "json" && data.jsonRootType === "array"
                  ? "RedisJSON[]"
                  : REDIS_DATA_STRUCTURE_OPTIONS.find((o) => o.value === structure)?.label || structure}
              </SelectValue>
            </SelectTrigger>
            <SelectContent position="popper" className="nodrag z-50">
              {REDIS_DATA_STRUCTURE_OPTIONS.map((opt) => (
                <SelectItem key={opt.value} value={opt.value} className="text-xs">
                  {opt.value === "json" && data.jsonRootType === "array"
                    ? "RedisJSON[]"
                    : opt.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          {/* [ ] Array of Objects Toggle Button */}
          <button
            type="button"
            className={`nodrag h-6 px-1.5 rounded border text-[10px] font-mono font-medium transition-all cursor-pointer flex items-center justify-center ${
              structure === "json" && data.jsonRootType === "array"
                ? "bg-primary/15 border-primary/40 text-primary shadow-xs"
                : "bg-background/80 border-border/50 text-muted-foreground hover:text-foreground hover:border-border"
            }`}
            title={
              structure === "json" && data.jsonRootType === "array"
                ? "Array of Objects []. Click to switch to Object {}"
                : "Click to toggle Array of Objects [] mode"
            }
            onClick={(e) => {
              e.stopPropagation();
              const isCurrentlyArray = structure === "json" && data.jsonRootType === "array";
              const nextRootType = isCurrentlyArray ? "object" : "array";
              const customOps = (data.dbOperations || []).filter((op) => !op.isAutoGenerated);
              const newDefaults = generateRedisOperations(data.label || "Cache", {
                ...data,
                redisDataStructure: "json",
                jsonRootType: nextRootType,
              });
              updateNode(id, {
                data: {
                  ...data,
                  redisDataStructure: "json",
                  jsonRootType: nextRootType,
                  dbOperations: data.dbOperations ? [...newDefaults, ...customOps] : undefined,
                },
              });
            }}
          >
            [ ]
          </button>

          <div className="flex items-center gap-1 px-1.5 py-0.5 rounded bg-background/80 border border-border/50 font-mono text-[10px]">
            <Clock size={10} className="text-amber-500" />
            <span>{ttl.unit === "never" ? "No TTL" : `${ttl.value}${ttl.unit}`}</span>
          </div>
        </div>

        <div className="flex items-center gap-1 font-mono text-[10px]">
          <span className="px-1.5 py-0.5 rounded bg-background/80 border border-border/50">
            {strategy}
          </span>
          {data.negativeCaching?.enabled && (
            <span
              className="px-1.5 py-0.5 rounded bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/30 text-[9px] font-medium"
              title="Negative caching enabled"
            >
              404
            </span>
          )}
          {data.staleWhileRevalidate?.enabled && (
            <span
              className="px-1.5 py-0.5 rounded bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/30 text-[9px] font-medium"
              title="SWR enabled"
            >
              SWR
            </span>
          )}
        </div>
      </div>
    </div>
  );
});
