"use client";

import React, { useState, useEffect } from "react";
import { useSimulationStore } from "@/lib/stores/simulationStore";
import { useMutation } from "convex/react";
import { api } from "@workspace/backend/_generated/api";
import { Id } from "@workspace/backend/_generated/dataModel";
import { useParams } from "next/navigation";
import { Endpoint, BackendNode } from "@/types/canvas";
import { SimulationTestCase } from "@workspace/canvas";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@workspace/ui/components/accordion";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@workspace/ui/components/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogClose,
  DialogTrigger,
} from "@workspace/ui/components/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@workspace/ui/components/select";
import { Button } from "@workspace/ui/components/button";
import { Input } from "@workspace/ui/components/input";
import { Label } from "@workspace/ui/components/label";
import {
  FlaskConical,
  Plus,
  Zap,
  SlidersHorizontal,
} from "lucide-react";
import {
  generateDefaultTestCases,
  createTestCaseFromPreset,
  generateId,
} from "./utils";
import { EndpointTestCaseEditor } from "./EndpointTestCaseEditor";
import { toast } from "sonner";
import { cn } from "@workspace/ui/lib/utils";

interface EndpointTestCasesSectionProps {
  endpoint: Endpoint;
  nodeId: string;
  serviceNode?: BackendNode | null;
}

export function EndpointTestCasesSection({
  endpoint,
  nodeId,
  serviceNode,
}: EndpointTestCasesSectionProps) {
  const paramsHook = useParams();
  const projectId = paramsHook.projectId as Id<"projects">;

  const testCases = useSimulationStore((s) => s.testCases);
  const addTestCase = useSimulationStore((s) => s.addTestCase);
  const updateTestCase = useSimulationStore((s) => s.updateTestCase);
  const deleteTestCase = useSimulationStore((s) => s.deleteTestCase);

  const upsertBackendTestCase = useMutation(api.canvas.upsertBackendTestCase);
  const removeBackendTestCase = useMutation(api.canvas.removeBackendTestCase);

  // Filter test cases targeting this endpoint
  const endpointCases = testCases.filter(
    (tc) =>
      (tc.targetNodeId === nodeId && tc.targetEventId === endpoint.id) ||
      tc.targetEventId === endpoint.id,
  );

  // Separate Auto-Generated vs Manual test cases
  const autoCases = endpointCases.filter(
    (tc) =>
      tc.isAutoGenerated === true ||
      tc.category === "auto" ||
      tc.id.startsWith("auto-") ||
      tc.name.includes("Valid Request") ||
      tc.name.includes("Validation Error"),
  );

  const manualCases = endpointCases.filter(
    (tc) =>
      !(
        tc.isAutoGenerated === true ||
        tc.category === "auto" ||
        tc.id.startsWith("auto-") ||
        tc.name.includes("Valid Request") ||
        tc.name.includes("Validation Error")
      ),
  );

  const [activeTab, setActiveTab] = useState<"auto" | "manual">("auto");
  const [newTcOpen, setNewTcOpen] = useState(false);
  const [newTcName, setNewTcName] = useState("");
  const [newTcPreset, setNewTcPreset] = useState<
    "200_ok" | "201_created" | "400_bad_request" | "401_unauthorized" | "404_not_found" | "custom"
  >("200_ok");

  // Automatically populate basic contract test cases on mount if missing
  useEffect(() => {
    const hasSuccess = autoCases.some(
      (tc) =>
        tc.id === `auto-${endpoint.id}-success` ||
        tc.expectedStatus === 200 ||
        tc.expectedStatus === 201,
    );
    const hasValidation = autoCases.some(
      (tc) =>
        tc.id === `auto-${endpoint.id}-validation` ||
        tc.expectedStatus === 400,
    );

    if (!hasSuccess || !hasValidation) {
      const generated = generateDefaultTestCases(endpoint, nodeId, serviceNode);
      generated.forEach((genCase) => {
        const alreadyExists = endpointCases.some(
          (tc) => tc.id === genCase.id || tc.expectedStatus === genCase.expectedStatus,
        );
        if (!alreadyExists) {
          addTestCase(genCase);
          if (projectId) {
            upsertBackendTestCase({
              projectId,
              testCaseId: genCase.id,
              data: genCase,
            });
          }
        }
      });
    }
  }, [endpoint.id, nodeId, projectId, autoCases.length, endpointCases.length]);

  // Create new manual test case
  const handleCreateNewManual = () => {
    const newCase = createTestCaseFromPreset(
      newTcPreset,
      endpoint,
      nodeId,
      newTcName.trim() || undefined,
    );

    addTestCase(newCase);
    if (projectId) {
      upsertBackendTestCase({
        projectId,
        testCaseId: newCase.id,
        data: newCase,
      });
    }

    setNewTcOpen(false);
    setNewTcName("");
    setActiveTab("manual");
    toast.success(`Created manual test case: ${newCase.name}`);
  };

  // Update test case
  const handleUpdate = (updated: SimulationTestCase) => {
    updateTestCase(updated.id, {
      name: updated.name,
      request: updated.request,
      expectedStatus: updated.expectedStatus,
      expectedBody: updated.expectedBody,
      mocks: updated.mocks,
      isAutoGenerated: updated.isAutoGenerated,
      category: updated.category,
    });

    if (projectId) {
      upsertBackendTestCase({
        projectId,
        testCaseId: updated.id,
        data: updated,
      });
    }
  };

  // Delete test case
  const handleDelete = (tcId: string) => {
    deleteTestCase(tcId);
    if (projectId) {
      removeBackendTestCase({ projectId, testCaseId: tcId });
    }
    toast.success("Test case deleted");
  };

  // Duplicate test case
  const handleDuplicate = (tc: SimulationTestCase) => {
    const duplicated: SimulationTestCase = {
      ...tc,
      id: generateId(),
      name: `${tc.name} (Copy)`,
      isAutoGenerated: false,
      category: "manual",
    };
    addTestCase(duplicated);
    if (projectId) {
      upsertBackendTestCase({
        projectId,
        testCaseId: duplicated.id,
        data: duplicated,
      });
    }
    setActiveTab("manual");
    toast.success("Test case duplicated to Manual Cases");
  };

  const method = (endpoint.type || "GET").toUpperCase();

  return (
    <div className="flex flex-col gap-3 rounded-xl bg-card/50 p-4 shadow-sm backdrop-blur-sm mt-2 font-sans border border-border/50">
      {/* Section Main Header */}
      <div className="flex items-center justify-between border-b border-border/50 pb-3 gap-2 flex-wrap">
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-secondary text-muted-foreground border border-border/50">
            <FlaskConical className="w-4 h-4" />
          </div>
          <div className="flex flex-col">
            <div className="flex items-center gap-2">
              <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Endpoint Test Cases
              </span>
              <span className="px-1.5 py-0.2 rounded-full text-[10px] font-mono font-bold bg-secondary text-muted-foreground border border-border/50">
                {endpointCases.length}
              </span>
            </div>
            <span className="text-[11px] text-muted-foreground">
              Auto-generated basic cases & custom manual test suites.
            </span>
          </div>
        </div>

        <div className="flex items-center gap-1.5">
          {/* New Manual Case Dialog */}
          <Dialog open={newTcOpen} onOpenChange={setNewTcOpen}>
            <DialogTrigger asChild>
              <Button
                size="sm"
                variant="secondary"
                className="h-7 text-xs px-2.5 bg-secondary/80 hover:bg-secondary text-muted-foreground hover:text-foreground border border-border/50 shadow-none font-medium gap-1.5"
                onClick={() => {
                  setNewTcPreset(method === "POST" ? "201_created" : "200_ok");
                  setNewTcName("");
                }}
              >
                <Plus className="w-3.5 h-3.5 text-muted-foreground" />
                <span>New Case</span>
              </Button>
            </DialogTrigger>
            <DialogContent className="font-sans max-w-md">
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2 text-sm">
                  <FlaskConical className="w-4 h-4 text-muted-foreground" />
                  <span>Create Manual Test Case</span>
                </DialogTitle>
              </DialogHeader>

              <div className="py-3 flex flex-col gap-3">
                <div className="flex flex-col gap-1.5">
                  <Label className="text-xs font-medium">Preset Template</Label>
                  <Select
                    value={newTcPreset}
                    onValueChange={(val: any) => setNewTcPreset(val)}
                  >
                    <SelectTrigger className="text-xs h-8 bg-background border-border/60">
                      <SelectValue placeholder="Select template" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="200_ok" className="text-xs">
                        200 OK - Standard Success
                      </SelectItem>
                      <SelectItem value="201_created" className="text-xs">
                        201 Created - Resource Created
                      </SelectItem>
                      <SelectItem value="400_bad_request" className="text-xs">
                        400 Bad Request - Validation Error
                      </SelectItem>
                      <SelectItem value="401_unauthorized" className="text-xs">
                        401 Unauthorized - Missing / Invalid Token
                      </SelectItem>
                      <SelectItem value="404_not_found" className="text-xs">
                        404 Not Found - Non-Existent ID
                      </SelectItem>
                      <SelectItem value="custom" className="text-xs">
                        Custom Test Case
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="flex flex-col gap-1.5">
                  <Label className="text-xs font-medium">Test Case Name</Label>
                  <Input
                    value={newTcName}
                    onChange={(e) => setNewTcName(e.target.value)}
                    placeholder={`e.g. Custom Edge Case (${method} ${endpoint.name || ""})`}
                    autoFocus
                    className="text-xs h-8 bg-background border-border/60"
                    onKeyDown={(e) => {
                      if (e.key === "Enter") handleCreateNewManual();
                    }}
                  />
                </div>
              </div>

              <DialogFooter>
                <DialogClose asChild>
                  <Button variant="outline" size="sm">
                    Cancel
                  </Button>
                </DialogClose>
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={handleCreateNewManual}
                >
                  Create Test Case
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Tabs for Auto-Generated vs Manual Test Cases */}
      <Tabs
        value={activeTab}
        onValueChange={(v) => setActiveTab(v as any)}
        className="w-full"
      >
        <TabsList className="grid grid-cols-2 h-8 bg-background/60 p-0.5 rounded-lg border border-border/50 mb-2">
          <TabsTrigger
            value="auto"
            className="text-xs font-medium data-[state=active]:bg-secondary data-[state=active]:text-foreground data-[state=active]:font-semibold text-muted-foreground flex items-center gap-1.5 transition-all"
          >
            <Zap className="w-3.5 h-3.5 text-muted-foreground" />
            <span>Auto-Generated</span>
            <span className="px-1.5 py-0.2 rounded-full text-[10px] font-mono bg-secondary/80 text-muted-foreground border border-border/40">
              {autoCases.length}
            </span>
          </TabsTrigger>
          <TabsTrigger
            value="manual"
            className="text-xs font-medium data-[state=active]:bg-secondary data-[state=active]:text-foreground data-[state=active]:font-semibold text-muted-foreground flex items-center gap-1.5 transition-all"
          >
            <SlidersHorizontal className="w-3.5 h-3.5 text-muted-foreground" />
            <span>Manual Cases</span>
            <span className="px-1.5 py-0.2 rounded-full text-[10px] font-mono bg-secondary/80 text-muted-foreground border border-border/40">
              {manualCases.length}
            </span>
          </TabsTrigger>
        </TabsList>

        {/* Tab 1: Auto-Generated Cases */}
        <TabsContent value="auto" className="outline-none mt-1">
          {autoCases.length > 0 ? (
            <Accordion
              type="multiple"
              defaultValue={autoCases.length > 0 && autoCases[0] ? [autoCases[0].id] : undefined}
              className="w-full flex flex-col gap-2.5 border-none"
            >
              {autoCases.map((tc) => (
                <AccordionItem
                  key={tc.id}
                  value={tc.id}
                  className="bg-background/40 border border-border/50 rounded-xl overflow-hidden shadow-sm"
                >
                  <AccordionTrigger className="text-xs font-semibold px-3 py-2.5 hover:bg-secondary/20 hover:no-underline">
                    <div className="flex items-center justify-between flex-1 mr-2 gap-2">
                      <div className="flex items-center gap-2 truncate">
                        <span className="px-1.5 py-0.5 rounded text-[9px] font-mono font-bold uppercase bg-secondary/60 text-muted-foreground border border-border/40 shrink-0">
                          Auto
                        </span>
                        <span className="truncate text-foreground font-medium">
                          {tc.name}
                        </span>
                      </div>

                      <div className="flex items-center gap-1.5 shrink-0">
                        {tc.expectedStatus && (
                          <span
                            className={cn(
                              "px-2 py-0.5 rounded text-[10px] font-mono font-bold border",
                              tc.expectedStatus >= 200 && tc.expectedStatus < 300
                                ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
                                : tc.expectedStatus >= 400 && tc.expectedStatus < 500
                                ? "bg-amber-500/10 text-amber-400 border-amber-500/20"
                                : "bg-destructive/10 text-destructive border-destructive/20",
                            )}
                          >
                            {tc.expectedStatus}
                          </span>
                        )}
                      </div>
                    </div>
                  </AccordionTrigger>

                  <AccordionContent className="p-2 pt-0">
                    <EndpointTestCaseEditor
                      initialCase={tc}
                      endpoint={endpoint}
                      nodeId={nodeId}
                      serviceNode={serviceNode}
                      onSave={handleUpdate}
                      onDelete={() => handleDelete(tc.id)}
                      onDuplicate={handleDuplicate}
                    />
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          ) : (
            <div className="flex flex-col items-center justify-center p-6 border border-border/50 rounded-xl bg-background/20 border-dashed text-center gap-2.5">
              <Zap className="w-8 h-8 text-muted-foreground/30" />
              <div className="flex flex-col gap-0.5">
                <span className="text-xs font-medium text-foreground">
                  Populating contract test cases...
                </span>
                <span className="text-[11px] text-muted-foreground">
                  Basic Success (200) and Validation Error (400) cases are automatically generated.
                </span>
              </div>
            </div>
          )}
        </TabsContent>

        {/* Tab 2: Manual Test Cases */}
        <TabsContent value="manual" className="outline-none mt-1">
          {manualCases.length > 0 ? (
            <Accordion
              type="multiple"
              defaultValue={manualCases.length > 0 && manualCases[0] ? [manualCases[0].id] : undefined}
              className="w-full flex flex-col gap-2.5 border-none"
            >
              {manualCases.map((tc) => (
                <AccordionItem
                  key={tc.id}
                  value={tc.id}
                  className="bg-background/40 border border-border/50 rounded-xl overflow-hidden shadow-sm"
                >
                  <AccordionTrigger className="text-xs font-semibold px-3 py-2.5 hover:bg-secondary/20 hover:no-underline">
                    <div className="flex items-center justify-between flex-1 mr-2 gap-2">
                      <div className="flex items-center gap-2 truncate">
                        <span className="px-1.5 py-0.5 rounded text-[9px] font-mono font-bold uppercase bg-secondary/60 text-muted-foreground border border-border/40 shrink-0">
                          Manual
                        </span>
                        <span className="truncate text-foreground font-medium">
                          {tc.name}
                        </span>
                      </div>

                      <div className="flex items-center gap-1.5 shrink-0">
                        {tc.expectedStatus && (
                          <span
                            className={cn(
                              "px-2 py-0.5 rounded text-[10px] font-mono font-bold border",
                              tc.expectedStatus >= 200 && tc.expectedStatus < 300
                                ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
                                : tc.expectedStatus >= 400 && tc.expectedStatus < 500
                                ? "bg-amber-500/10 text-amber-400 border-amber-500/20"
                                : "bg-destructive/10 text-destructive border-destructive/20",
                            )}
                          >
                            {tc.expectedStatus}
                          </span>
                        )}
                      </div>
                    </div>
                  </AccordionTrigger>

                  <AccordionContent className="p-2 pt-0">
                    <EndpointTestCaseEditor
                      initialCase={tc}
                      endpoint={endpoint}
                      nodeId={nodeId}
                      serviceNode={serviceNode}
                      onSave={handleUpdate}
                      onDelete={() => handleDelete(tc.id)}
                      onDuplicate={handleDuplicate}
                    />
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          ) : (
            <div className="flex flex-col items-center justify-center p-6 border border-border/50 rounded-xl bg-background/20 border-dashed text-center gap-2.5">
              <SlidersHorizontal className="w-8 h-8 text-muted-foreground/30" />
              <div className="flex flex-col gap-0.5">
                <span className="text-xs font-medium text-foreground">
                  No manual test cases defined yet
                </span>
                <span className="text-[11px] text-muted-foreground">
                  Create custom test scenarios, edge cases, auth errors, and specific payloads.
                </span>
              </div>
              <Button
                size="sm"
                variant="secondary"
                className="h-7 text-xs px-3 bg-secondary/80 hover:bg-secondary text-muted-foreground hover:text-foreground border border-border/50 shadow-none gap-1.5 mt-1"
                onClick={() => {
                  setNewTcPreset(method === "POST" ? "201_created" : "200_ok");
                  setNewTcOpen(true);
                }}
              >
                <Plus className="w-3.5 h-3.5 text-muted-foreground" />
                <span>Add Manual Test Case</span>
              </Button>
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
