/**
 * Test case generation — auto-generated defaults and preset factory.
 */
import { Endpoint, BackendNode } from "@/types/canvas";
import { SimulationTestCase } from "@workspace/canvas";
import { generateId } from "./helpers";
import { getInitialBody } from "./fakeData";
import { sanitizeEndpointPath } from "./url";

/**
 * Builds the default request headers for an endpoint, injecting
 * internal JWT placeholder for authenticated internal endpoints.
 */
function buildDefaultHeaders(
  endpoint: Endpoint,
  serviceNode?: BackendNode | null,
): Record<string, string> {
  const headers: Record<string, string> = {};
  endpoint.headers?.forEach((h) => {
    const k = (h.key || h.name || "").toLowerCase();
    if (k) headers[k] = h.defaultValue || h.value || "";
  });

  const isExternal = serviceNode?.type === "external";
  if (!isExternal && endpoint.requireAuth !== false && !headers["authorization"]) {
    headers["authorization"] = "Bearer <test_jwt_token>";
  }

  const method = (endpoint.type || "GET").toUpperCase();
  if (["POST", "PUT", "PATCH"].includes(method) && !headers["content-type"]) {
    headers["content-type"] = "application/json";
  }

  return headers;
}

/**
 * Generates default 200 OK and 400 Bad Request test cases for an endpoint.
 */
export function generateDefaultTestCases(
  endpoint: Endpoint,
  nodeId: string,
  serviceNode?: BackendNode | null,
): SimulationTestCase[] {
  const method = (endpoint.type || "GET").toUpperCase();
  const path = sanitizeEndpointPath(endpoint.name || "/");
  const expectedSuccessStatus = method === "POST" ? 201 : 200;

  // Path params
  const defaultPathParams: Record<string, string> = {};
  endpoint.pathParams?.forEach((p) => {
    const k = p.key || p.name;
    if (k) defaultPathParams[k] = p.defaultValue || p.value || "1";
  });

  // Query params
  const defaultQueryParams: Record<string, string> = {};
  endpoint.queryParams?.forEach((p) => {
    const k = p.key || p.name;
    if (k) defaultQueryParams[k] = p.defaultValue || p.value || "sample";
  });

  const defaultHeaders = buildDefaultHeaders(endpoint, serviceNode);
  const successBody = getInitialBody(endpoint);

  const successCase: SimulationTestCase = {
    id: `auto-${endpoint.id}-success`,
    name: `${expectedSuccessStatus} OK - Valid Request (${method} ${path})`,
    targetNodeId: nodeId,
    targetEventId: endpoint.id,
    isAutoGenerated: true,
    category: "auto",
    request: {
      headers: defaultHeaders,
      params: { ...defaultPathParams, ...defaultQueryParams },
      body: successBody,
    },
    expectedStatus: expectedSuccessStatus,
    expectedBody: {
      success: true,
      data: successBody,
    },
    mocks: {},
  };

  const validationCase: SimulationTestCase = {
    id: `auto-${endpoint.id}-validation`,
    name: `400 Bad Request - Validation Error (${method} ${path})`,
    targetNodeId: nodeId,
    targetEventId: endpoint.id,
    isAutoGenerated: true,
    category: "auto",
    request: {
      headers: defaultHeaders,
      params: {},
      body: {},
    },
    expectedStatus: 400,
    expectedBody: {
      error: "Validation Error",
    },
    mocks: {},
  };

  return [successCase, validationCase];
}

/**
 * Creates a new test case by preset type.
 */
export function createTestCaseFromPreset(
  preset: "200_ok" | "201_created" | "400_bad_request" | "401_unauthorized" | "404_not_found" | "custom",
  endpoint: Endpoint,
  nodeId: string,
  customName?: string,
): SimulationTestCase {
  const method = (endpoint.type || "GET").toUpperCase();
  const path = sanitizeEndpointPath(endpoint.name || "/");
  const defaultBody = getInitialBody(endpoint);
  const headers = buildDefaultHeaders(endpoint);

  const pathParams: Record<string, string> = {};
  endpoint.pathParams?.forEach((p) => {
    const k = p.key || p.name;
    if (k) pathParams[k] = p.defaultValue || p.value || "1";
  });

  const queryParams: Record<string, string> = {};
  endpoint.queryParams?.forEach((p) => {
    const k = p.key || p.name;
    if (k) queryParams[k] = p.defaultValue || p.value || "";
  });

  const baseParams = { ...pathParams, ...queryParams };

  switch (preset) {
    case "200_ok":
      return {
        id: generateId(),
        name: customName || `200 OK - Standard Success`,
        targetNodeId: nodeId,
        targetEventId: endpoint.id,
        isAutoGenerated: false,
        category: "manual",
        request: { headers, params: baseParams, body: defaultBody },
        expectedStatus: 200,
        expectedBody: { success: true },
        mocks: {},
      };
    case "201_created":
      return {
        id: generateId(),
        name: customName || `201 Created - Resource Created`,
        targetNodeId: nodeId,
        targetEventId: endpoint.id,
        isAutoGenerated: false,
        category: "manual",
        request: { headers, params: baseParams, body: defaultBody },
        expectedStatus: 201,
        expectedBody: { success: true },
        mocks: {},
      };
    case "400_bad_request":
      return {
        id: generateId(),
        name: customName || `400 Bad Request - Invalid Payload`,
        targetNodeId: nodeId,
        targetEventId: endpoint.id,
        isAutoGenerated: false,
        category: "manual",
        request: { headers, params: {}, body: {} },
        expectedStatus: 400,
        expectedBody: { error: "Bad Request" },
        mocks: {},
      };
    case "401_unauthorized":
      const noAuthHeaders = { ...headers };
      delete noAuthHeaders["authorization"];
      return {
        id: generateId(),
        name: customName || `401 Unauthorized - Missing Token`,
        targetNodeId: nodeId,
        targetEventId: endpoint.id,
        isAutoGenerated: false,
        category: "manual",
        request: { headers: noAuthHeaders, params: baseParams, body: defaultBody },
        expectedStatus: 401,
        expectedBody: { error: "Unauthorized" },
        mocks: {},
      };
    case "404_not_found":
      return {
        id: generateId(),
        name: customName || `404 Not Found - Non-Existent ID`,
        targetNodeId: nodeId,
        targetEventId: endpoint.id,
        isAutoGenerated: false,
        category: "manual",
        request: { headers, params: { ...baseParams, id: "999999" }, body: defaultBody },
        expectedStatus: 404,
        expectedBody: { error: "Not Found" },
        mocks: {},
      };
    case "custom":
    default:
      return {
        id: generateId(),
        name: customName || `Test Case for ${method} ${path}`,
        targetNodeId: nodeId,
        targetEventId: endpoint.id,
        isAutoGenerated: false,
        category: "manual",
        request: { headers, params: baseParams, body: defaultBody },
        expectedStatus: method === "POST" ? 201 : 200,
        expectedBody: undefined,
        mocks: {},
      };
  }
}
