import React from "react";
import { ChevronLeft, Zap } from "lucide-react";
import { FunctionEditorHeaderProps } from "./types";

export const FunctionEditorHeader: React.FC<FunctionEditorHeaderProps> = React.memo(({
  name,
  kind,
  isNew = false,
  isAutoGenerated = false,
  inferredReturnType,
  onBack,
}) => {
  const displayKind = kind === "fetchByIndex" ? "INDEX" : kind;
  const displayName = name || (isNew ? "New Function" : "Unnamed Function");

  return (
    <div className="flex flex-col gap-4">
      {/* Back navigation */}
      <button
        type="button"
        onClick={onBack}
        className="flex items-center text-sm text-muted-foreground hover:text-foreground cursor-pointer transition-colors w-fit border-0 bg-transparent p-0"
      >
        <ChevronLeft size={16} className="mr-0.5" />
        Back to Operations List
      </button>

      {/* Operation Header */}
      <div className="flex flex-col gap-2 border-b border-border/50 pb-5">
        <div className="flex items-center gap-2.5 flex-wrap">
          <span className="text-[10px] font-mono font-bold px-2 py-0.5 bg-secondary text-secondary-foreground rounded border border-border/40 uppercase">
            {displayKind}
          </span>
          <span className="text-lg font-semibold tracking-tight text-foreground font-mono">
            {displayName}
          </span>
          {isAutoGenerated && (
            <span className="text-[10px] text-muted-foreground border border-border/40 px-1.5 py-0.5 rounded flex items-center gap-1">
              <Zap size={10} className="text-muted-foreground" /> Auto
            </span>
          )}
        </div>
        <div className="flex items-center gap-2 flex-wrap text-xs">
          <span className="text-muted-foreground font-medium">Return Type:</span>
          <code className="px-2 py-0.5 rounded text-[11px] font-mono font-semibold bg-secondary/80 text-foreground border border-border/40">
            {inferredReturnType}
          </code>
          <span className="text-[10px] text-muted-foreground/70 italic">(Inferred from code)</span>
        </div>
        <span className="text-xs text-muted-foreground">
          Define function signature, input parameters, pagination, and implementation logic.
        </span>
      </div>
    </div>
  );
});

FunctionEditorHeader.displayName = "FunctionEditorHeader";
