import React from "react";
import { DbOperationFunction, CanvasEntityColumn } from "@workspace/canvas/types";
import { BackendNode } from "@/types/canvas";
import { TableSchemaInfo } from "../../../shared/BusinessLogicBlock";
import { ConnectedDatabaseInfo } from "../ConnectedDatabasesSection";

export type OperationKind = DbOperationFunction["kind"];

export interface FunctionDetailEditorProps {
  selectedOp: DbOperationFunction;
  isNew?: boolean;
  onCancelNew?: () => void;
  onSaveNew?: () => void;
  label: string;
  columns?: CanvasEntityColumn[];
  indexes?: Array<{ name: string; columns: string; isUnique?: boolean }>;
  dbType?: string;
  pascalLabel: string;
  availableTableNodes: { id: string; label: string }[];
  allTableSchemas?: TableSchemaInfo[];
  parentDb?: BackendNode;
  allNodes?: BackendNode[];
  onBack: () => void;
  updateSelectedOp: (changes: Partial<DbOperationFunction>) => void;
  handleTogglePagination?: (enabled: boolean) => void;
  handleChangePaginationMode?: (mode: "offset" | "cursor") => void;
  onDeleteRequest: (op: { id: string; name: string }) => void;
}

export interface FunctionEditorHeaderProps {
  name?: string;
  kind: OperationKind;
  isNew?: boolean;
  isAutoGenerated?: boolean;
  inferredReturnType: string;
  onBack: () => void;
}

export interface FunctionMetaSectionProps {
  name?: string;
  kind: OperationKind;
  description?: string;
  isNew: boolean;
  isRedis: boolean;
  pascalLabel: string;
  nameInputRef: React.RefObject<HTMLInputElement | null>;
  onNameChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  onNameBlur: () => void;
  onNameKeyDown: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  onKindChange: (kind: OperationKind) => void;
  onDescriptionChange: (description: string) => void;
}

export interface FunctionEditorFooterProps {
  onDelete: () => void;
  onDone: () => void;
}

export interface UseFunctionEditorStateReturn {
  draftOp: DbOperationFunction;
  isRedis: boolean;
  effectiveDbType: string;
  currentInferredReturnType: string;
  functionInputSchema: Array<{ name: string; type: string; required?: boolean }>;
  nameInputRef: React.RefObject<HTMLInputElement | null>;
  handleNameChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleNameBlur: () => void;
  handleNameKeyDown: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  handleUpdateOp: (changes: Partial<DbOperationFunction>, immediate?: boolean) => void;
  handleTogglePagination: (enabled: boolean) => void;
  handleChangePaginationMode: (mode: "offset" | "cursor") => void;
  handlePromptChange: (prompt: string) => void;
  handleCodeChange: (code: string) => void;
  handleModeChange: (logicMode: "natural_language" | "code") => void;
  handleResetContext: () => void;
  handleGenerateCode: () => Promise<void>;
  connectedDatabases: ConnectedDatabaseInfo[];
  handleToggleDb: (dbId: string) => void;
  handleInsertSnippet: (snippet: string) => void;
  handleDelete: () => void;
  handleBack: () => void;
}
