import {
  ServiceNode,
  DatabaseTableRefNode,
  QueueNode,
  PubSubNode,
  EventStreamNode,
  KafkaNode,
  RedisStreamsNode,
  SQSNode,
  RedisPubSubNode,
  RedisCacheNode,
  StorageNode,
  ExternalNode,
  WebAppNode,
  WebClientNode,
  WorkerNode,
  ServerlessNode,
  SearchIndexNode,
  APIGatewayNode,
  LoadBalancerNode,
  WebhookNode,
  LLMNode,
  MCPServerNode,
  VectorDBRefNode,
  IdentityProviderNode,
  AuthNode,
  PaymentsNode,
  LangGraphNode,
  LangGraphStepNode,
} from "./graph-nodes";
import { SchemaGroupNode } from "./SchemaGroupNode";
import { WebAppGroupNode } from "./WebAppGroupNode";
import { EntityNode } from "./entity-node/EntityNode";
import { DatabaseNode } from "./database-node/DatabaseNode";

export const nodeTypes = {
  service: ServiceNode,
  database: DatabaseNode,
  db_ref: DatabaseTableRefNode,
  queue: QueueNode,
  pubsub: PubSubNode,
  eventstream: EventStreamNode,
  kafka: KafkaNode,
  "redis-streams": RedisStreamsNode,
  sqs: SQSNode,
  "redis-pubsub": RedisPubSubNode,
  "redis-cache": RedisCacheNode,
  storage: StorageNode,
  entity: EntityNode,
  external: ExternalNode,
  webApp: WebAppNode,
  webClient: WebClientNode,
  group: SchemaGroupNode,
  webAppGroup: WebAppGroupNode,
  // New nodes
  worker: WorkerNode,
  serverless: ServerlessNode,
  search_index: SearchIndexNode,
  api_gateway: APIGatewayNode,
  load_balancer: LoadBalancerNode,
  webhook: WebhookNode,
  llm: LLMNode,
  mcp_server: MCPServerNode,
  vector_db_ref: VectorDBRefNode,
  identity_provider: IdentityProviderNode,
  auth: AuthNode,
  payments: PaymentsNode,
  langgraph: LangGraphNode,
  langgraph_step: LangGraphStepNode,
};
