import { describe, it, expect } from "vitest";
import {
  isAutoGeneratedStepName,
  formatConditionSummary,
  formatSourceShort,
} from "../utils";

describe("Step Name Identification & Formatting Helpers", () => {
  describe("isAutoGeneratedStepName", () => {
    it("identifies default auto-generated variable names", () => {
      expect(isAutoGeneratedStepName("condition1Result")).toBe(true);
      expect(isAutoGeneratedStepName("condition2Result")).toBe(true);
      expect(isAutoGeneratedStepName("dbResult1")).toBe(true);
      expect(isAutoGeneratedStepName("transformedData3")).toBe(true);
      expect(isAutoGeneratedStepName("cachedResult1")).toBe(true);
      expect(isAutoGeneratedStepName("publishResult2")).toBe(true);
      expect(isAutoGeneratedStepName("serviceResponse1")).toBe(true);
      expect(isAutoGeneratedStepName("externalResult1")).toBe(true);
      expect(isAutoGeneratedStepName("tryCatch1Result")).toBe(true);
      expect(isAutoGeneratedStepName("switch1Result")).toBe(true);
      expect(isAutoGeneratedStepName("parallel1Results")).toBe(true);
      expect(isAutoGeneratedStepName("loop1Results")).toBe(true);
      expect(isAutoGeneratedStepName("earlyReturn1")).toBe(true);
      expect(isAutoGeneratedStepName("step1Result")).toBe(true);
      expect(isAutoGeneratedStepName("")).toBe(true);
      expect(isAutoGeneratedStepName(undefined)).toBe(true);
    });

    it("recognizes custom human-readable step titles", () => {
      expect(isAutoGeneratedStepName("Check User Active")).toBe(false);
      expect(isAutoGeneratedStepName("Create Conversation in DB")).toBe(false);
      expect(isAutoGeneratedStepName("Verify Auth Session")).toBe(false);
      expect(isAutoGeneratedStepName("if (user.isActive)")).toBe(false);
      expect(isAutoGeneratedStepName("Validate Token")).toBe(false);
      expect(isAutoGeneratedStepName("return 404")).toBe(false);
    });
  });

  describe("formatSourceShort", () => {
    it("formats request sources with prefixes and fields", () => {
      expect(formatSourceShort({ kind: "req_body", field: "userId" })).toBe("body.userId");
      expect(formatSourceShort({ kind: "req_params", field: "id" })).toBe("params.id");
      expect(formatSourceShort({ kind: "req_query", field: "filter" })).toBe("query.filter");
      expect(formatSourceShort({ kind: "req_headers", field: "authorization" })).toBe("headers.authorization");
      expect(formatSourceShort({ kind: "step_output", field: "data" })).toBe("step.data");
    });
  });

  describe("formatConditionSummary", () => {
    it("returns 'condition' when no expression or empty fields", () => {
      expect(formatConditionSummary(undefined)).toBe("condition");
      expect(formatConditionSummary({ left: { kind: "req_body", field: "" }, operator: "eq" })).toBe("condition");
    });

    it("formats equality and comparison clauses", () => {
      expect(
        formatConditionSummary({
          left: { kind: "req_body", field: "role" },
          operator: "eq",
          right: { kind: "literal", value: "admin" },
        }),
      ).toBe('body.role == "admin"');

      expect(
        formatConditionSummary({
          left: { kind: "req_body", field: "age" },
          operator: "gte",
          right: { kind: "literal", value: 18 },
        }),
      ).toBe("body.age >= 18");

      expect(
        formatConditionSummary({
          left: { kind: "req_params", field: "id" },
          operator: "neq",
          right: { kind: "literal", value: "" },
        }),
      ).toBe('params.id != ""');
    });

    it("formats unary truthy and null checks", () => {
      expect(
        formatConditionSummary({
          left: { kind: "req_body", field: "token" },
          operator: "truthy",
        }),
      ).toBe("body.token");

      expect(
        formatConditionSummary({
          left: { kind: "req_body", field: "error" },
          operator: "falsy",
        }),
      ).toBe("!body.error");

      expect(
        formatConditionSummary({
          left: { kind: "req_body", field: "session" },
          operator: "is_not_null",
        }),
      ).toBe("body.session != null");
    });
  });
});
