import React, { useState } from "react";
import { useBackendCanvasStore } from "@/lib/stores/backendCanvasStore";
import { DbOperationFunction } from "@workspace/canvas/types";
import { generateDefaultDbOperations } from "@/lib/utils/entityOperationsHelper";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@workspace/ui/components/alert-dialog";
import { FunctionDetailEditor } from "./FunctionDetailEditor";
import { EntityFunctionsList } from "./EntityFunctionsList";

export interface EntityFunctionsConfigProps {
  id?: string;
  nodeId: string;
}

export const EntityFunctionsConfig: React.FC<EntityFunctionsConfigProps> = ({
  nodeId,
}) => {
  const node = useBackendCanvasStore((s) =>
    s.nodes.find((n) => n.id === nodeId),
  );
  const updateNode = useBackendCanvasStore((s) => s.updateNode);
  const allNodes = useBackendCanvasStore((s) => s.nodes);

  // Selected operation ID for detail editing view
  const [selectedOpId, setSelectedOpId] = useState<string | null>(null);
  const [opToDelete, setOpToDelete] = useState<{ id: string; name: string } | null>(null);

  if (!node || (node.type !== "entity" && node.type !== "redis_schema")) {
    return (
      <div className="p-4 text-sm text-muted-foreground">
        Entity node not found.
      </div>
    );
  }

  const label = node.data.label || "Table";
  const columns = node.data.columns || [];
  const indexes = node.data.indexes || [];
  const pascalLabel = label.charAt(0).toUpperCase() + label.slice(1);

  const currentOps: DbOperationFunction[] =
    node.data.dbOperations && node.data.dbOperations.length > 0
      ? node.data.dbOperations
      : generateDefaultDbOperations(label, columns, indexes, allNodes);

  const selectedOp = currentOps.find((op) => op.id === selectedOpId);

  const saveOps = (updated: DbOperationFunction[]) => {
    updateNode(nodeId, {
      data: {
        ...node.data,
        dbOperations: updated,
      },
    });
  };

  const updateSelectedOp = (changes: Partial<DbOperationFunction>) => {
    if (!selectedOpId) return;
    const updated = currentOps.map((op) =>
      op.id === selectedOpId ? { ...op, ...changes } : op,
    );
    saveOps(updated);
  };

  const handleRegenerateDefaults = () => {
    const defaults = generateDefaultDbOperations(label, columns, indexes, allNodes);
    const customOps = currentOps.filter((op) => !op.isAutoGenerated);
    saveOps([...defaults, ...customOps]);
  };

  const handleToggle = (opId: string, enabled: boolean) => {
    const updated = currentOps.map((op) =>
      op.id === opId ? { ...op, enabled } : op,
    );
    saveOps(updated);
  };

  const handleDeleteOp = (opId: string) => {
    const updated = currentOps.filter((op) => op.id !== opId);
    saveOps(updated);
    if (selectedOpId === opId) setSelectedOpId(null);
  };

  const handleCreateNewFunction = () => {
    const newOp: DbOperationFunction = {
      id: `custom-op-${Date.now()}`,
      name: `custom${pascalLabel}Query`,
      kind: "custom",
      description: `Custom database query for ${label}`,
      returnTypeMode: "fixed",
      returnType: `${pascalLabel}Row[]`,
      params: [],
      pagination: {
        enabled: false,
        defaultLimit: 20,
        maxLimit: 100,
        mode: "offset",
      },
      logicMode: "natural_language",
      prompt: `Select records from ${label} table where status is active`,
      code: "",
      enabled: true,
      isAutoGenerated: false,
    };

    saveOps([...currentOps, newOp]);
    setSelectedOpId(newOp.id);
  };

  // Sync pagination parameters into function params when pagination toggling occurs
  const handleTogglePagination = (enabled: boolean) => {
    if (!selectedOp) return;
    const currentPagination = selectedOp.pagination || {
      defaultLimit: 20,
      maxLimit: 100,
      mode: "offset",
    };

    let params = selectedOp.params || [];

    if (enabled) {
      const mode = currentPagination.mode || "offset";
      const hasLimit = params.some((p) => p.name === "limit");
      const hasOffset = params.some((p) => p.name === "offset");
      const hasCursor = params.some((p) => p.name === "cursor");

      const newParams = [...params];
      if (!hasLimit) {
        newParams.push({
          name: "limit",
          type: "number",
          required: false,
          defaultValue: String(currentPagination.defaultLimit ?? 20),
        });
      }
      if (mode === "offset" && !hasOffset) {
        newParams.push({
          name: "offset",
          type: "number",
          required: false,
          defaultValue: "0",
        });
      } else if (mode === "cursor" && !hasCursor) {
        newParams.push({
          name: "cursor",
          type: "string",
          required: false,
        });
      }

      params = newParams;
    } else {
      params = params.filter(
        (p) => p.name !== "limit" && p.name !== "offset" && p.name !== "cursor",
      );
    }

    updateSelectedOp({
      pagination: { ...currentPagination, enabled },
      params,
    });
  };

  // Sync parameters when pagination mode changes (offset vs cursor)
  const handleChangePaginationMode = (mode: "offset" | "cursor") => {
    if (!selectedOp) return;
    let params = selectedOp.params || [];
    if (mode === "offset") {
      params = params.filter((p) => p.name !== "cursor");
      if (!params.some((p) => p.name === "offset")) {
        params.push({
          name: "offset",
          type: "number",
          required: false,
          defaultValue: "0",
        });
      }
    } else {
      params = params.filter((p) => p.name !== "offset");
      if (!params.some((p) => p.name === "cursor")) {
        params.push({
          name: "cursor",
          type: "string",
          required: false,
        });
      }
    }

    updateSelectedOp({
      pagination: {
        ...(selectedOp.pagination || {
          enabled: true,
          defaultLimit: 20,
          maxLimit: 100,
        }),
        mode,
      },
      params,
    });
  };

  // Available table nodes for BusinessLogicBlock context
  const availableTableNodes = allNodes
    .filter((n) => n?.type === "entity")
    .map((n) => ({
      id: n.id,
      label: n.data?.label || "Table",
    }));

  const autoOps = currentOps.filter((op) => op.isAutoGenerated);
  const customOps = currentOps.filter((op) => !op.isAutoGenerated);

  return (
    <>
      {selectedOp ? (
        <FunctionDetailEditor
          selectedOp={selectedOp}
          label={label}
          pascalLabel={pascalLabel}
          availableTableNodes={availableTableNodes}
          onBack={() => setSelectedOpId(null)}
          updateSelectedOp={updateSelectedOp}
          handleTogglePagination={handleTogglePagination}
          handleChangePaginationMode={handleChangePaginationMode}
          onDeleteRequest={(op) => setOpToDelete(op)}
        />
      ) : (
        <EntityFunctionsList
          label={label}
          autoOps={autoOps}
          customOps={customOps}
          onSelectOp={(id) => setSelectedOpId(id)}
          onToggle={handleToggle}
          onRegenerateDefaults={handleRegenerateDefaults}
          onCreateNewFunction={handleCreateNewFunction}
          onDeleteRequest={(op) => setOpToDelete(op)}
        />
      )}

      {/* Delete Function Confirmation Dialog */}
      <AlertDialog
        open={!!opToDelete}
        onOpenChange={(open) => !open && setOpToDelete(null)}
      >
        <AlertDialogContent
          onClick={(e) => e.stopPropagation()}
          className="bg-[#111216] border-zinc-800 text-zinc-100 max-w-md shadow-2xl ring-1 ring-white/10"
        >
          <AlertDialogHeader>
            <AlertDialogTitle className="text-zinc-100 font-semibold">
              Delete Function "{opToDelete?.name}"?
            </AlertDialogTitle>
            <AlertDialogDescription className="text-zinc-400 text-xs leading-relaxed">
              Are you sure you want to delete this database operation function? Any logic calling this function will need to be updated.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel
              onClick={() => setOpToDelete(null)}
              className="bg-zinc-800 hover:bg-zinc-700 text-zinc-300 border-zinc-700 hover:text-zinc-100"
            >
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (opToDelete) {
                  handleDeleteOp(opToDelete.id);
                  setOpToDelete(null);
                }
              }}
              className="bg-destructive hover:bg-destructive/90 text-destructive-foreground font-semibold"
            >
              Delete Function
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
};
