import React from "react";
import { ChevronLeft, Zap, Check, Trash } from "lucide-react";
import { DbOperationFunction } from "@workspace/canvas/types";
import { Input } from "@workspace/ui/components/input";
import { Button } from "@workspace/ui/components/button";
import { Label } from "@workspace/ui/components/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@workspace/ui/components/select";
import {
  BusinessLogicBlock,
  generateCodeWithAI,
} from "../../shared/BusinessLogicBlock";
import { FunctionParamsSection } from "./FunctionParamsSection";
import { FunctionReturnTypeSection } from "./FunctionReturnTypeSection";

interface FunctionDetailEditorProps {
  selectedOp: DbOperationFunction;
  label: string;
  pascalLabel: string;
  availableTableNodes: { id: string; label: string }[];
  onBack: () => void;
  updateSelectedOp: (changes: Partial<DbOperationFunction>) => void;
  handleTogglePagination: (enabled: boolean) => void;
  handleChangePaginationMode: (mode: "offset" | "cursor") => void;
  onDeleteRequest: (op: { id: string; name: string }) => void;
}

export const FunctionDetailEditor: React.FC<FunctionDetailEditorProps> = ({
  selectedOp,
  label,
  pascalLabel,
  availableTableNodes,
  onBack,
  updateSelectedOp,
  handleTogglePagination,
  handleChangePaginationMode,
  onDeleteRequest,
}) => {
  return (
    <div className="flex flex-col gap-6 mt-2 pb-12">
      {/* Back navigation */}
      <div
        onClick={onBack}
        className="flex items-center text-sm text-muted-foreground hover:text-foreground cursor-pointer transition-colors"
      >
        <ChevronLeft size={16} className="mr-0.5" />
        Back to Operations List
      </div>

      {/* Operation Header */}
      <div className="flex flex-col gap-2 border-b border-border/50 pb-5">
        <div className="flex items-center gap-2.5">
          <span className="text-[10px] font-mono font-bold px-2 py-0.5 bg-secondary text-secondary-foreground rounded border border-border/40 uppercase">
            {selectedOp.kind === "fetchByIndex" ? "INDEX" : selectedOp.kind}
          </span>
          <span className="text-lg font-semibold tracking-tight text-foreground font-mono">
            {selectedOp.name}
          </span>
          {selectedOp.isAutoGenerated && (
            <span className="text-[10px] text-muted-foreground border border-border/40 px-1.5 py-0.5 rounded flex items-center gap-1">
              <Zap size={10} className="text-muted-foreground" /> Auto
            </span>
          )}
        </div>
        <span className="text-xs text-muted-foreground">
          Define function signature, input parameters, pagination, implementation logic, and return type contract.
        </span>
      </div>

      {/* 1. Function Name & Kind */}
      <div className="grid grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label className="text-xs font-semibold">Function Name</Label>
          <Input
            value={selectedOp.name}
            onChange={(e) => updateSelectedOp({ name: e.target.value })}
            className="h-8 text-xs font-mono"
          />
        </div>

        <div className="flex flex-col gap-1.5">
          <Label className="text-xs font-semibold">Operation Kind</Label>
          <Select
            value={selectedOp.kind}
            onValueChange={(val: DbOperationFunction["kind"]) =>
              updateSelectedOp({ kind: val })
            }
          >
            <SelectTrigger className="h-8 text-xs">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="findAll">Read (findAll)</SelectItem>
              <SelectItem value="findById">Read (findById)</SelectItem>
              <SelectItem value="fetchByIndex">Index Fetch (fetchByIndex)</SelectItem>
              <SelectItem value="join">Relational Join (join)</SelectItem>
              <SelectItem value="create">Write (create)</SelectItem>
              <SelectItem value="update">Write (update)</SelectItem>
              <SelectItem value="delete">Write (delete)</SelectItem>
              <SelectItem value="custom">Custom Query</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Description */}
      <div className="flex flex-col gap-1.5">
        <Label className="text-xs font-semibold">Description</Label>
        <Input
          placeholder="Purpose of this database function..."
          value={selectedOp.description || ""}
          onChange={(e) => updateSelectedOp({ description: e.target.value })}
          className="h-8 text-xs"
        />
      </div>

      {/* 2. Unified Function Input Parameters & Pagination Card */}
      <FunctionParamsSection
        selectedOp={selectedOp}
        updateSelectedOp={updateSelectedOp}
        handleTogglePagination={handleTogglePagination}
        handleChangePaginationMode={handleChangePaginationMode}
      />

      {/* 3. Business Logic Block */}
      <BusinessLogicBlock
        title="Function Body & Business Logic"
        description="Define the function implementation in natural language or write query code. Use AI to generate code from instructions."
        mode={selectedOp.logicMode || "natural_language"}
        onModeChange={(logicMode) => updateSelectedOp({ logicMode })}
        prompt={selectedOp.prompt || selectedOp.query || ""}
        onPromptChange={(prompt) => updateSelectedOp({ prompt, query: prompt })}
        code={selectedOp.code || ""}
        onCodeChange={(code) => updateSelectedOp({ code })}
        availableTableNodes={availableTableNodes}
        promptPlaceholder={`Describe query function logic for ${selectedOp.name}... e.g. Query ${label} table with parameters and pagination limit/offset`}
        codePlaceholder="/* Function implementation code or raw SQL query */"
        onGenerateCode={async () => {
          const promptText =
            selectedOp.prompt ||
            selectedOp.query ||
            `Query function for ${selectedOp.name}`;
          const generated = await generateCodeWithAI({
            prompt: promptText,
            endpointPath: `db.${label}.${selectedOp.name}`,
            endpointMethod: selectedOp.kind.toUpperCase(),
            availableTableNodes,
          });
          if (generated) {
            updateSelectedOp({ code: generated, logicMode: "code" });
          }
        }}
      />

      {/* 4. Function Return Type */}
      <FunctionReturnTypeSection
        selectedOp={selectedOp}
        pascalLabel={pascalLabel}
        updateSelectedOp={updateSelectedOp}
      />

      {/* Actions Footer */}
      <div className="flex items-center justify-between pt-4 border-t border-border/40">
        <Button
          variant="destructive"
          size="sm"
          className="h-8 gap-1 text-xs cursor-pointer"
          onClick={() =>
            onDeleteRequest({
              id: selectedOp.id,
              name: selectedOp.name || "Function",
            })
          }
        >
          <Trash size={13} /> Delete Function
        </Button>

        <Button
          variant="default"
          size="sm"
          className="h-8 gap-1 text-xs cursor-pointer"
          onClick={onBack}
        >
          <Check size={13} /> Done
        </Button>
      </div>
    </div>
  );
};
