import React from "react";
import { BusinessLogicBlock } from "../../shared/BusinessLogicBlock";
import { FunctionParamsSection } from "./FunctionParamsSection";
import { ConnectedDatabasesSection } from "./ConnectedDatabasesSection";
import { OperationTestStudio } from "./OperationTestStudio";
import {
  FunctionDetailEditorProps,
  useFunctionEditorState,
  FunctionEditorHeader,
  FunctionMetaSection,
  FunctionEditorFooter,
} from "./function-editor";

export type { FunctionDetailEditorProps } from "./function-editor";

export const FunctionDetailEditor: React.FC<FunctionDetailEditorProps> = (props) => {
  const {
    draftOp,
    isRedis,
    effectiveDbType,
    currentInferredReturnType,
    functionInputSchema,
    nameInputRef,
    handleNameChange,
    handleNameBlur,
    handleNameKeyDown,
    handleUpdateOp,
    handleTogglePagination,
    handleChangePaginationMode,
    handlePromptChange,
    handleCodeChange,
    handleModeChange,
    handleResetContext,
    handleGenerateCode,
    connectedDatabases,
    handleToggleDb,
    handleInsertSnippet,
    handleDelete,
    handleBack,
  } = useFunctionEditorState(props);

  return (
    <div className="flex flex-col gap-6 mt-2 pb-12">
      {/* Header & Back navigation */}
      <FunctionEditorHeader
        name={draftOp.name}
        kind={draftOp.kind}
        isNew={props.isNew}
        isAutoGenerated={draftOp.isAutoGenerated}
        inferredReturnType={currentInferredReturnType}
        onBack={handleBack}
      />

      {/* 1. Function Name, Kind & Description */}
      <FunctionMetaSection
        name={draftOp.name}
        kind={draftOp.kind}
        description={draftOp.description}
        isNew={props.isNew ?? false}
        isRedis={isRedis}
        pascalLabel={props.pascalLabel}
        nameInputRef={nameInputRef}
        onNameChange={handleNameChange}
        onNameBlur={handleNameBlur}
        onNameKeyDown={handleNameKeyDown}
        onKindChange={(kind) => handleUpdateOp({ kind }, true)}
        onDescriptionChange={(description) => handleUpdateOp({ description })}
      />

      {/* 2. Unified Function Input Parameters & Pagination Card */}
      <FunctionParamsSection
        selectedOp={draftOp}
        updateSelectedOp={handleUpdateOp}
        handleTogglePagination={handleTogglePagination}
        handleChangePaginationMode={handleChangePaginationMode}
      />

      {/* 3. Database & Tables (hidden for Redis operations) */}
      {!isRedis && (
        <ConnectedDatabasesSection
          allNodes={props.allNodes || []}
          parentDb={props.parentDb}
          currentTableName={props.label}
          selectedDbIds={draftOp.connectedDbIds}
          connectedTableNames={draftOp.connectedTableNames}
          onToggleDb={handleToggleDb}
          onUpdateConnectedTables={(tableNames) =>
            handleUpdateOp({ connectedTableNames: tableNames }, true)
          }
          onInsertSnippet={handleInsertSnippet}
        />
      )}

      {/* 4. Business Logic Block */}
      <BusinessLogicBlock
        title="4. Function Implementation Logic"
        description="Define the function implementation in natural language or write query code. Use AI to generate code from instructions."
        mode={draftOp.logicMode || "natural_language"}
        onModeChange={handleModeChange}
        prompt={draftOp.prompt || draftOp.query || ""}
        onPromptChange={handlePromptChange}
        code={draftOp.code || ""}
        onCodeChange={handleCodeChange}
        onResetContext={handleResetContext}
        contextType="db_operation"
        dbType={effectiveDbType}
        tableName={props.label}
        tableSchema={{
          name: props.label,
          columns: props.columns || [],
          indexes: props.indexes || [],
        }}
        allTableSchemas={props.allTableSchemas}
        operationKind={draftOp.kind}
        operationParams={draftOp.params}
        operationReturnType={currentInferredReturnType}
        pagination={draftOp.pagination}
        availableTableNodes={props.availableTableNodes}
        promptPlaceholder={`Describe query function logic for ${draftOp.name}... e.g. Query ${props.label} table with parameters and pagination limit/offset`}
        codePlaceholder="/* Function implementation code or raw SQL query */"
        onGenerateCode={handleGenerateCode}
        functionName={draftOp.name || "unnamedOperation"}
        isAsync={true}
        inputSchema={functionInputSchema}
        outputTypeName={currentInferredReturnType}
        codeLanguageLabel="TypeScript Function"
        connectedDatabases={connectedDatabases}
      />

      {/* 5. Test Cases & Live Execution Studio */}
      <OperationTestStudio
        selectedOp={draftOp}
        label={props.label}
        columns={props.columns}
        parentDb={props.parentDb}
        updateSelectedOp={handleUpdateOp}
      />

      {/* Actions Footer */}
      <FunctionEditorFooter
        onDelete={handleDelete}
        onDone={handleBack}
      />
    </div>
  );
};

FunctionDetailEditor.displayName = "FunctionDetailEditor";
