// ═══════════════════════════════════════════════════════════════
// MODULE: CompileCustomOperationHelpers
// LAYER:  redis / generators / helpers
// EMITS:  Custom operations defined on Redis entity nodes
// ═══════════════════════════════════════════════════════════════

import { getEntityDbOperations } from "@/lib/utils/entityOperationsHelper";
import { HelperContext, HelperEmitResult } from "./types";

const STANDARD_OPERATION_NAMES = new Set([
  "get",
  "getAll",
  "set",
  "setFields",
  "getField",
  "setField",
  "invalidate",
  "delete",
  "invalidateAll",
  "push",
  "pop",
  "getList",
  "addMembers",
  "isMember",
  "getMembers",
  "addScore",
  "getRank",
  "getTop",
]);

export function compileCustomOperationHelpers(ctx: HelperContext): HelperEmitResult {
  const { schemaNode, allNodes, schema } = ctx;
  const { varName, typeName } = schema;
  const files: HelperEmitResult["files"] = [];
  const barrelExports: string[] = [];

  const standardNamesForType = new Set(
    Array.from(STANDARD_OPERATION_NAMES).map((name) => `${name}${typeName}`),
  );
  standardNamesForType.add(`getAll${typeName}Fields`);
  standardNamesForType.add(`set${typeName}Fields`);

  const customOps = getEntityDbOperations(schemaNode, allNodes).filter(
    (op) =>
      !op.isAutoGenerated &&
      !standardNamesForType.has(op.name) &&
      (!op.code ||
        (!op.code.includes("stmtUpdate") &&
          !op.code.includes("stmtInsert") &&
          !op.code.includes("stmtFindAll") &&
          !op.code.includes("stmtFindById") &&
          !op.code.includes("stmtDelete"))),
  );

  customOps.forEach((op) => {
    if (op.enabled !== false && op.code && op.code.trim()) {
      const customFnName = op.name || `custom${typeName}Op`;
      const customFnFile = `import { getRedisClient } from "../../client";
import { getCache, setCache, deleteCache } from "../../cache";
import {
  ${typeName},
  get${typeName}Key,
  ${typeName.toUpperCase()}_KEY_PATTERN,
  ${typeName.toUpperCase()}_TTL_SECONDS,
} from "../../schemas/${varName}";
import { createLogger } from "@workspace/logger";

const logger = createLogger("${customFnName}");

${op.code.trim()}
`;
      files.push({
        filename: `src/helpers/${varName}/${customFnName}.ts`,
        language: "typescript",
        content: customFnFile,
      });
      barrelExports.push(`export * from "./${customFnName}";`);
    }
  });

  return { files, barrelExports };
}
