import React, { useState } from "react";
import {
  FunctionSquare,
  Plus,
  Trash2,
  Zap,
  RotateCcw,
  Check,
  ChevronLeft,
  Settings2,
  X,
  Sparkles,
  Database,
} from "lucide-react";
import { useBackendCanvasStore } from "@/lib/stores/backendCanvasStore";
import { DbOperationFunction } from "@workspace/canvas/types";
import { generateDefaultDbOperations } from "@/lib/utils/entityOperationsHelper";
import { Input } from "@workspace/ui/components/input";
import { Button } from "@workspace/ui/components/button";
import { Switch } from "@workspace/ui/components/switch";
import { Label } from "@workspace/ui/components/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@workspace/ui/components/select";
import {
  BusinessLogicBlock,
  generateCodeWithAI,
} from "../shared/BusinessLogicBlock";
import { cn } from "@workspace/ui/lib/utils";

interface EntityFunctionsConfigProps {
  id: string;
  nodeId: string;
}

export const EntityFunctionsConfig: React.FC<EntityFunctionsConfigProps> = ({
  nodeId,
}) => {
  const node = useBackendCanvasStore((s) =>
    s.nodes.find((n) => n.id === nodeId),
  );
  const updateNode = useBackendCanvasStore((s) => s.updateNode);
  const allNodes = useBackendCanvasStore((s) => s.nodes);

  // Selected operation ID for detail editing view
  const [selectedOpId, setSelectedOpId] = useState<string | null>(null);

  if (!node || node.type !== "entity") {
    return (
      <div className="p-4 text-sm text-muted-foreground">
        Entity node not found.
      </div>
    );
  }

  const label = node.data.label || "Table";
  const columns = node.data.columns || [];
  const indexes = node.data.indexes || [];
  const pascalLabel = label.charAt(0).toUpperCase() + label.slice(1);

  const currentOps: DbOperationFunction[] =
    node.data.dbOperations && node.data.dbOperations.length > 0
      ? node.data.dbOperations
      : generateDefaultDbOperations(label, columns, indexes, allNodes);

  const selectedOp = currentOps.find((op) => op.id === selectedOpId);

  const saveOps = (updated: DbOperationFunction[]) => {
    updateNode(nodeId, {
      data: {
        ...node.data,
        dbOperations: updated,
      },
    });
  };

  const updateSelectedOp = (changes: Partial<DbOperationFunction>) => {
    if (!selectedOpId) return;
    const updated = currentOps.map((op) =>
      op.id === selectedOpId ? { ...op, ...changes } : op,
    );
    saveOps(updated);
  };

  const handleRegenerateDefaults = () => {
    const defaults = generateDefaultDbOperations(label, columns, indexes, allNodes);
    const customOps = currentOps.filter((op) => !op.isAutoGenerated);
    saveOps([...defaults, ...customOps]);
  };

  const handleToggle = (opId: string, enabled: boolean) => {
    const updated = currentOps.map((op) =>
      op.id === opId ? { ...op, enabled } : op,
    );
    saveOps(updated);
  };

  const handleDeleteOp = (opId: string) => {
    const updated = currentOps.filter((op) => op.id !== opId);
    saveOps(updated);
    if (selectedOpId === opId) setSelectedOpId(null);
  };

  const handleCreateNewFunction = () => {
    const newOp: DbOperationFunction = {
      id: `custom-op-${Date.now()}`,
      name: `custom${pascalLabel}Query`,
      kind: "custom",
      description: `Custom database query for ${label}`,
      returnTypeMode: "fixed",
      returnType: `${pascalLabel}Row[]`,
      params: [],
      pagination: {
        enabled: false,
        defaultLimit: 20,
        maxLimit: 100,
        mode: "offset",
      },
      logicMode: "natural_language",
      prompt: `Select records from ${label} table where status is active`,
      code: "",
      enabled: true,
      isAutoGenerated: false,
    };

    saveOps([...currentOps, newOp]);
    setSelectedOpId(newOp.id);
  };

  // Sync pagination parameters into function params when pagination toggling occurs
  const handleTogglePagination = (enabled: boolean) => {
    if (!selectedOp) return;
    const currentPagination = selectedOp.pagination || {
      defaultLimit: 20,
      maxLimit: 100,
      mode: "offset",
    };

    let params = selectedOp.params || [];

    if (enabled) {
      const mode = currentPagination.mode || "offset";
      const hasLimit = params.some((p) => p.name === "limit");
      const hasOffset = params.some((p) => p.name === "offset");
      const hasCursor = params.some((p) => p.name === "cursor");

      const newParams = [...params];
      if (!hasLimit) {
        newParams.push({ name: "limit", type: "number", required: false, defaultValue: String(currentPagination.defaultLimit ?? 20) });
      }
      if (mode === "offset" && !hasOffset) {
        newParams.push({ name: "offset", type: "number", required: false, defaultValue: "0" });
      } else if (mode === "cursor" && !hasCursor) {
        newParams.push({ name: "cursor", type: "string", required: false });
      }

      params = newParams;
    } else {
      params = params.filter((p) => p.name !== "limit" && p.name !== "offset" && p.name !== "cursor");
    }

    updateSelectedOp({
      pagination: { ...currentPagination, enabled },
      params,
    });
  };

  // Sync parameters when pagination mode changes (offset vs cursor)
  const handleChangePaginationMode = (mode: "offset" | "cursor") => {
    if (!selectedOp) return;
    let params = selectedOp.params || [];
    if (mode === "offset") {
      params = params.filter((p) => p.name !== "cursor");
      if (!params.some((p) => p.name === "offset")) {
        params.push({ name: "offset", type: "number", required: false, defaultValue: "0" });
      }
    } else {
      params = params.filter((p) => p.name !== "offset");
      if (!params.some((p) => p.name === "cursor")) {
        params.push({ name: "cursor", type: "string", required: false });
      }
    }

    updateSelectedOp({
      pagination: {
        ...(selectedOp.pagination || { enabled: true, defaultLimit: 20, maxLimit: 100 }),
        mode,
      },
      params,
    });
  };

  // Available table nodes for BusinessLogicBlock context
  const availableTableNodes = allNodes
    .filter((n) => n?.type === "entity")
    .map((n) => ({
      id: n.id,
      label: n.data?.label || "Table",
    }));

  // ---------------------------------------------------------------------------
  // DETAIL EDITOR VIEW FOR A SELECTED DB OPERATION (Unified Parameters Card & Return Mode)
  // ---------------------------------------------------------------------------
  if (selectedOp) {
    const isPaginated = selectedOp.pagination?.enabled ?? false;
    const returnTypeMode = selectedOp.returnTypeMode || "fixed";

    const presets = [
      `${pascalLabel}Row[]`,
      `${pascalLabel}Row | undefined`,
      `${pascalLabel}Row`,
      "void",
      "boolean",
      "number",
      "string",
    ];

    return (
      <div className="flex flex-col gap-6 mt-2 pb-12">
        {/* Back navigation */}
        <div
          onClick={() => setSelectedOpId(null)}
          className="flex items-center text-sm text-muted-foreground hover:text-foreground cursor-pointer transition-colors"
        >
          <ChevronLeft size={16} className="mr-0.5" />
          Back to Operations List
        </div>

        {/* Operation Header */}
        <div className="flex flex-col gap-2 border-b border-border/50 pb-5">
          <div className="flex items-center gap-2.5">
            <span className="text-[10px] font-mono font-bold px-2 py-0.5 bg-secondary text-secondary-foreground rounded border border-border/40 uppercase">
              {selectedOp.kind === "fetchByIndex" ? "INDEX" : selectedOp.kind}
            </span>
            <span className="text-lg font-semibold tracking-tight text-foreground font-mono">
              {selectedOp.name}
            </span>
            {selectedOp.isAutoGenerated && (
              <span className="text-[10px] text-muted-foreground border border-border/40 px-1.5 py-0.5 rounded flex items-center gap-1">
                <Zap size={10} className="text-muted-foreground" /> Auto
              </span>
            )}
          </div>
          <span className="text-xs text-muted-foreground">
            Define function signature, input parameters, pagination, implementation logic, and return type contract.
          </span>
        </div>

        {/* 1. Function Name & Kind */}
        <div className="grid grid-cols-2 gap-4">
          <div className="flex flex-col gap-1.5">
            <Label className="text-xs font-semibold">Function Name</Label>
            <Input
              value={selectedOp.name}
              onChange={(e) => updateSelectedOp({ name: e.target.value })}
              className="h-8 text-xs font-mono"
            />
          </div>

          <div className="flex flex-col gap-1.5">
            <Label className="text-xs font-semibold">Operation Kind</Label>
            <Select
              value={selectedOp.kind}
              onValueChange={(val: DbOperationFunction["kind"]) =>
                updateSelectedOp({ kind: val })
              }
            >
              <SelectTrigger className="h-8 text-xs">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="findAll">Read (findAll)</SelectItem>
                <SelectItem value="findById">Read (findById)</SelectItem>
                <SelectItem value="fetchByIndex font-mono">Index Fetch (fetchByIndex)</SelectItem>
                <SelectItem value="join font-mono">Relational Join (join)</SelectItem>
                <SelectItem value="create">Write (create)</SelectItem>
                <SelectItem value="update">Write (update)</SelectItem>
                <SelectItem value="delete">Write (delete)</SelectItem>
                <SelectItem value="custom">Custom Query</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* Description */}
        <div className="flex flex-col gap-1.5">
          <Label className="text-xs font-semibold">Description</Label>
          <Input
            placeholder="Purpose of this database function..."
            value={selectedOp.description || ""}
            onChange={(e) => updateSelectedOp({ description: e.target.value })}
            className="h-8 text-xs"
          />
        </div>

        {/* 2. Unified Function Input Parameters & Pagination Card */}
        <div className="flex flex-col gap-4 rounded-xl border border-border/60 bg-card/40 p-4 shadow-sm">
          {/* Card Header with Parameters Count, Pagination Switch, and Add Parameter button */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Function Input Parameters ({selectedOp.params?.length || 0})
              </span>
              <div className="flex items-center gap-1.5 border-l border-border/40 pl-3">
                <Switch
                  id="pagination-toggle"
                  checked={isPaginated}
                  onCheckedChange={handleTogglePagination}
                  className="scale-90"
                />
                <Label htmlFor="pagination-toggle" className="text-xs text-muted-foreground cursor-pointer select-none">
                  Pagination
                </Label>
              </div>
            </div>

            <Button
              variant="ghost"
              size="sm"
              className="h-6 text-[11px] gap-1"
              onClick={() => {
                const currentParams = selectedOp.params || [];
                updateSelectedOp({
                  params: [
                    ...currentParams,
                    { name: `param${currentParams.length + 1}`, type: "string", required: true },
                  ],
                });
              }}
            >
              <Plus size={12} /> Add Parameter
            </Button>
          </div>

          {/* Embedded Pagination Controls (when pagination is enabled) */}
          {isPaginated && (
            <div className="grid grid-cols-3 gap-3 p-2.5 rounded-lg bg-secondary/30 border border-border/30">
              <div className="flex flex-col gap-1">
                <Label className="text-[11px]">Default Limit</Label>
                <Input
                  type="number"
                  min={0}
                  value={selectedOp.pagination?.defaultLimit ?? 20}
                  onChange={(e) => {
                    const parsed = parseInt(e.target.value, 10);
                    updateSelectedOp({
                      pagination: {
                        ...selectedOp.pagination,
                        defaultLimit: isNaN(parsed) ? 0 : parsed,
                      },
                    });
                  }}
                  className="h-7 text-xs font-mono bg-background/60"
                />
              </div>

              <div className="flex flex-col gap-1">
                <Label className="text-[11px]">Max Limit</Label>
                <Input
                  type="number"
                  min={0}
                  value={selectedOp.pagination?.maxLimit ?? 100}
                  onChange={(e) => {
                    const parsed = parseInt(e.target.value, 10);
                    updateSelectedOp({
                      pagination: {
                        ...selectedOp.pagination,
                        maxLimit: isNaN(parsed) ? 0 : parsed,
                      },
                    });
                  }}
                  className="h-7 text-xs font-mono bg-background/60"
                />
              </div>

              <div className="flex flex-col gap-1">
                <Label className="text-[11px]">Pagination Mode</Label>
                <Select
                  value={selectedOp.pagination?.mode || "offset"}
                  onValueChange={handleChangePaginationMode}
                >
                  <SelectTrigger className="h-7 text-xs font-mono bg-background/60">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="offset">Offset / Limit</SelectItem>
                    <SelectItem value="cursor">Cursor Keys</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          )}

          {/* Parameter List */}
          {(!selectedOp.params || selectedOp.params.length === 0) ? (
            <div className="text-xs text-muted-foreground italic py-2">
              No input parameters defined for this function.
            </div>
          ) : (
            <div className="flex flex-col gap-2">
              {selectedOp.params.map((p, idx) => {
                const isPaginationParam =
                  isPaginated &&
                  (p.name === "limit" || p.name === "offset" || p.name === "cursor");

                return (
                  <div key={idx} className="flex items-center gap-2">
                    <Input
                      value={p.name}
                      placeholder="name"
                      onChange={(e) => {
                        const updated = [...(selectedOp.params || [])];
                        updated[idx] = { ...updated[idx]!, name: e.target.value };
                        updateSelectedOp({ params: updated });
                      }}
                      className="h-7 text-xs font-mono flex-1"
                    />
                    <Select
                      value={p.type}
                      onValueChange={(val) => {
                        const updated = [...(selectedOp.params || [])];
                        updated[idx] = { ...updated[idx]!, type: val };
                        updateSelectedOp({ params: updated });
                      }}
                    >
                      <SelectTrigger className="h-7 w-28 text-xs font-mono">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="string">string</SelectItem>
                        <SelectItem value="number">number</SelectItem>
                        <SelectItem value="boolean">boolean</SelectItem>
                        <SelectItem value="any">any</SelectItem>
                        <SelectItem value="object">object</SelectItem>
                      </SelectContent>
                    </Select>

                    {isPaginationParam ? (
                      <span className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-muted text-muted-foreground border border-border/30 shrink-0">
                        PAGE
                      </span>
                    ) : (
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-muted-foreground hover:text-destructive shrink-0"
                        onClick={() => {
                          const updated = selectedOp.params?.filter((_, i) => i !== idx);
                          updateSelectedOp({ params: updated });
                        }}
                      >
                        <X size={12} />
                      </Button>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* 3. Business Logic Block (Function Body / Implementation BEFORE Return Type) */}
        <BusinessLogicBlock
          title="Function Body & Business Logic"
          description="Define the function implementation in natural language or write query code. Use AI to generate code from instructions."
          mode={selectedOp.logicMode || "natural_language"}
          onModeChange={(logicMode) => updateSelectedOp({ logicMode })}
          prompt={selectedOp.prompt || selectedOp.query || ""}
          onPromptChange={(prompt) => updateSelectedOp({ prompt, query: prompt })}
          code={selectedOp.code || ""}
          onCodeChange={(code) => updateSelectedOp({ code })}
          availableTableNodes={availableTableNodes}
          promptPlaceholder={`Describe query function logic for ${selectedOp.name}... e.g. Query ${label} table with parameters and pagination limit/offset`}
          codePlaceholder="/* Function implementation code or raw SQL query */"
          onGenerateCode={async () => {
            const promptText = selectedOp.prompt || selectedOp.query || `Query function for ${selectedOp.name}`;
            const generated = await generateCodeWithAI({
              prompt: promptText,
              endpointPath: `db.${label}.${selectedOp.name}`,
              endpointMethod: selectedOp.kind.toUpperCase(),
              availableTableNodes,
            });
            if (generated) {
              updateSelectedOp({ code: generated, logicMode: "code" });
            }
          }}
        />

        {/* 4. Function Return Type (Matching EndpointConfig Response Contract style) */}
        <div className="flex flex-col gap-3.5 p-4 rounded-xl border border-border/60 bg-card/40 shadow-sm">
          <div className="flex items-center justify-between border-b border-border/40 pb-2.5">
            <div className="flex flex-col gap-0.5">
              <span className="text-xs font-bold text-foreground uppercase tracking-wider font-mono">
                Function Return Type Contract
              </span>
              <span className="text-[10px] text-muted-foreground">
                Specify fixed TypeScript return type or let AI infer dynamically from function logic.
              </span>
            </div>
          </div>

          {/* Return Type Mode Tabs */}
          <div className="flex items-center justify-between gap-1 bg-background/60 p-1 rounded-lg border border-border/50">
            <button
              type="button"
              onClick={() => updateSelectedOp({ returnTypeMode: "fixed" })}
              className={`flex-1 flex items-center justify-center gap-1.5 py-1 px-2 rounded-md text-[11px] font-medium transition-all ${
                returnTypeMode === "fixed"
                  ? "bg-secondary text-foreground shadow-sm font-semibold border border-border/50"
                  : "text-muted-foreground hover:text-foreground hover:bg-secondary/40"
              }`}
            >
              <Database className="w-3.5 h-3.5" />
              <span>Fixed Type</span>
            </button>

            <button
              type="button"
              onClick={() => updateSelectedOp({ returnTypeMode: "inferred" })}
              className={`flex-1 flex items-center justify-center gap-1.5 py-1 px-2 rounded-md text-[11px] font-medium transition-all ${
                returnTypeMode === "inferred"
                  ? "bg-secondary text-foreground shadow-sm font-semibold border border-border/50"
                  : "text-muted-foreground hover:text-foreground hover:bg-secondary/40"
              }`}
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>AI Inferred</span>
            </button>
          </div>

          {/* Mode 1: Fixed Type with Presets & Input */}
          {returnTypeMode === "fixed" && (
            <div className="flex flex-col gap-2.5 pt-1">
              <div className="flex items-center justify-between">
                <Label className="text-[11px] font-semibold text-muted-foreground">
                  TypeScript Return Type Signature
                </Label>
              </div>

              {/* Preset buttons */}
              <div className="flex flex-wrap gap-1.5">
                {presets.map((preset) => (
                  <button
                    key={preset}
                    type="button"
                    onClick={() => updateSelectedOp({ returnType: preset })}
                    className={cn(
                      "px-2 py-0.5 rounded text-[10px] font-mono transition-all border",
                      selectedOp.returnType === preset
                        ? "bg-primary/15 text-primary border-primary/40 font-bold"
                        : "bg-background/60 text-muted-foreground border-border/50 hover:bg-secondary hover:text-foreground",
                    )}
                  >
                    {preset}
                  </button>
                ))}
              </div>

              <Input
                placeholder="e.g. UserRow[] or Promise<UserRow | undefined>"
                value={selectedOp.returnType || ""}
                onChange={(e) => updateSelectedOp({ returnType: e.target.value })}
                className="h-8 text-xs font-mono bg-background"
              />
            </div>
          )}

          {/* Mode 2: AI Inferred */}
          {returnTypeMode === "inferred" && (
            <div className="flex flex-col gap-1.5 text-[11px] text-muted-foreground bg-secondary/20 p-3 rounded-lg border border-border/40">
              <div className="flex items-center gap-1.5 font-semibold text-foreground">
                <Sparkles className="w-3.5 h-3.5 text-primary" />
                <span>AI Dynamic Return Inference</span>
              </div>
              <span>
                The return type will be inferred dynamically by AI from the function logic, entity schema ({pascalLabel}), and query operations.
              </span>
            </div>
          )}
        </div>

        {/* Actions Footer */}
        <div className="flex items-center justify-between pt-4 border-t border-border/40">
          <Button
            variant="destructive"
            size="sm"
            className="h-8 gap-1 text-xs"
            onClick={() => handleDeleteOp(selectedOp.id)}
          >
            <Trash2 size={13} /> Delete Function
          </Button>

          <Button
            variant="default"
            size="sm"
            className="h-8 gap-1 text-xs"
            onClick={() => setSelectedOpId(null)}
          >
            <Check size={13} /> Done
          </Button>
        </div>
      </div>
    );
  }

  // ---------------------------------------------------------------------------
  // LIST VIEW: OVERVIEW OF ALL DB OPERATIONS (Neutral monochrome styling)
  // ---------------------------------------------------------------------------
  const autoOps = currentOps.filter((op) => op.isAutoGenerated);
  const customOps = currentOps.filter((op) => !op.isAutoGenerated);

  return (
    <div className="space-y-6 mt-2 pb-12">
      {/* Header */}
      <div className="border-b border-border/50 pb-4">
        <div className="flex items-center justify-between mb-1">
          <div className="flex items-center gap-2">
            <FunctionSquare className="h-5 w-5 text-muted-foreground" />
            <h2 className="text-lg font-bold">DB Operation Functions</h2>
          </div>
          <Button
            variant="outline"
            size="sm"
            className="h-8 gap-1.5 text-xs"
            onClick={handleRegenerateDefaults}
            title="Auto-create standard CRUD & fetchByIndex operations based on current schema"
          >
            <RotateCcw className="h-3.5 w-3.5" />
            Auto-Generate
          </Button>
        </div>
        <p className="text-xs text-muted-foreground">
          Manage database operation functions for table{" "}
          <span className="font-semibold text-foreground">{label}</span>. Click a function to configure signature, parameters, pagination, and AI logic.
        </p>
      </div>

      {/* Auto-Generated Operations Section */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-1.5">
            <Zap className="h-4 w-4 text-muted-foreground" />
            <h3 className="text-sm font-semibold">
              Standard CRUD & Index Operations ({autoOps.length})
            </h3>
          </div>
        </div>

        <div className="space-y-2">
          {autoOps.map((op) => {
            const isEnabled = op.enabled !== false;
            const isPaginated = op.pagination?.enabled;
            return (
              <div
                key={op.id}
                className={cn(
                  "p-3 rounded-lg border border-border/60 bg-card/40 flex items-start justify-between gap-3 transition-colors hover:border-border cursor-pointer group",
                  !isEnabled && "opacity-50 bg-muted/20",
                )}
                onClick={() => setSelectedOpId(op.id)}
              >
                <div className="space-y-1 min-w-0 flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono font-semibold text-sm group-hover:text-primary transition-colors">
                      {op.name}
                    </span>
                    <span className="px-1.5 py-0.5 rounded text-[10px] font-mono font-bold uppercase shrink-0 bg-secondary text-secondary-foreground border border-border/40">
                      {op.kind === "fetchByIndex" ? "INDEX" : op.kind}
                    </span>
                    {isPaginated && (
                      <span className="px-1.5 py-0.5 rounded text-[9px] font-mono bg-muted text-muted-foreground border border-border/30">
                        PAGE ({op.pagination?.mode || "offset"})
                      </span>
                    )}
                  </div>
                  {op.signature && (
                    <div className="text-[11px] font-mono text-muted-foreground truncate">
                      {op.signature}
                    </div>
                  )}
                  {op.description && (
                    <div className="text-xs text-muted-foreground/80 truncate">
                      {op.description}
                    </div>
                  )}
                </div>

                <div className="flex items-center gap-2 shrink-0 pt-0.5">
                  <Switch
                    checked={isEnabled}
                    onClick={(e) => e.stopPropagation()}
                    onCheckedChange={(checked) => handleToggle(op.id, checked)}
                  />
                  <div
                    className="p-1 rounded hover:bg-secondary text-muted-foreground hover:text-foreground"
                    title="Configure operation"
                  >
                    <Settings2 size={14} />
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Custom Database Operations Section */}
      <div className="space-y-3 pt-2 border-t border-border/40">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-1.5">
            <FunctionSquare className="h-4 w-4 text-muted-foreground" />
            <h3 className="text-sm font-semibold">
              Custom DB Functions ({customOps.length})
            </h3>
          </div>
          <Button
            variant="secondary"
            size="sm"
            className="h-7 text-xs gap-1"
            onClick={handleCreateNewFunction}
          >
            <Plus className="h-3.5 w-3.5" /> Add Function
          </Button>
        </div>

        {customOps.length === 0 && (
          <div className="text-xs text-muted-foreground italic py-4 text-center border border-dashed border-border/60 rounded-lg">
            No custom functions added yet. Click &quot;Add Function&quot; to define custom database queries.
          </div>
        )}

        <div className="space-y-2">
          {customOps.map((op) => {
            const isEnabled = op.enabled !== false;
            const isPaginated = op.pagination?.enabled;
            return (
              <div
                key={op.id}
                className={cn(
                  "p-3 rounded-lg border border-border/60 bg-card/40 flex items-start justify-between gap-3 transition-colors hover:border-border cursor-pointer group",
                  !isEnabled && "opacity-50 bg-muted/20",
                )}
                onClick={() => setSelectedOpId(op.id)}
              >
                <div className="space-y-1 min-w-0 flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono font-semibold text-sm group-hover:text-primary transition-colors">
                      {op.name}
                    </span>
                    <span className="px-1.5 py-0.5 rounded text-[10px] font-mono font-bold uppercase shrink-0 bg-secondary text-secondary-foreground border border-border/40">
                      {op.kind}
                    </span>
                    {isPaginated && (
                      <span className="px-1.5 py-0.5 rounded text-[9px] font-mono bg-muted text-muted-foreground border border-border/30">
                        PAGE ({op.pagination?.mode || "offset"})
                      </span>
                    )}
                  </div>
                  {op.returnType && (
                    <div className="text-[11px] font-mono text-muted-foreground">
                      Return: {op.returnType}
                    </div>
                  )}
                  {(op.prompt || op.query) && (
                    <div className="text-xs text-muted-foreground/80 truncate">
                      {op.prompt || op.query}
                    </div>
                  )}
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <Switch
                    checked={isEnabled}
                    onClick={(e) => e.stopPropagation()}
                    onCheckedChange={(checked) => handleToggle(op.id, checked)}
                  />
                  <div
                    className="p-1 rounded hover:bg-secondary text-muted-foreground hover:text-foreground"
                    title="Configure operation"
                  >
                    <Settings2 size={14} />
                  </div>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-7 w-7 text-muted-foreground hover:text-destructive"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDeleteOp(op.id);
                    }}
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
