import type {
  ServiceTechStack,
  ServiceTechVersion,
  WebClientTechStack,
  WebClientTechVersion,
  DatabaseEngine,
  DatabaseEngineVersion,
} from "../techStack";
import type { Endpoint, WorkerTask, SearchSource } from "../schemas";
import type { InterServiceProtocol } from "../constants";
import type { UIEventItem, Parameter, Schema } from "./simulation";
import type { MessagingNodeData } from "./messaging";
import type {
  GatewayRoute,
  AuthRule,
  AuthFramework,
  BetterAuthVersion,
  WebAppZone,
  ProtectionRule,
  OAuthProviderConfig,
  AuthHookConfig,
  PaymentsPlanConfig,
  AdditionalAuthTableConfig,
  AuthFunctionRef,
  EmailPasswordConfig,
  AccountLinkingPolicy,
  SessionConfig,
  RedirectsConfig,
  OrgInvitationsConfig,
  BetterAuthTableMapping,
} from "./auth";
import type {
  CanvasLangGraphNodeData,
  CanvasLangGraphStepNodeData,
  CanvasAINodeData,
} from "./langgraph";

export type BackendNodeType =
  | "service"
  | "database"
  | "queue"
  | "pubsub"
  | "eventstream"
  | "kafka"
  | "redis-streams"
  | "sqs"
  | "redis-pubsub"
  | "redis-cache"
  | "entity"
  | "webClient"
  | "external"
  | "group"
  | "db_ref"
  | "storage"
  // Redis Dedicated Schema View Nodes
  | "redis_instance"
  | "redis_schema"
  // New node types
  | "worker"
  | "serverless"
  | "search_index"
  | "api_gateway"
  | "load_balancer"
  | "webhook"
  | "llm"
  | "mcp_server"
  | "vector_db_ref"
  | "identity_provider"
  | "auth"
  | "webApp"
  | "webAppGroup"
  | "payments"
  | "langgraph"
  | "langgraph_step"
  | "page_ref"
  | "transformer"
  | "transformer_ref";

/** Core fields present on every canvas node. */
export interface BaseNodeData {
  label: string;
  description?: string;
  color?: string;
  isWebClient?: boolean;
  parentId?: string;
  /** Nested position inside a group node. */
  position?: { x: number; y: number };
  /** Position override used in the graph-view layout. */
  graphPosition?: { x: number; y: number };
  // Tech stack & DB engine selection (shared by Service and Database nodes)
  techStack?: ServiceTechStack | WebClientTechStack;
  techVersion?: ServiceTechVersion | WebClientTechVersion;
  dbEngine?: DatabaseEngine;
  dbEngineVersion?: DatabaseEngineVersion;
  // Client & connection properties
  targetServerId?: string;
  targetRouteId?: string;
  pageSlug?: string;
  path?: string;
  route?: string;
  // Shared visual / misc
  authentication?: string;
  tags?: string[];
  // Transformer node properties
  functionName?: string;
  scope?: "global" | "local";
  targetServiceId?: string;
  targetEndpointId?: string;
  targetEndpointIds?: string[];
  transformerRef?: string;
  inputSchema?: {
    id?: string;
    name: string;
    type: string;
    required?: boolean;
    description?: string;
  }[];
  inputSchemaMode?: "field_builder" | "raw_json";
  inputSchemaRawJson?: string;
  logicMode?: "natural_language" | "code";
  prompt?: string;
  code?: string;
  returnSchema?: {
    id?: string;
    name: string;
    type: string;
    required?: boolean;
    description?: string;
  }[];
  returnSchemaMode?: "field_builder" | "raw_json";
  returnSchemaRawJson?: string;
  isAsync?: boolean;
}


/** Database operation function (CRUD, index fetch, or custom query) */
export interface DbOperationFunction {
  id: string;
  name: string;
  kind: "findAll" | "findById" | "create" | "update" | "delete" | "fetchByIndex" | "join" | "custom";
  description?: string;
  signature?: string;
  indexName?: string;
  params?: { name: string; type: string; required?: boolean; defaultValue?: string }[];
  returnType?: string;
  returnTypeMode?: "fixed" | "inferred";
  query?: string;
  pagination?: {
    enabled?: boolean;
    defaultLimit?: number;
    maxLimit?: number;
    mode?: "offset" | "cursor";
  };
  logicMode?: "natural_language" | "code";
  prompt?: string;
  code?: string;
  enabled?: boolean;
  isAutoGenerated?: boolean;
}

export type RedisDataStructure =
  | "hash"
  | "string"
  | "json"
  | "set"
  | "list"
  | "zset"
  | "geo"
  | "stream"
  | "bitmap"
  | "bitfield"
  | "hyperloglog"
  | "bloom";

export type RedisDurationUnit = "s" | "m" | "h" | "d" | "never";

export interface RedisDuration {
  value: number;
  unit: RedisDurationUnit;
}

export interface RedisHashField {
  name: string;
  type: "string" | "number" | "boolean" | "json" | "datetime" | "binary";
  required?: boolean;
  defaultValue?: string;
  description?: string;
  ttl?: RedisDuration; // Redis 7.4+ per-field TTL (HEXPIRE)
}

export interface RedisGeoConfig {
  longitudeField: string;
  latitudeField: string;
  memberType: "string" | "number" | "uuid";
  distanceUnit?: "m" | "km" | "mi" | "ft";
}

export interface RedisBitfieldSubfield {
  name: string;
  type: "u" | "i";
  bits: number;
  offset: number;
  overflow?: "WRAP" | "SAT" | "FAIL";
  description?: string;
}

export interface RedisBitfieldConfig {
  fields: RedisBitfieldSubfield[];
}

export interface RedisStreamConsumerGroup {
  name: string;
  description?: string;
  startId?: string;
}

export interface RedisStreamConfig {
  fields: Array<{ name: string; type: string }>;
  maxLen?: number;
  approximateTrim?: boolean;
  consumerGroups?: RedisStreamConsumerGroup[];
}

export interface RedisListConfig {
  elementType: string;
  maxLength?: number;
  trimStrategy?: "LTRIM" | "NONE";
  orientation?: "FIFO" | "LIFO";
}

export interface RedisSetConfig {
  memberType: string;
  description?: string;
}

export interface RedisZSetConfig {
  memberType: string;
  scoreType: "number" | "timestamp" | "float";
  sortOrder?: "asc" | "desc";
}

export interface RedisBitmapConfig {
  bitDescriptions?: Array<{ offset: number; name: string; description?: string }>;
}

export interface RedisHyperLogLogConfig {
  memberType?: string;
  precision?: string;
}

/** Database entity / table schema fields (canvas type). */
export interface CanvasEntityNodeData {
  isSchemaGroup?: boolean;
  variant?: string;
  dbType?: "relational" | "document" | "vector" | "redis" | "key-value";
  /** Column definitions stored as part of the node. */
  columns?: {
    name: string;
    type: string;
    isPrimaryKey?: boolean;
    isForeignKey?: boolean;
    isNotNull?: boolean;
    isUnique?: boolean;
    references?: { table: string; column: string };
  }[];
  indexes?: {
    name: string;
    columns: string;
    isUnique?: boolean;
  }[];
  /** DB Operation functions (CRUD, index queries, custom queries). */
  dbOperations?: DbOperationFunction[];
  /** For vector DB entities. */
  embeddingModel?: string;
  dimensions?: number;
  metric?: "Cosine" | "Dot Product" | "Euclidean";
  /** For Redis schema entities. */
  redisDataStructure?: RedisDataStructure;
  keyTemplate?: string;
  clusterHashTagParam?: string;
  ttl?: RedisDuration;
  cacheStrategy?:
    | "Cache Aside"
    | "Read Through"
    | "Write Through"
    | "Write Behind"
    | "Refresh Ahead";
  negativeCaching?: {
    enabled: boolean;
    ttl?: RedisDuration;
  };
  staleWhileRevalidate?: {
    enabled: boolean;
    refreshInterval?: RedisDuration;
  };
  sourceOfTruth?: {
    tableNodeId?: string;
    tableName?: string;
  };
  invalidationRules?: string;
  serialization?: "JSON" | "String" | "Binary" | "MessagePack" | "ProtoBuf";
  compression?: "None" | "gzip" | "brotli" | "lz4";
  hashConfig?: {
    fields: RedisHashField[];
  };
  geoConfig?: RedisGeoConfig;
  bitfieldConfig?: RedisBitfieldConfig;
  streamConfig?: RedisStreamConfig;
  listConfig?: RedisListConfig;
  setConfig?: RedisSetConfig;
  zsetConfig?: RedisZSetConfig;
  bitmapConfig?: RedisBitmapConfig;
  hyperloglogConfig?: RedisHyperLogLogConfig;
  /** Reference to entity node ID (used by DB Ref nodes). */
  tableRef?: string;
  /** Reference to vector collection (used by Vector DB Ref nodes). */
  collectionRef?: string;
  /** Reference to Redis schema node (used by Redis Cache Ref nodes). */
  schemaRef?: string;
  /** Reference to DB node (used by Vector DB Ref nodes or Entity nodes). */
  dbRef?: string;
  /** Associated Database node ID to which this table hangs. */
  databaseId?: string;
  /** Seed data rows for the entity. */
  seedRows?: Record<string, string | number | boolean | null>[];
}

/** Database node fields — connection configurations, environment variables, engine. */
export interface CanvasDatabaseNodeData {
  dbEngine?: DatabaseEngine | string;
  dbType?: "relational" | "document" | "vector" | "redis" | "key-value" | "nosql";
  dbCategory?: "sql" | "nosql" | "vector" | "key-value";
  provider?: string;
  dbConnectionType?: "env_var" | "connection_string";
  connectionStringEnv?: string;
  dbFilePathEnv?: string;
  hostEnv?: string;
  portEnv?: string;
  host?: string;
  port?: string | number;
  databaseNameEnv?: string;
  usernameEnv?: string;
  passwordEnv?: string;
  apiKeyEnv?: string;
  isDefault?: boolean;
  // Redis instance-wide server configurations
  maxmemoryPolicy?:
    | "noeviction"
    | "allkeys-lru"
    | "volatile-lru"
    | "allkeys-lfu"
    | "volatile-lfu"
    | "volatile-ttl"
    | "allkeys-random"
    | "volatile-random";
  maxmemory?: string;
  persistenceMode?: "RDB" | "AOF" | "RDB+AOF" | "None";
  clustering?: boolean;
}


/** Service / web-client node fields — endpoints, routing, CORS, etc. (canvas type). */
export interface CanvasServiceNodeData {
  baseUrl?: string;
  cors?: boolean;
  corsOrigins?: string;
  rateLimit?: string;
  timeout?: string;
  port?: string | number;
  grpcPort?: string;
  interServiceProtocol?: InterServiceProtocol;
  endpoints?: Endpoint[];


  isRoot?: boolean;
  isAuthPage?: boolean;
  routeGroup?: string;
  routeGroups?: {
    id: string;
    name: string;
    basePath: string;
    endpoints: Endpoint[];
  }[];
  // Graph-view event/logic lists (for web clients and services)
  events?: UIEventItem[] | { id: string; name: string }[];
  inputs?: { id: string; name: string }[];
  logic?: { id: string; name: string }[];
  outputs?: { id: string; name: string }[];
  actions?: { id: string; name: string }[];
  publishedEvents?: {
    id: string;
    name: string;
    description?: string;
    schema?: string;
    version?: string;
    targetNodeId?: string;
  }[];
  consumedEvents?: {
    id: string;
    name: string;
    description?: string;
    schema?: string;
    retryPolicy?: string;
    version?: string;
    handlerLogic?: string;
    targetNodeId?: string;
  }[];
  /** Local data-transformation helper functions attached to this service */
  transformerHelpers?: TransformerHelperNodeData[];
}

/**
 * A small, pure data-transformation helper function.
 * 3-section model: Input | Logic | Return.
 * Scope: "local" means compiled into this service's src/helpers/.
 *        "global" means compiled into packages/transformers.
 */
export interface TransformerHelperNodeData {
  id: string;
  name: string;             // camelCase function name, e.g. slugifyProductInput
  description?: string;
  scope: "global" | "local";
  targetServiceId?: string; // For local scope, which service this belongs to
  targetEndpointId?: string; // Optional: specific endpoint within the service

  // Section 1: Input
  inputSchema: {
    name: string;
    type: string;
    required?: boolean;
    description?: string;
  }[];
  inputSchemaMode?: "field_builder" | "raw_json";
  inputSchemaRawJson?: string;

  // Section 2: Logic
  logicMode: "natural_language" | "code";
  prompt?: string;   // NL description of the transformation
  code?: string;     // TypeScript function body (just the return expression, no function wrapper)

  // Section 3: Return
  returnSchema: {
    name: string;
    type: string;
    required?: boolean;
    description?: string;
  }[];
  returnSchemaMode?: "field_builder" | "raw_json";
  returnSchemaRawJson?: string;

  isAsync?: boolean;
}

/** Standalone transformer node fields for canvas graph view. */
export interface CanvasTransformerNodeData {
  functionName?: string;
  scope?: "global" | "local";
  targetServiceId?: string;
  targetEndpointId?: string;
  targetEndpointIds?: string[];
  inputSchema?: {
    name: string;
    type: string;
    required?: boolean;
    description?: string;
  }[];
  inputSchemaMode?: "field_builder" | "raw_json";
  inputSchemaRawJson?: string;
  logicMode?: "natural_language" | "code";
  prompt?: string;
  code?: string;
  returnSchema?: {
    name: string;
    type: string;
    required?: boolean;
    description?: string;
  }[];
  returnSchemaMode?: "field_builder" | "raw_json";
  returnSchemaRawJson?: string;
  isAsync?: boolean;
  transformerHelpers?: TransformerHelperNodeData[];
}

/** Transformer reference node fields (canvas type). */
export interface CanvasTransformerRefNodeData {
  transformerRef?: string;
  targetServiceId?: string;
  targetEndpointId?: string;
  targetEndpointIds?: string[];
}


/** Background worker node fields (canvas type). */
export interface CanvasWorkerNodeData {
  tasks?: WorkerTask[];
  queueSources?: string[];
  concurrency?: number;
  retryPolicy?: string;
  maxRetries?: number;
}

/** Serverless function node fields (canvas type). */
export interface CanvasServerlessNodeData {
  triggerType?: "HTTP" | "Event" | "CRON" | "Queue";
  runtime?: string;
  memoryMb?: number;
  timeoutSec?: number;
}

/** Infrastructure node fields — API Gateway, Load Balancer, Search Index (canvas type). */
export interface CanvasInfrastructureNodeData {
  // API Gateway
  routes?: GatewayRoute[];
  authRules?: AuthRule[];
  authType?: string;
  // Load Balancer
  targetGroups?: { id: string; name: string }[];
  algorithm?: string;
  healthCheckPath?: string;
  // Search Index
  searchSources?: SearchSource[];
  analyzer?: string;
  shards?: number;
  replicas?: number;
  refreshInterval?: string;
  reindexStrategy?: string;
}

/** Identity Provider node fields (canvas type). */
export interface CanvasIdentityProviderNodeData {
  provider?: string;
  issuerUrl?: string;
  discoveryUrl?: string;
  jwksUrl?: string;
  audiences?: string[];
  supportedAlgorithms?: string[];
  customCapabilities?: {
    authentication?: boolean;
    userManagement?: boolean;
    identity?: boolean;
    authorization?: boolean;
  };
  customOutputs?: {
    user?: boolean;
    tokens?: boolean;
    claims?: boolean;
  };
}

/** Auth Framework node fields (canvas type). */
export interface CanvasAuthNodeData {
  framework?: AuthFramework;
  provider?: string;
  authMode?: "embedded" | "standalone" | "gateway";
  plugins?: string[];
  secretKey?: string;
  baseUrl?: string;
  version?: BetterAuthVersion | string;
  dbAdapter?: "sqlite-raw" | "custom";
  databaseId?: string;
  authFunctions?: AuthFunctionRef[];
  tableMappings?: BetterAuthTableMapping;
  userEntityId?: string;
  userSchemaId?: string;
  additionalUserTables?: AdditionalAuthTableConfig[];
  additionalTables?: AdditionalAuthTableConfig[];
  providers?: {
    emailPassword?: EmailPasswordConfig;
    socialEnabled?: boolean;
    oauthEnabled?: boolean;
    oauth?: OAuthProviderConfig[];
    magicLink?: boolean;
    passkey?: boolean;
    accountLinking?: AccountLinkingPolicy;
  };
  session?: SessionConfig;
  redirects?: RedirectsConfig;
  trustedOrigins?: string[];
  organization?: {
    enabled?: boolean;
    roles?: string[];
    teams?: boolean;
    multiOrg?: boolean;
    invitations?: boolean;
    invitationsConfig?: OrgInvitationsConfig;
    schemaId?: string;
    entityId?: string;
    additionalTables?: AdditionalAuthTableConfig[];
  };
  subscription?: {
    enabled?: boolean;
    schemaId?: string;
    entityId?: string;
  };
  hooks?: AuthHookConfig[];
  paymentsPlugin?: { provider: "creem"; apiKeyEnv: string; webhookSecretEnv: string };
}

/** WebApp node fields (canvas type). */
export interface CanvasWebAppNodeData {
  appSlug?: string;
  framework?: string;
  port?: string | number;
  routes?: Array<{
    id: string;
    name: string;
    path: string;
    accessType?: "public" | "private" | "role-gated" | "payment-gated" | "org-gated";
    allowedRoles?: string[];
    requiredPlans?: string[];
    allowedOrgRoles?: string[];
    redirectTo?: string;
    isAuthPage?: boolean;
    events?: UIEventItem[];
  }>;
  zones?: WebAppZone[];
  authMode?: "none" | "connected_auth_node" | "custom_jwt" | "better_auth";
  authNodeId?: string;
  defaultLoginRoute?: string;
  corsOrigins?: string;
}

/** Web Client node fields (canvas type). */
export interface CanvasWebClientNodeData {
  appName?: string;
  appSlug?: string;
  accessType?: "public" | "private" | "role-gated" | "payment-gated" | "org-gated";
  allowedRoles?: string[];
  requiredPlans?: string[];
  allowedOrgRoles?: string[];
  redirectTo?: string;
  isAuthPage?: boolean;
  authNodeId?: string;
  zoneId?: string;
  useZoneDefault?: boolean;
  protectionOverride?: ProtectionRule;
  events?: UIEventItem[];
  headers?: Parameter[];
  pathParams?: Parameter[];
  queryParams?: Parameter[];
  requestBody?: Schema;
  requestBodyMode?: "field_builder" | "raw_json";
  summary?: string;
  requireAuth?: boolean;
}

/** Payments node fields (canvas type). */
export interface CanvasPaymentsNodeData {
  provider?: "creem" | string;
  plans?: PaymentsPlanConfig[];
  eventMapping?: Record<string, "active" | "trialing" | "past_due" | "canceled" | "expired">;
  apiKeyEnv?: string;
  webhookSecretEnv?: string;
}

/** Page Reference node fields (canvas type). */
export interface CanvasPageRefNodeData {
  pageRefId?: string;
  targetPageId?: string;
  targetPageLabel?: string;
  targetPageSlug?: string;
}

/**
 * Composite data payload for every BackendNode.
 * All domain-specific fields are optional; only `BaseNodeData.label` is required.
 * Sub-type interfaces are prefixed with `Canvas` to avoid naming conflicts
 * with the Zod-inferred schema types in `@workspace/canvas/schemas`.
 */
export type BackendNodeData = BaseNodeData &
  Partial<
    CanvasDatabaseNodeData &
      CanvasEntityNodeData &
      CanvasServiceNodeData &
      CanvasWebAppNodeData &
      CanvasWebClientNodeData &
      MessagingNodeData &
      CanvasWorkerNodeData &
      CanvasServerlessNodeData &
      CanvasInfrastructureNodeData &
      CanvasAINodeData &
      CanvasIdentityProviderNodeData &
      CanvasAuthNodeData &
      CanvasPaymentsNodeData &
      CanvasLangGraphNodeData &
      CanvasLangGraphStepNodeData &
      CanvasPageRefNodeData &
      CanvasTransformerNodeData &
      CanvasTransformerRefNodeData
  >;

export type BackendNode = {
  id: string;
  nodeId?: string;
  type: BackendNodeType;
  position: { x: number; y: number };
  data: BackendNodeData;
  fractionalIndex: string; // For Z-order
  parentId?: string;
  style?: Record<string, string | number | boolean | null | undefined>;
  width?: number;
  height?: number;
  selected?: boolean;
};

// BackendNodeData is defined above (composite of all node domain sub-types).
// BackendNodeItem is kept for AI tool / store compatibility.
export interface BackendNodeItem {
  nodeId: string;
  type?: string;
  data?: BackendNodeData;
}

/**
 * Describes a reusable function exported by a shared package (db, kafka, redis, etc.)
 * so service nodes can auto-import and call them in generated route handlers.
 */
export interface ReusableFunction {
  /** Human-readable function name, e.g. "findAllUsers" */
  name: string;
  /** Full import path, e.g. "@workspace/db/helpers/users" */
  importPath: string;
  /** TypeScript signature for documentation, e.g. "findAllUsers(): User[]" */
  signature: string;
  /** The entity/table/topic this function targets, e.g. "users" */
  targetName: string;
  /** CRUD operation kind or category */
  kind: "findAll" | "findById" | "create" | "update" | "delete" | "publish" | "consume" | "custom";
}

/**
 * Represents a database operation target resolved for a generated route endpoint.
 */
export interface TargetDbOperation {
  fn: ReusableFunction;
  callExpr: string;
  operationKind: "read" | "create" | "update" | "delete";
  tableNodeId?: string;
}

