import { z } from "zod";
import { baseNodeDataSchema } from "./base";

export const dbOperationFunctionSchema = z.object({
  id: z.string(),
  name: z.string(),
  kind: z.enum([
    "findAll",
    "findById",
    "create",
    "update",
    "delete",
    "fetchByIndex",
    "join",
    "custom",
  ]),
  description: z.string().optional(),
  signature: z.string().optional(),
  indexName: z.string().optional(),
  params: z
    .array(
      z.object({
        name: z.string(),
        type: z.string(),
        required: z.boolean().optional(),
        defaultValue: z.string().optional(),
      }),
    )
    .optional(),
  returnType: z.string().optional(),
  returnTypeMode: z.enum(["fixed", "inferred"]).optional(),
  query: z.string().optional(),
  pagination: z
    .object({
      enabled: z.boolean().optional(),
      defaultLimit: z.number().optional(),
      maxLimit: z.number().optional(),
      mode: z.enum(["offset", "cursor"]).optional(),
    })
    .optional(),
  logicMode: z.enum(["natural_language", "code"]).optional(),
  prompt: z.string().optional(),
  code: z.string().optional(),
  enabled: z.boolean().optional(),
  isAutoGenerated: z.boolean().optional(),
});

export const redisDurationSchema = z.object({
  value: z.number(),
  unit: z.enum(["s", "m", "h", "d", "never"]),
});

export const redisHashFieldSchema = z.object({
  name: z.string(),
  type: z.enum(["string", "number", "boolean", "json", "datetime", "binary"]),
  required: z.boolean().optional(),
  defaultValue: z.string().optional(),
  description: z.string().optional(),
  ttl: redisDurationSchema.optional(),
});

export const entityDataSchema = baseNodeDataSchema
  .extend({
    description: z.string().optional(),
    dbType: z.enum(["relational", "vector", "redis", "key-value", "document"]).optional(),
    embeddingModel: z.string().optional(),
    dimensions: z.number().optional(),
    metric: z.enum(["Cosine", "Dot Product", "Euclidean"]).optional(),
    // Redis Schema Fields
    redisDataStructure: z
      .enum([
        "hash",
        "string",
        "json",
        "set",
        "list",
        "zset",
        "geo",
        "stream",
        "bitmap",
        "bitfield",
        "hyperloglog",
        "bloom",
      ])
      .optional(),
    keyTemplate: z.string().optional(),
    clusterHashTagParam: z.string().optional(),
    ttl: redisDurationSchema.optional(),
    cacheStrategy: z
      .enum([
        "Cache Aside",
        "Read Through",
        "Write Through",
        "Write Behind",
        "Refresh Ahead",
      ])
      .optional(),
    negativeCaching: z
      .object({
        enabled: z.boolean(),
        ttl: redisDurationSchema.optional(),
      })
      .optional(),
    staleWhileRevalidate: z
      .object({
        enabled: z.boolean(),
        refreshInterval: redisDurationSchema.optional(),
      })
      .optional(),
    sourceOfTruth: z
      .object({
        tableNodeId: z.string().optional(),
        tableName: z.string().optional(),
      })
      .optional(),
    invalidationRules: z.string().optional(),
    serialization: z
      .enum(["JSON", "String", "Binary", "MessagePack", "ProtoBuf"])
      .optional(),
    compression: z.enum(["None", "gzip", "brotli", "lz4"]).optional(),
    hashConfig: z
      .object({
        fields: z.array(redisHashFieldSchema),
      })
      .optional(),
    geoConfig: z
      .object({
        longitudeField: z.string(),
        latitudeField: z.string(),
        memberType: z.enum(["string", "number", "uuid"]),
        distanceUnit: z.enum(["m", "km", "mi", "ft"]).optional(),
      })
      .optional(),
    bitfieldConfig: z
      .object({
        fields: z.array(
          z.object({
            name: z.string(),
            type: z.enum(["u", "i"]),
            bits: z.number(),
            offset: z.number(),
            overflow: z.enum(["WRAP", "SAT", "FAIL"]).optional(),
            description: z.string().optional(),
          }),
        ),
      })
      .optional(),
    streamConfig: z
      .object({
        fields: z.array(
          z.object({
            name: z.string(),
            type: z.string(),
          }),
        ),
        maxLen: z.number().optional(),
        approximateTrim: z.boolean().optional(),
        consumerGroups: z
          .array(
            z.object({
              name: z.string(),
              description: z.string().optional(),
              startId: z.string().optional(),
            }),
          )
          .optional(),
      })
      .optional(),
    listConfig: z
      .object({
        elementType: z.string(),
        maxLength: z.number().optional(),
        trimStrategy: z.enum(["LTRIM", "NONE"]).optional(),
        orientation: z.enum(["FIFO", "LIFO"]).optional(),
      })
      .optional(),
    setConfig: z
      .object({
        memberType: z.string(),
        description: z.string().optional(),
      })
      .optional(),
    zsetConfig: z
      .object({
        memberType: z.string(),
        scoreType: z.enum(["number", "timestamp", "float"]),
        sortOrder: z.enum(["asc", "desc"]).optional(),
      })
      .optional(),
    bitmapConfig: z
      .object({
        bitDescriptions: z
          .array(
            z.object({
              offset: z.number(),
              name: z.string(),
              description: z.string().optional(),
            }),
          )
          .optional(),
      })
      .optional(),
    hyperloglogConfig: z
      .object({
        memberType: z.string().optional(),
        precision: z.string().optional(),
      })
      .optional(),
    columns: z.array(
      z.object({
        name: z.string(),
        type: z.string(),
        isPrimaryKey: z.boolean().optional(),
        isForeignKey: z.boolean().optional(),
        isNotNull: z.boolean().optional(),
        isUnique: z.boolean().optional(),
        references: z
          .object({
            table: z.string(),
            column: z.string(),
          })
          .optional(),
      }),
    ),
    indexes: z
      .array(
        z.object({
          name: z.string(),
          columns: z.string(),
          isUnique: z.boolean().optional(),
        }),
      )
      .optional(),
    dbOperations: z.array(dbOperationFunctionSchema).optional(),
    databaseId: z.string().optional(),
  })
  .strict();

export const entityColumnInputSchema = z.object({
  name: z.string(),
  type: z.string(),
  isPrimaryKey: z.boolean().optional(),
  isForeignKey: z.boolean().optional(),
  isNotNull: z.boolean().optional(),
  isUnique: z.boolean().optional(),
  references: z
    .object({
      table: z.string(),
      column: z.string(),
    })
    .optional()
    .describe(
      "If this is a foreign key, which table and column it references in this group",
    ),
});

export const entityDataInputSchema = baseNodeDataSchema.extend({
  description: z.string().optional(),
  dbType: z.enum(["relational", "vector", "redis", "key-value", "document"]).optional(),
  embeddingModel: z.string().optional(),
  dimensions: z.number().optional(),
  metric: z.enum(["Cosine", "Dot Product", "Euclidean"]).optional(),
  columns: z.array(entityColumnInputSchema),
});
