import { z } from "zod";
import { baseNodeDataSchema } from "./base";

export const dbOperationFunctionSchema = z.object({
  id: z.string(),
  name: z.string(),
  kind: z.enum([
    "findAll",
    "findById",
    "create",
    "update",
    "delete",
    "fetchByIndex",
    "join",
    "custom",
  ]),
  description: z.string().optional(),
  signature: z.string().optional(),
  indexName: z.string().optional(),
  params: z
    .array(
      z.object({
        name: z.string(),
        type: z.string(),
        required: z.boolean().optional(),
        defaultValue: z.string().optional(),
      }),
    )
    .optional(),
  returnType: z.string().optional(),
  returnTypeMode: z.enum(["fixed", "inferred"]).optional(),
  query: z.string().optional(),
  pagination: z
    .object({
      enabled: z.boolean().optional(),
      defaultLimit: z.number().optional(),
      maxLimit: z.number().optional(),
      mode: z.enum(["offset", "cursor"]).optional(),
    })
    .optional(),
  logicMode: z.enum(["natural_language", "code"]).optional(),
  prompt: z.string().optional(),
  code: z.string().optional(),
  enabled: z.boolean().optional(),
  isAutoGenerated: z.boolean().optional(),
});

export const entityDataSchema = baseNodeDataSchema
  .extend({
    description: z.string().optional(),
    dbType: z.enum(["relational", "vector"]).optional(),
    embeddingModel: z.string().optional(),
    dimensions: z.number().optional(),
    metric: z.enum(["Cosine", "Dot Product", "Euclidean"]).optional(),
    columns: z.array(
      z.object({
        name: z.string(),
        type: z.string(),
        isPrimaryKey: z.boolean().optional(),
        isForeignKey: z.boolean().optional(),
        isNotNull: z.boolean().optional(),
        isUnique: z.boolean().optional(),
        references: z
          .object({
            table: z.string(),
            column: z.string(),
          })
          .optional(),
      }),
    ),
    indexes: z
      .array(
        z.object({
          name: z.string(),
          columns: z.string(),
          isUnique: z.boolean().optional(),
        }),
      )
      .optional(),
    dbOperations: z.array(dbOperationFunctionSchema).optional(),
    databaseId: z.string().optional(),
  })
  .strict();

export const entityColumnInputSchema = z.object({
  name: z.string(),
  type: z.string(),
  isPrimaryKey: z.boolean().optional(),
  isForeignKey: z.boolean().optional(),
  isNotNull: z.boolean().optional(),
  isUnique: z.boolean().optional(),
  references: z
    .object({
      table: z.string(),
      column: z.string(),
    })
    .optional()
    .describe(
      "If this is a foreign key, which table and column it references in this group",
    ),
});

export const entityDataInputSchema = baseNodeDataSchema.extend({
  description: z.string().optional(),
  dbType: z.enum(["relational", "vector"]).optional(),
  embeddingModel: z.string().optional(),
  dimensions: z.number().optional(),
  metric: z.enum(["Cosine", "Dot Product", "Euclidean"]).optional(),
  columns: z.array(entityColumnInputSchema),
});
