import { DbOperationFunction } from "@workspace/canvas/types";
import { toTableName } from "@/lib/compiler/utils";
import type { BackendNode } from "@/types/canvas";
import { toPascal, toSingular } from "./naming";
import { generateRedisOperations } from "./redisGenerator";
import { generateDefaultDbOperationsForEngine } from "./engineOperationsGenerator";
import { deriveDbFunctionSignature } from "./signatureHelper";
import { inferDbOperationReturnType } from "../inferDbOperationReturnType";

/**
 * Helper function to retrieve the active list of DB operation functions for an entity node.
 * If entityNode has dbOperations configured on its data, returns that.
 * Otherwise generates default CRUD, index-based, relational JOIN, or Redis operations.
 *
 * Pass `engine` to get engine-specific default operations (e.g. "postgres" for async SQL).
 */
export function getEntityDbOperations(
  entityNode?: { type?: string; data?: BackendNode["data"] } | null,
  allNodes: BackendNode[] = [],
  engine = "sqlite",
): DbOperationFunction[] {
  if (!entityNode || !entityNode.data) return [];
  const label = entityNode.data.label || "table";
  const columns = entityNode.data.columns || [];
  const indexes = entityNode.data.indexes || [];

  const isRedis =
    entityNode.data.dbType === "redis" ||
    entityNode.type === "redis_schema" ||
    entityNode.type === "redis-cache";

  if (isRedis) {
    const tableName = toTableName(label || "cache");
    const pascal = toPascal(tableName);
    const pascalSingular = toSingular(pascal);

    if (entityNode.data.dbOperations && entityNode.data.dbOperations.length > 0) {
      const hasSqlStatements = entityNode.data.dbOperations.some(
        (op) =>
          op.code &&
          (op.code.includes("stmtUpdate") ||
            op.code.includes("stmtInsert") ||
            op.code.includes("stmtFindAll") ||
            op.code.includes("stmtFindById") ||
            op.code.includes("stmtDelete")),
      );

      // Check if existing auto-generated operations match the current structure & jsonRootType,
      // and do not contain stale generics (<T) or outdated return types
      const autoGeneratedOps = entityNode.data.dbOperations.filter((op) => op.isAutoGenerated || op.id?.startsWith("redis-"));
      const currentStructure = entityNode.data.redisDataStructure || "hash";
      const isJsonArray = currentStructure === "json" && entityNode.data.jsonRootType === "array";

      let autoOpsMismatch = false;
      if (autoGeneratedOps.length > 0) {
        if (currentStructure === "list") {
          autoOpsMismatch = !autoGeneratedOps.some((op) => op.id.startsWith("redis-rpush-") || op.id.startsWith("redis-lrange-"));
        } else if (isJsonArray) {
          autoOpsMismatch = !autoGeneratedOps.some((op) => op.id.startsWith("redis-json-arrappend-"));
        } else if (currentStructure === "hash") {
          autoOpsMismatch = !autoGeneratedOps.some((op) => op.id.startsWith("redis-hgetall-"));
        } else if (currentStructure === "zset") {
          autoOpsMismatch = !autoGeneratedOps.some((op) => op.id.startsWith("redis-zadd-"));
        } else if (currentStructure === "geo") {
          autoOpsMismatch = !autoGeneratedOps.some((op) => op.id.startsWith("redis-geoadd-"));
        } else if (currentStructure === "stream") {
          autoOpsMismatch = !autoGeneratedOps.some((op) => op.id.startsWith("redis-xadd-"));
        } else if (currentStructure === "json" || currentStructure === "string") {
          autoOpsMismatch = autoGeneratedOps.some((op) =>
            op.id.startsWith("redis-rpush-") ||
            op.id.startsWith("redis-json-arrappend-") ||
            op.id.startsWith("redis-hgetall-") ||
            op.id.startsWith("redis-zadd-") ||
            op.id.startsWith("redis-geoadd-") ||
            op.id.startsWith("redis-xadd-")
          );
        }

        // Detect any stale generic signatures or old non-Result return types in auto-generated operations
        const hasStaleGenericsOrSignatures = autoGeneratedOps.some(
          (op) =>
            op.signature?.includes("<T") ||
            op.code?.includes("<T") ||
            (op.returnType && op.returnType.includes("<T")) ||
            (isJsonArray &&
              (op.name === `get${pascalSingular}` ||
                op.name === `getRecent${pascalSingular}Items` ||
                op.name === `append${pascalSingular}Item` ||
                op.name === `pop${pascalSingular}Item` ||
                op.name === `get${pascalSingular}Length`) &&
              !op.returnType?.includes("Result")) ||
            (currentStructure === "json" &&
              op.name === `get${pascalSingular}` &&
              !op.returnType?.includes("Result")) ||
            (currentStructure === "hash" &&
              (op.name === `getAll${pascalSingular}Fields` ||
                op.name === `get${pascalSingular}Field` ||
                op.name === `set${pascalSingular}Fields`) &&
              !op.returnType?.includes("Result"))
        );
        if (hasStaleGenericsOrSignatures) {
          autoOpsMismatch = true;
        }
      }

      if (!hasSqlStatements && !autoOpsMismatch) {
        return entityNode.data.dbOperations;
      }
      // Cleanse SQL statements or outdated auto-generated ops: preserve only genuine non-SQL custom operations
      const customRedisOps = entityNode.data.dbOperations.filter(
        (op) =>
          !op.isAutoGenerated &&
          !op.id?.startsWith("redis-") &&
          op.code &&
          !op.code.includes("stmtUpdate") &&
          !op.code.includes("stmtInsert") &&
          !op.code.includes("stmtFindAll") &&
          !op.code.includes("stmtFindById") &&
          !op.code.includes("stmtDelete"),
      );
      const redisDefaults = generateRedisOperations(label, entityNode.data);
      const upgradedOps = [...redisDefaults, ...customRedisOps];
      entityNode.data.dbOperations = upgradedOps;
      return upgradedOps;
    }
    return generateRedisOperations(label, entityNode.data);
  }

  if (engine === "postgres") {
    if (entityNode.data.dbOperations && entityNode.data.dbOperations.length > 0) {
      const hasStalePgOrSqliteOps = entityNode.data.dbOperations.some(
        (op) =>
          op.isAutoGenerated &&
          op.code &&
          (op.code.includes("stmtInsert") ||
            op.code.includes("stmtFindAll") ||
            op.code.includes("stmtFindById") ||
            op.code.includes("stmtDelete") ||
            op.code.includes("as unknown as") ||
            op.code.includes("as any") ||
            op.code.includes(" as ") ||
            (op.kind === "create" && !op.code.includes("{"))),
      );
      if (hasStalePgOrSqliteOps) {
        const customOps = entityNode.data.dbOperations.filter(
          (op) =>
            !op.isAutoGenerated &&
            op.code &&
            !op.code.includes("stmtInsert") &&
            !op.code.includes("stmtFindAll") &&
            !op.code.includes("stmtFindById") &&
            !op.code.includes("stmtDelete"),
        );
        const pgDefaults = generateDefaultDbOperationsForEngine(
          label,
          columns,
          indexes,
          allNodes,
          "postgres",
        );
        const upgradedOps = [...pgDefaults, ...customOps];
        entityNode.data.dbOperations = upgradedOps;
        return upgradedOps;
      }
    }
  }

  if (engine === "sqlite") {
    if (entityNode.data.dbOperations && entityNode.data.dbOperations.length > 0) {
      const hasPgOps = entityNode.data.dbOperations.some(
        (op) => op.isAutoGenerated && op.code && op.code.includes("await query"),
      );
      if (hasPgOps) {
        const customOps = entityNode.data.dbOperations.filter(
          (op) => !op.isAutoGenerated && op.code && !op.code.includes("await query"),
        );
        const sqliteDefaults = generateDefaultDbOperationsForEngine(
          label,
          columns,
          indexes,
          allNodes,
          "sqlite",
        );
        const upgradedOps = [...sqliteDefaults, ...customOps];
        entityNode.data.dbOperations = upgradedOps;
        return upgradedOps;
      }
    }
  }

  const rawOps =
    entityNode.data.dbOperations && entityNode.data.dbOperations.length > 0
      ? [...entityNode.data.dbOperations]
      : generateDefaultDbOperationsForEngine(label, columns, indexes, allNodes, engine);

  // Synchronize auto-generated fetchByIndex operations with current indexes
  if (!isRedis && entityNode.data.dbOperations && entityNode.data.dbOperations.length > 0) {
    const currentDefaults = generateDefaultDbOperationsForEngine(label, columns, indexes, allNodes, engine);
    const defaultIndexOps = currentDefaults.filter((d) => d.kind === "fetchByIndex");
    const existingAutoIndexOps = rawOps.filter(
      (op) => op.isAutoGenerated && op.kind === "fetchByIndex",
    );

    const isIndexMismatch =
      existingAutoIndexOps.length !== defaultIndexOps.length ||
      existingAutoIndexOps.some((curr, idx) => {
        const expected = defaultIndexOps[idx];
        return (
          !expected ||
          curr.name !== expected.name ||
          curr.indexName !== expected.indexName ||
          curr.id !== expected.id
        );
      });

    if (isIndexMismatch) {
      const nonAutoIndexOps = rawOps.filter(
        (op) => !(op.isAutoGenerated && op.kind === "fetchByIndex"),
      );

      const syncedIndexOps = defaultIndexOps.map((defOp, idx) => {
        const matchingExisting =
          existingAutoIndexOps.find(
            (ex) =>
              ex.id === defOp.id ||
              ex.indexName === defOp.indexName ||
              ex.name === defOp.name,
          ) || existingAutoIndexOps[idx];
        return {
          ...defOp,
          enabled: matchingExisting ? matchingExisting.enabled !== false : defOp.enabled !== false,
        };
      });

      const updatedOps = [...nonAutoIndexOps, ...syncedIndexOps];
      entityNode.data.dbOperations = updatedOps;
      rawOps.length = 0;
      rawOps.push(...updatedOps);
    }
  }

  // Synchronize auto-generated standard CRUD operations with current columns
  if (!isRedis && entityNode.data.dbOperations && entityNode.data.dbOperations.length > 0) {
    const currentDefaults = generateDefaultDbOperationsForEngine(label, columns, indexes, allNodes, engine);
    let hasCrudUpdates = false;

    rawOps.forEach((op, opIdx) => {
      if (!op.isAutoGenerated) return;
      const isSingletonCrud =
        op.kind === "findAll" ||
        op.kind === "findById" ||
        op.kind === "create" ||
        op.kind === "update" ||
        op.kind === "upsert" ||
        op.kind === "delete";
      if (!isSingletonCrud) return;

      const matchingDefault = currentDefaults.find((d) => d.kind === op.kind);
      if (matchingDefault) {
        const isStale =
          op.signature !== matchingDefault.signature ||
          op.code !== matchingDefault.code ||
          op.name !== matchingDefault.name ||
          op.returnType !== matchingDefault.returnType ||
          JSON.stringify(op.params) !== JSON.stringify(matchingDefault.params);

        if (isStale) {
          rawOps[opIdx] = {
            ...matchingDefault,
            enabled: op.enabled !== false,
          };
          hasCrudUpdates = true;
        }
      }
    });

    if (hasCrudUpdates) {
      entityNode.data.dbOperations = [...rawOps];
    }
  }

  const tableName = toTableName(label || "table");
  const pascal = toPascal(tableName);
  const pascalSingular = toSingular(pascal);

  // If node already has dbOperations but lacks an upsert operation, inject default upsert
  const hasUpsert = rawOps.some(
    (op) => op.kind === "upsert" || op.name.toLowerCase() === `upsert${pascalSingular.toLowerCase()}`,
  );
  if (!hasUpsert && !isRedis) {
    const defaults = generateDefaultDbOperationsForEngine(label, columns, indexes, allNodes, engine);
    const defaultUpsert = defaults.find((d) => d.kind === "upsert");
    if (defaultUpsert) {
      const insertIdx = rawOps.findIndex((o) => o.kind === "update");
      if (insertIdx !== -1) {
        rawOps.splice(insertIdx + 1, 0, defaultUpsert);
      } else {
        rawOps.push(defaultUpsert);
      }
      if (entityNode.data.dbOperations) {
        entityNode.data.dbOperations = rawOps;
      }
    }
  }

  // Deduplicate operations by id and non-empty name
  const seenIds = new Set<string>();
  const seenNames = new Set<string>();
  const deduped: DbOperationFunction[] = [];

  rawOps.forEach((op) => {
    if (!op || !op.id) return;
    if (seenIds.has(op.id)) return;
    seenIds.add(op.id);
    if (op.name && seenNames.has(op.name)) return;
    if (op.name) seenNames.add(op.name);

    // Automatically synchronize returnType and signature with code for operations with executable code
    if (op.code && op.code.trim()) {
      const inferred = inferDbOperationReturnType(op.code, {
        pascalLabel: toPascal(label || "table"),
        tableName: label,
      });
      if (inferred) {
        op.returnType = inferred;
        op.signature = deriveDbFunctionSignature(op.name, op.params, inferred);
      }
    } else if (!op.signature && op.name) {
      op.signature = deriveDbFunctionSignature(op.name, op.params, op.returnType || "void");
    }

    deduped.push(op);
  });

  return deduped;
}
