import { DbOperationFunction, RedisDataStructure } from "@workspace/canvas/types";
import { toTableName } from "@/lib/compiler/utils";
import type { BackendNode } from "@/types/canvas";
import { toPascal, toSingular, toPlural } from "./naming";

/**
 * Generates default Redis helper operation functions based on the Redis data structure.
 */
export function generateRedisOperations(
  label: string,
  data?: BackendNode["data"],
): DbOperationFunction[] {
  const tableName = toTableName(label || "cache");
  const pascal = toPascal(tableName);
  const pascalSingular = toSingular(pascal);
  const pascalPlural = toPlural(pascal);
  const structure: RedisDataStructure = data?.redisDataStructure || "hash";

  if (structure === "hash") {
    return [
      {
        id: `redis-hgetall-${tableName}`,
        name: `getAll${pascalSingular}Fields`,
        kind: "findAll",
        description: `Retrieve all field-value pairs from Redis hash [${label}]`,
        signature: `getAll${pascalSingular}Fields(key: string): Promise<GetAll${pascalSingular}FieldsResult>`,
        params: [{ name: "key", type: "string", required: true }],
        returnType: `Promise<GetAll${pascalSingular}FieldsResult>`,
        logicMode: "code",
        code: `export async function getAll${pascalSingular}Fields(key: string): Promise<GetAll${pascalSingular}FieldsResult> {\n  try {\n    const redis = await getRedisClient();\n    const data = await redis.hgetall(key);\n    return { success: true, data: data || {} };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_HGETALL_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-hget-${tableName}`,
        name: `get${pascalSingular}Field`,
        kind: "findById",
        description: `Get a specific field from Redis hash [${label}]`,
        signature: `get${pascalSingular}Field(key: string, field: string): Promise<Get${pascalSingular}FieldResult>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "field", type: "string", required: true },
        ],
        returnType: `Promise<Get${pascalSingular}FieldResult>`,
        logicMode: "code",
        code: `export async function get${pascalSingular}Field(key: string, field: string): Promise<Get${pascalSingular}FieldResult> {\n  try {\n    const redis = await getRedisClient();\n    const data = await redis.hget(key, field);\n    return { success: true, data };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_HGET_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-hset-${tableName}`,
        name: `set${pascalSingular}Fields`,
        kind: "create",
        description: `Set fields in Redis hash [${label}]`,
        signature: `set${pascalSingular}Fields(key: string, fields: Record<string, string | number>): Promise<Set${pascalSingular}FieldsResult>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "fields", type: "Record<string, string | number>", required: true },
        ],
        returnType: `Promise<Set${pascalSingular}FieldsResult>`,
        logicMode: "code",
        code: `export async function set${pascalSingular}Fields(key: string, fields: Record<string, string | number>): Promise<Set${pascalSingular}FieldsResult> {\n  try {\n    const redis = await getRedisClient();\n    await redis.hset(key, fields);\n    return { success: true, data: undefined };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_HSET_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-hexpire-${tableName}`,
        name: `expire${pascalSingular}Field`,
        kind: "update",
        description: `Set field-level TTL in Redis 7.4+ hash [${label}] using HEXPIRE`,
        signature: `expire${pascalSingular}Field(key: string, field: string, ttlSeconds: number): Promise<number>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "field", type: "string", required: true },
          { name: "ttlSeconds", type: "number", required: true },
        ],
        returnType: "Promise<number>",
        logicMode: "code",
        code: `export async function expire${pascalSingular}Field(key: string, field: string, ttlSeconds: number): Promise<number> {\n  const redis = await getRedisClient();\n  return (await redis.call("HEXPIRE", key, ttlSeconds, "FIELDS", 1, field)) as number;\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-del-${tableName}`,
        name: `delete${pascalSingular}`,
        kind: "delete",
        description: `Delete Redis hash [${label}]`,
        signature: `delete${pascalSingular}(key: string): Promise<Delete${pascalSingular}Result>`,
        params: [{ name: "key", type: "string", required: true }],
        returnType: `Promise<Delete${pascalSingular}Result>`,
        logicMode: "code",
        code: `export async function delete${pascalSingular}(key: string): Promise<Delete${pascalSingular}Result> {\n  try {\n    const redis = await getRedisClient();\n    const res = await redis.del(key);\n    return { success: true, data: res > 0 };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_DEL_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
    ];
  }

  if (structure === "geo") {
    return [
      {
        id: `redis-geoadd-${tableName}`,
        name: `add${pascalSingular}Location`,
        kind: "create",
        description: `Add geospatial coordinate to [${label}] (GEOADD)`,
        signature: `add${pascalSingular}Location(key: string, longitude: number, latitude: number, member: string): Promise<number>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "longitude", type: "number", required: true },
          { name: "latitude", type: "number", required: true },
          { name: "member", type: "string", required: true },
        ],
        returnType: "Promise<number>",
        logicMode: "code",
        code: `export async function add${pascalSingular}Location(key: string, longitude: number, latitude: number, member: string): Promise<number> {\n  const redis = await getRedisClient();\n  return await redis.geoadd(key, longitude, latitude, member);\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-geosearch-${tableName}`,
        name: `searchNearby${pascalPlural}`,
        kind: "findAll",
        description: `Search coordinates within radius (GEOSEARCH)`,
        signature: `searchNearby${pascalPlural}(key: string, longitude: number, latitude: number, radius: number, unit: "km" | "m" | "mi" = "km"): Promise<string[]>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "longitude", type: "number", required: true },
          { name: "latitude", type: "number", required: true },
          { name: "radius", type: "number", required: true, defaultValue: "10" },
        ],
        returnType: "Promise<string[]>",
        logicMode: "code",
        code: `export async function searchNearby${pascalPlural}(key: string, longitude: number, latitude: number, radius: number = 10, unit: "km" | "m" | "mi" = "km"): Promise<string[]> {\n  const redis = await getRedisClient();\n  return (await redis.call("GEOSEARCH", key, "FROMLONLAT", longitude, latitude, "BYRADIUS", radius, unit)) as string[];\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
    ];
  }

  if (structure === "stream") {
    return [
      {
        id: `redis-xadd-${tableName}`,
        name: `add${pascalSingular}Entry`,
        kind: "create",
        description: `Append entry to Redis Stream [${label}] (XADD)`,
        signature: `add${pascalSingular}Entry(key: string, fields: Record<string, string>): Promise<string>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "fields", type: "Record<string, string>", required: true },
        ],
        returnType: "Promise<string>",
        logicMode: "code",
        code: `export async function add${pascalSingular}Entry(key: string, fields: Record<string, string>): Promise<string> {\n  const redis = await getRedisClient();\n  const args: string[] = [];\n  Object.entries(fields).forEach(([k, v]) => args.push(k, String(v)));\n  return String(await redis.xadd(key, "*", ...args));\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-xread-${tableName}`,
        name: `read${pascalSingular}Stream`,
        kind: "findAll",
        description: `Read entries from Redis Stream [${label}] (XREAD)`,
        signature: `read${pascalSingular}Stream(key: string, lastId: string = "0", count: number = 20): Promise<Array<[string, string[]]>>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "lastId", type: "string", required: false, defaultValue: '"0"' },
          { name: "count", type: "number", required: false, defaultValue: "20" },
        ],
        returnType: "Promise<Array<[string, string[]]>>",
        logicMode: "code",
        code: `export async function read${pascalSingular}Stream(key: string, lastId: string = "0", count: number = 20): Promise<Array<[string, string[]]>> {\n  const redis = await getRedisClient();\n  return (await redis.xread("COUNT", count, "STREAMS", key, lastId)) || [];\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
    ];
  }

  if (structure === "zset") {
    return [
      {
        id: `redis-zadd-${tableName}`,
        name: `add${pascalSingular}Member`,
        kind: "create",
        description: `Add member with numerical score to Sorted Set (ZADD)`,
        signature: `add${pascalSingular}Member(key: string, score: number, member: string): Promise<number>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "score", type: "number", required: true },
          { name: "member", type: "string", required: true },
        ],
        returnType: "Promise<number>",
        logicMode: "code",
        code: `export async function add${pascalSingular}Member(key: string, score: number, member: string): Promise<number> {\n  const redis = await getRedisClient();\n  return await redis.zadd(key, score, member);\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-zrange-${tableName}`,
        name: `getTop${pascalPlural}`,
        kind: "findAll",
        description: `Get top ranked members from Sorted Set (ZREVRANGE)`,
        signature: `getTop${pascalPlural}(key: string, count: number = 10): Promise<string[]>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "count", type: "number", required: false, defaultValue: "10" },
        ],
        returnType: "Promise<string[]>",
        logicMode: "code",
        code: `export async function getTop${pascalPlural}(key: string, count: number = 10): Promise<string[]> {\n  const redis = await getRedisClient();\n  return (await redis.zrevrange(key, 0, count - 1)) || [];\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
    ];
  }

  if (structure === "list") {
    return [
      {
        id: `redis-rpush-${tableName}`,
        name: `push${pascalSingular}`,
        kind: "create",
        description: `Append items to Redis list [${label}] (RPUSH)`,
        signature: `push${pascalSingular}(key: string, ...items: string[]): Promise<number>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "items", type: "string[]", required: true },
        ],
        returnType: "Promise<number>",
        logicMode: "code",
        code: `export async function push${pascalSingular}(key: string, ...items: string[]): Promise<number> {\n  const redis = await getRedisClient();\n  return await redis.rpush(key, ...items);\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-lpop-${tableName}`,
        name: `pop${pascalSingular}`,
        kind: "delete",
        description: `Remove and get the first element from Redis list [${label}] (LPOP)`,
        signature: `pop${pascalSingular}(key: string): Promise<string | null>`,
        params: [{ name: "key", type: "string", required: true }],
        returnType: "Promise<string | null>",
        logicMode: "code",
        code: `export async function pop${pascalSingular}(key: string): Promise<string | null> {\n  const redis = await getRedisClient();\n  return await redis.lpop(key);\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-lrange-${tableName}`,
        name: `get${pascalSingular}List`,
        kind: "findAll",
        description: `Get range of items from Redis list [${label}] (LRANGE)`,
        signature: `get${pascalSingular}List(key: string, start: number = 0, stop: number = -1): Promise<string[]>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "start", type: "number", required: false, defaultValue: "0" },
          { name: "stop", type: "number", required: false, defaultValue: "-1" },
        ],
        returnType: "Promise<string[]>",
        logicMode: "code",
        code: `export async function get${pascalSingular}List(key: string, start: number = 0, stop: number = -1): Promise<string[]> {\n  const redis = await getRedisClient();\n  return (await redis.lrange(key, start, stop)) || [];\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-llen-${tableName}`,
        name: `get${pascalSingular}Length`,
        kind: "findById",
        description: `Get length of Redis list [${label}] (LLEN)`,
        signature: `get${pascalSingular}Length(key: string): Promise<number>`,
        params: [{ name: "key", type: "string", required: true }],
        returnType: "Promise<number>",
        logicMode: "code",
        code: `export async function get${pascalSingular}Length(key: string): Promise<number> {\n  const redis = await getRedisClient();\n  return await redis.llen(key);\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-del-${tableName}`,
        name: `delete${pascalSingular}`,
        kind: "delete",
        description: `Delete Redis list [${label}] (DEL)`,
        signature: `delete${pascalSingular}(key: string): Promise<boolean>`,
        params: [{ name: "key", type: "string", required: true }],
        returnType: "Promise<boolean>",
        logicMode: "code",
        code: `export async function delete${pascalSingular}(key: string): Promise<boolean> {\n  const redis = await getRedisClient();\n  const res = await redis.del(key);\n  return res > 0;\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
    ];
  }

  if (structure === "json" && data?.jsonRootType === "array") {
    const itemType = `${pascalSingular}Item`;
    return [
      {
        id: `redis-json-arrappend-${tableName}`,
        name: `append${pascalSingular}Item`,
        kind: "create",
        description: `Append item to RedisJSON array [${label}] (JSON.ARRAPPEND)`,
        signature: `append${pascalSingular}Item(key: string, item: ${itemType}): Promise<Append${pascalSingular}ItemResult>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "item", type: itemType, required: true },
        ],
        returnType: `Promise<Append${pascalSingular}ItemResult>`,
        logicMode: "code",
        code: `export async function append${pascalSingular}Item(key: string, item: ${itemType}): Promise<Append${pascalSingular}ItemResult> {\n  try {\n    const redis = await getRedisClient();\n    // Upsert: ensure root array exists\n    await redis.call("JSON.SET", key, "$", "[]", "NX");\n    const res = await redis.call("JSON.ARRAPPEND", key, "$", JSON.stringify(item));\n    const count = Array.isArray(res) && typeof res[0] === "number" ? res[0] : typeof res === "number" ? res : 0;\n    return { success: true, data: count };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_JSON_ARRAPPEND_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-json-arrpop-${tableName}`,
        name: `pop${pascalSingular}Item`,
        kind: "delete",
        description: `Pop item from RedisJSON array [${label}] (JSON.ARRPOP)`,
        signature: `pop${pascalSingular}Item(key: string, index?: number): Promise<Pop${pascalSingular}ItemResult>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "index", type: "number", required: false, defaultValue: "-1" },
        ],
        returnType: `Promise<Pop${pascalSingular}ItemResult>`,
        logicMode: "code",
        code: `export async function pop${pascalSingular}Item(key: string, index: number = -1): Promise<Pop${pascalSingular}ItemResult> {\n  try {\n    const redis = await getRedisClient();\n    const res = await redis.call("JSON.ARRPOP", key, "$", index);\n    if (!res) return { success: true, data: null };\n    const parsed = typeof res === "string" ? JSON.parse(res) : res;\n    const data: ${itemType} | null = Array.isArray(parsed) ? (parsed[0] ?? null) : (parsed ?? null);\n    return { success: true, data };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_JSON_ARRPOP_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-json-getrecent-${tableName}`,
        name: `getRecent${pascalSingular}Items`,
        kind: "findAll",
        description: `Retrieve latest N items from RedisJSON array [${label}] (JSON.GET with slice)`,
        signature: `getRecent${pascalSingular}Items(key: string, count?: number): Promise<GetRecent${pascalSingular}ItemsResult>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "count", type: "number", required: false, defaultValue: "20" },
        ],
        returnType: `Promise<GetRecent${pascalSingular}ItemsResult>`,
        logicMode: "code",
        code: `export async function getRecent${pascalSingular}Items(key: string, count: number = 20): Promise<GetRecent${pascalSingular}ItemsResult> {\n  try {\n    const redis = await getRedisClient();\n    const res = await redis.call("JSON.GET", key, "INDENT", "", "NEWLINE", "", "SPACE", "", "PATH", "$[-" + count + ":]");\n    if (!res || typeof res !== "string") return { success: true, data: [] };\n    const parsed = JSON.parse(res);\n    const data: ${itemType}[] = Array.isArray(parsed) && Array.isArray(parsed[0]) ? parsed[0] : Array.isArray(parsed) ? parsed : [];\n    return { success: true, data };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_JSON_GET_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-json-arrlen-${tableName}`,
        name: `get${pascalSingular}Length`,
        kind: "findById",
        description: `Get array length of RedisJSON [${label}] (JSON.ARRLEN)`,
        signature: `get${pascalSingular}Length(key: string): Promise<Get${pascalSingular}LengthResult>`,
        params: [{ name: "key", type: "string", required: true }],
        returnType: `Promise<Get${pascalSingular}LengthResult>`,
        logicMode: "code",
        code: `export async function get${pascalSingular}Length(key: string): Promise<Get${pascalSingular}LengthResult> {\n  try {\n    const redis = await getRedisClient();\n    const res = await redis.call("JSON.ARRLEN", key, "$");\n    const count = Array.isArray(res) && typeof res[0] === "number" ? res[0] : typeof res === "number" ? res : 0;\n    return { success: true, data: count };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_JSON_ARRLEN_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-json-get-${tableName}`,
        name: `get${pascalSingular}`,
        kind: "findById",
        description: `Retrieve entire RedisJSON array document [${label}] (JSON.GET)`,
        signature: `get${pascalSingular}(key: string): Promise<Get${pascalSingular}Result>`,
        params: [{ name: "key", type: "string", required: true }],
        returnType: `Promise<Get${pascalSingular}Result>`,
        logicMode: "code",
        code: `export async function get${pascalSingular}(key: string): Promise<Get${pascalSingular}Result> {\n  try {\n    const redis = await getRedisClient();\n    const res = await redis.call("JSON.GET", key);\n    if (!res || typeof res !== "string") return { success: true, data: null };\n    const data: ${itemType}[] = JSON.parse(res);\n    return { success: true, data };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_JSON_GET_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-json-set-${tableName}`,
        name: `set${pascalSingular}`,
        kind: "create",
        description: `Set entire RedisJSON array document [${label}] (JSON.SET)`,
        signature: `set${pascalSingular}(key: string, value: ${itemType}[]): Promise<Set${pascalSingular}Result>`,
        params: [
          { name: "key", type: "string", required: true },
          { name: "value", type: `${itemType}[]`, required: true },
        ],
        returnType: `Promise<Set${pascalSingular}Result>`,
        logicMode: "code",
        code: `export async function set${pascalSingular}(key: string, value: ${itemType}[]): Promise<Set${pascalSingular}Result> {\n  try {\n    const redis = await getRedisClient();\n    await redis.call("JSON.SET", key, "$", JSON.stringify(value));\n    return { success: true, data: undefined };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_JSON_SET_ERROR" } };\n  }\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
      {
        id: `redis-del-${tableName}`,
        name: `delete${pascalSingular}`,
        kind: "delete",
        description: `Delete RedisJSON document [${label}] (DEL)`,
        signature: `delete${pascalSingular}(key: string): Promise<boolean>`,
        params: [{ name: "key", type: "string", required: true }],
        returnType: "Promise<boolean>",
        logicMode: "code",
        code: `export async function delete${pascalSingular}(key: string): Promise<boolean> {\n  const redis = await getRedisClient();\n  const res = await redis.del(key);\n  return res > 0;\n}`,
        enabled: true,
        isAutoGenerated: true,
      },
    ];
  }

  // Default: String / JSON
  return [
    {
      id: `redis-get-${tableName}`,
      name: `get${pascalSingular}`,
      kind: "findById",
      description: `Retrieve cached value for key from Redis`,
      signature: `get${pascalSingular}(key: string): Promise<Get${pascalSingular}Result>`,
      params: [{ name: "key", type: "string", required: true }],
      returnType: `Promise<Get${pascalSingular}Result>`,
      logicMode: "code",
      code: `export async function get${pascalSingular}(key: string): Promise<Get${pascalSingular}Result> {\n  try {\n    const redis = await getRedisClient();\n    const data = await redis.get(key);\n    if (!data) return { success: true, data: null };\n    return { success: true, data: JSON.parse(data) };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_GET_ERROR" } };\n  }\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `redis-set-${tableName}`,
      name: `set${pascalSingular}`,
      kind: "create",
      description: `Cache value in Redis with optional TTL`,
      signature: `set${pascalSingular}(key: string, value: Record<string, unknown>, ttlSeconds?: number): Promise<Set${pascalSingular}Result>`,
      params: [
        { name: "key", type: "string", required: true },
        { name: "value", type: "Record<string, unknown>", required: true },
        { name: "ttlSeconds", type: "number", required: false, defaultValue: "3600" },
      ],
      returnType: `Promise<Set${pascalSingular}Result>`,
      logicMode: "code",
      code: `export async function set${pascalSingular}(key: string, value: Record<string, unknown>, ttlSeconds?: number): Promise<Set${pascalSingular}Result> {\n  try {\n    const redis = await getRedisClient();\n    const serialized = typeof value === "string" ? value : JSON.stringify(value);\n    if (ttlSeconds && ttlSeconds > 0) {\n      await redis.setex(key, ttlSeconds, serialized);\n    } else {\n      await redis.set(key, serialized);\n    }\n    return { success: true, data: undefined };\n  } catch (error) {\n    const message = error instanceof Error ? error.message : String(error);\n    return { success: false, error: { message, code: "REDIS_SET_ERROR" } };\n  }\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
    {
      id: `redis-del-${tableName}`,
      name: `delete${pascalSingular}`,
      kind: "delete",
      description: `Delete cached key from Redis`,
      signature: `delete${pascalSingular}(key: string): Promise<boolean>`,
      params: [{ name: "key", type: "string", required: true }],
      returnType: "Promise<boolean>",
      logicMode: "code",
      code: `export async function delete${pascalSingular}(key: string): Promise<boolean> {\n  const redis = await getRedisClient();\n  const res = await redis.del(key);\n  return res > 0;\n}`,
      enabled: true,
      isAutoGenerated: true,
    },
  ];
}
