import type { StorageOperationOption } from "../types/storage";

export const STORAGE_TEST_DEFAULT_KEY = "uploads/avatars/user-42.png";
export const STORAGE_TEST_DEFAULT_CONTENT_TYPE = "image/png";

export const STORAGE_OPERATIONS: readonly StorageOperationOption[] = [
  {
    key: "createBucket",
    name: "createBucket",
    label: "createBucket(bucketName)",
    desc: "Dispatches HTTP PUT to create the bucket on the target server (SeaweedFS, MinIO, or AWS)",
    kind: "write",
    defaultKey: "",
  },
  {
    key: "uploadObject",
    name: "uploadObject",
    label: "uploadObject(bucket, key, body, options)",
    desc: "Dispatches HTTP PUT with file payload directly to configured storage server",
    kind: "write",
    defaultKey: STORAGE_TEST_DEFAULT_KEY,
    defaultContentType: STORAGE_TEST_DEFAULT_CONTENT_TYPE,
    defaultBody: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
  },
  {
    key: "downloadObject",
    name: "downloadObject",
    label: "downloadObject(bucket, key)",
    desc: "Dispatches HTTP GET to fetch object stream/body from configured server",
    kind: "read",
    defaultKey: STORAGE_TEST_DEFAULT_KEY,
    defaultContentType: STORAGE_TEST_DEFAULT_CONTENT_TYPE,
  },
  {
    key: "getUploadPresignedUrl",
    name: "getUploadPresignedUrl",
    label: "getUploadPresignedUrl(bucket, key, options)",
    desc: "Generates SigV4 presigned PUT URL and tests reachability against server",
    kind: "presign",
    defaultKey: STORAGE_TEST_DEFAULT_KEY,
    defaultContentType: STORAGE_TEST_DEFAULT_CONTENT_TYPE,
    defaultTtl: "900",
  },
  {
    key: "getDownloadPresignedUrl",
    name: "getDownloadPresignedUrl",
    label: "getDownloadPresignedUrl(bucket, key, options)",
    desc: "Generates SigV4 presigned GET URL for downloading private assets",
    kind: "presign",
    defaultKey: STORAGE_TEST_DEFAULT_KEY,
    defaultContentType: STORAGE_TEST_DEFAULT_CONTENT_TYPE,
    defaultTtl: "3600",
  },
  {
    key: "objectExists",
    name: "objectExists",
    label: "objectExists(bucket, key)",
    desc: "Dispatches HTTP HEAD request to check if object exists on live server",
    kind: "read",
    defaultKey: STORAGE_TEST_DEFAULT_KEY,
  },
  {
    key: "deleteObject",
    name: "deleteObject",
    label: "deleteObject(bucket, key)",
    desc: "Dispatches HTTP DELETE to permanently purge object on configured server",
    kind: "delete",
    defaultKey: STORAGE_TEST_DEFAULT_KEY,
  },
  {
    key: "listObjects",
    name: "listObjects",
    label: "listObjects(bucket, prefix, maxKeys)",
    desc: "Dispatches HTTP GET list-type=2 to enumerate objects on configured server",
    kind: "query",
    defaultKey: "uploads/",
  },
  {
    key: "getPublicObjectUrl",
    name: "getPublicObjectUrl",
    label: "getPublicObjectUrl(bucket, key)",
    desc: "Resolves public CDN or direct S3 URL and verifies public reachability",
    kind: "read",
    defaultKey: STORAGE_TEST_DEFAULT_KEY,
  },
];
