import { useMemo, useEffect } from "react";
import {
  Endpoint,
  BackendNode,
  BackendEdge,
  AnyMessagingResource,
} from "@workspace/canvas/types";
import {
  ConnectedTransformer,
  ConnectedKafka,
  ConnectedLangGraph,
  ConnectedRedis,
} from "@/types/canvas";
import { PipelineStepDraft, StepBinding } from "./types";
import {
  generateId,
  ensureRedisCacheConnection,
  ensureDatabaseRefConnection,
  ensurePageRefConnection,
  isAutoGeneratedStepName,
} from "./utils";
import {
  getConnectedTransformersForEndpoint,
  getConnectedKafkaForEndpoint,
  getConnectedLangGraphForEndpoint,
  getConnectedRedisForEndpoint,
} from "@/lib/utils/pipelineValidation";
import { getEntityDbOperations } from "@/lib/utils/entityOperationsHelper";
import { toFolderName, toVarName } from "@/lib/compiler/utils";

export interface UseCanvasStepSyncProps {
  steps: PipelineStepDraft[];
  executableSteps: PipelineStepDraft[];
  onChange: (steps: PipelineStepDraft[]) => void;
  targetId?: string;
  serviceNodeId?: string;
  endpoint?: Endpoint;
  consumedEvent?: AnyMessagingResource;
  allNodes?: BackendNode[];
  allEdges?: BackendEdge[];
  isNested?: boolean;
  isConsumer: boolean;
}

export interface UseCanvasStepSyncReturn {
  connectedTransformers: ConnectedTransformer[];
  connectedKafka: ConnectedKafka[];
  connectedLangGraph: ConnectedLangGraph[];
  connectedRedis: ConnectedRedis[];
}

export function useCanvasStepSync({
  steps,
  executableSteps,
  onChange,
  targetId,
  serviceNodeId,
  endpoint,
  consumedEvent,
  allNodes = [],
  allEdges = [],
  isNested = false,
  isConsumer,
}: UseCanvasStepSyncProps): UseCanvasStepSyncReturn {
  const connectedTransformers = useMemo(() => {
    if (!targetId || !serviceNodeId) return [];
    return getConnectedTransformersForEndpoint(
      targetId,
      serviceNodeId,
      allNodes,
      allEdges,
    );
  }, [targetId, serviceNodeId, allNodes, allEdges]);

  // Auto-synchronize connected transformers into the pipeline steps
  useEffect(() => {
    if (isNested || connectedTransformers.length === 0) return;

    // 1. Sync any existing transform steps whose returnSchema or function name has updated
    let stepsChanged = false;
    const syncedSteps = executableSteps.map((s) => {
      if (s.type !== "transform") return s;
      const matchingCt = connectedTransformers.find(
        (ct) =>
          (s.transformerNodeId &&
            (ct.id === s.transformerNodeId ||
              ct.nodeId === s.transformerNodeId ||
              ct.masterId === s.transformerNodeId)) ||
          s.functionRef?.name === ct.functionName ||
          (s.functionRef?.name &&
            toVarName(s.functionRef.name) === toVarName(ct.functionName)),
      );
      if (!matchingCt) return s;

      const updates: Partial<PipelineStepDraft> = {};

      // Sync functionRef and output variable name if function name changed
      const currentFnName = s.functionRef?.name;
      if (matchingCt.functionName && currentFnName !== matchingCt.functionName) {
        const cleanFnName = toVarName(matchingCt.functionName);
        updates.functionRef = {
          ...s.functionRef,
          name: cleanFnName,
          importPath: matchingCt.isGlobal
            ? "@workspace/transformers"
            : `../transformers/${cleanFnName}`,
          isGlobal: matchingCt.isGlobal,
          inputSchema: matchingCt.inputSchema,
          returnSchema: matchingCt.returnSchema,
        };
        if (isAutoGeneratedStepName(s.outputVariable)) {
          const newVar = `${cleanFnName}Result`;
          updates.outputVariable = newVar;
          updates.name = newVar;
        }
      }

      // Sync outputSchema if holding dummy result, empty, or differs from transformer return schema
      const currentSchema = s.outputSchema || [];
      const isDummy =
        currentSchema.length === 1 && currentSchema[0]?.name === "result";
      const hasRealCtSchema =
        Array.isArray(matchingCt.returnSchema) && matchingCt.returnSchema.length > 0;

      if (hasRealCtSchema) {
        const ctSchemaFields = matchingCt.returnSchema.map((r) => ({
          name: r.name,
          type: r.type || "string",
          required: r.required,
        }));
        const schemaDiffers =
          isDummy ||
          currentSchema.length !== ctSchemaFields.length ||
          ctSchemaFields.some(
            (cf, idx) =>
              cf.name !== currentSchema[idx]?.name ||
              cf.type !== currentSchema[idx]?.type,
          );

        if (schemaDiffers) {
          updates.outputSchema = ctSchemaFields;
          if (!updates.functionRef && s.functionRef) {
            updates.functionRef = {
              ...s.functionRef,
              returnSchema: matchingCt.returnSchema,
              inputSchema: matchingCt.inputSchema,
            };
          }
        }
      }

      if (Object.keys(updates).length > 0) {
        stepsChanged = true;
        return { ...s, ...updates };
      }
      return s;
    });

    // 2. Identify missing transformers to add
    const missingTransformers = connectedTransformers.filter(
      (ct) =>
        !syncedSteps.some(
          (s) =>
            s.type === "transform" &&
            (s.functionRef?.name === ct.functionName ||
              s.transformerNodeId === ct.id ||
              s.transformerNodeId === ct.nodeId ||
              s.transformerNodeId === ct.masterId),
        ),
    );

    if (missingTransformers.length > 0 || stepsChanged) {
      const newSteps: PipelineStepDraft[] = missingTransformers.map(
        (ct, idx) => {
          const stepNum = syncedSteps.length + idx + 1;
          const cleanFnName = toVarName(ct.functionName);
          const outputVar = `${cleanFnName}Result` || `transformedData${stepNum}`;
          const outputSchema = Array.isArray(ct.returnSchema) && ct.returnSchema.length > 0
            ? ct.returnSchema.map((r) => ({ name: r.name, type: r.type || "string", required: r.required }))
            : [{ name: "result", type: "string", required: true }];

          return {
            id: generateId(),
            name: outputVar,
            type: "transform",
            enabled: true,
            outputVariable: outputVar,
            functionRef: {
              name: cleanFnName,
              importPath: ct.isGlobal
                ? "@workspace/transformers"
                : `../transformers/${cleanFnName}`,
              isGlobal: ct.isGlobal,
              inputSchema: ct.inputSchema,
              returnSchema: ct.returnSchema,
            },
            outputSchema,
            transformerNodeId: ct.id,
            inputBindings: [],
          };
        },
      );

      if (isConsumer) {
        onChange([...syncedSteps, ...newSteps]);
      } else {
        const foundReturn = steps.find((s) => s.type === "return_response");
        onChange([
          ...syncedSteps,
          ...newSteps,
          foundReturn || {
            id: "return-response-step",
            name: "Return Response",
            type: "return_response",
            enabled: true,
            statusCode: endpoint?.type === "POST" ? 201 : 200,
            inputBindings: [],
            outputVariable: "",
          },
        ]);
      }
    }
  }, [
    isNested,
    connectedTransformers,
    executableSteps,
    isConsumer,
    onChange,
    serviceNodeId,
    endpoint?.type,
    steps,
  ]);

  const connectedKafka = useMemo(() => {
    if (!targetId || !serviceNodeId) return [];
    return getConnectedKafkaForEndpoint(
      targetId,
      serviceNodeId,
      allNodes,
      allEdges,
      endpoint,
    );
  }, [targetId, serviceNodeId, allNodes, allEdges, endpoint]);

  // Auto-synchronize connected Kafka topics into the pipeline steps
  useEffect(() => {
    if (isNested || connectedKafka.length === 0) return;

    const missingKafka = connectedKafka.filter(
      (ck) =>
        !executableSteps.some(
          (s) =>
            s.type === "kafka_publish" &&
            (s.functionRef?.name === ck.functionName ||
              s.brokerNodeId === ck.brokerNodeId ||
              s.messagingResourceId === ck.topicId),
        ),
    );

    if (missingKafka.length > 0) {
      const newKafkaSteps: PipelineStepDraft[] = missingKafka.map(
        (ck, idx) => {
          const stepNum = executableSteps.length + idx + 1;
          const outputVar = `kafkaPublishResult${stepNum > 1 ? stepNum : ""}`;
          const inputBindings: StepBinding[] = [];
          if (ck.functionName === "publishKafkaEvent") {
            inputBindings.push({
              argName: "topic",
              source: {
                kind: "inline",
                value: ck.topicName || "events",
              },
            });
          }
          inputBindings.push({
            argName: ck.functionName === "publishKafkaEvent" ? "payload" : "message",
            source: { kind: "req_body", field: "" },
          });

          return {
            id: generateId(),
            name: ck.publisherName || `Publish ${ck.topicName}`,
            type: "kafka_publish",
            enabled: true,
            outputVariable: outputVar,
            functionRef: {
              name: ck.functionName,
              importPath: ck.importPath,
            },
            inputBindings,
            brokerNodeId: ck.brokerNodeId,
            messagingResourceId: ck.topicId,
          };
        },
      );

      if (isConsumer) {
        onChange([...executableSteps, ...newKafkaSteps]);
      } else {
        const foundReturn = steps.find((s) => s.type === "return_response");
        onChange([
          ...executableSteps,
          ...newKafkaSteps,
          foundReturn || {
            id: "return-response-step",
            name: "Return Response",
            type: "return_response",
            enabled: true,
            statusCode: endpoint?.type === "POST" ? 201 : 200,
            inputBindings: [],
            outputVariable: "",
          },
        ]);
      }
    }
  }, [
    isNested,
    connectedKafka,
    executableSteps,
    isConsumer,
    onChange,
    serviceNodeId,
    endpoint?.type,
    steps,
  ]);

  const connectedLangGraph = useMemo(() => {
    if (!targetId || !serviceNodeId) return [];
    return getConnectedLangGraphForEndpoint(
      targetId,
      serviceNodeId,
      allNodes,
      allEdges,
    );
  }, [targetId, serviceNodeId, allNodes, allEdges]);

  // Auto-synchronize connected LangGraph agents into the pipeline steps
  useEffect(() => {
    if (isNested || connectedLangGraph.length === 0) return;

    const missingLangGraph = connectedLangGraph.filter(
      (clg) =>
        !executableSteps.some(
          (s) =>
            s.type === "langgraph_invoke" &&
            (s.langGraphTargetNodeId === clg.id || s.name === clg.label),
        ),
    );

    if (missingLangGraph.length > 0) {
      const newLangGraphSteps: PipelineStepDraft[] = missingLangGraph.map(
        (clg, idx) => {
          const stepNum = executableSteps.length + idx + 1;
          const agentLabel = clg.label || "LangGraph Agent";
          const outputVar = `${toVarName(agentLabel)}Result${stepNum > 1 ? stepNum : ""}`;
          const defaultMapping: Record<string, string> = {};
          if (clg.stateChannels && clg.stateChannels.length > 0) {
            clg.stateChannels.forEach((ch) => {
              if (ch.key === "messages") {
                defaultMapping[ch.key] = isConsumer ? "event.message" : "body.message";
              } else {
                defaultMapping[ch.key] = isConsumer ? `event.${ch.key}` : `body.${ch.key}`;
              }
            });
          } else {
            defaultMapping["messages"] = isConsumer ? "event.message" : "body.message";
          }

          return {
            id: generateId(),
            name: agentLabel,
            type: "langgraph_invoke",
            enabled: true,
            outputVariable: outputVar,
            langGraphTargetNodeId: clg.id,
            langGraphStreamingEnabled: false,
            langGraphStreamingProtocol: "sse",
            langGraphOutputMode: "full_state",
            langGraphStateMapping: defaultMapping,
            inputBindings: [],
          };
        },
      );

      if (isConsumer) {
        onChange([...executableSteps, ...newLangGraphSteps]);
      } else {
        const foundReturn = steps.find((s) => s.type === "return_response");
        onChange([
          ...executableSteps,
          ...newLangGraphSteps,
          foundReturn || {
            id: "return-response-step",
            name: "Return Response",
            type: "return_response",
            enabled: true,
            statusCode: endpoint?.type === "POST" ? 201 : 200,
            inputBindings: [],
            outputVariable: "",
          },
        ]);
      }
    }
  }, [
    isNested,
    connectedLangGraph,
    executableSteps,
    isConsumer,
    onChange,
    serviceNodeId,
    endpoint?.type,
    steps,
  ]);

  const connectedRedis = useMemo(() => {
    if (!targetId || !serviceNodeId) return [];
    return getConnectedRedisForEndpoint(
      targetId,
      serviceNodeId,
      allNodes,
      allEdges,
    );
  }, [targetId, serviceNodeId, allNodes, allEdges]);

  // Auto-synchronize connected Redis cache into the pipeline steps
  useEffect(() => {
    if (isNested || connectedRedis.length === 0) return;

    const missingRedis = connectedRedis.filter(
      (cr) =>
        !executableSteps.some(
          (s) =>
            s.type === "redis_operation" &&
            (s.tableNodeId === cr.schemaId ||
              s.tableNodeId === cr.cacheNodeId ||
              (cr.instanceId && s.databaseId === cr.instanceId)),
        ),
    );

    if (missingRedis.length > 0) {
      const newRedisSteps: PipelineStepDraft[] = missingRedis.map(
        (cr, idx) => {
          const stepNum = executableSteps.length + idx + 1;
          const targetSchemaNode = cr.schemaNode || cr.cacheNode;
          const ops = targetSchemaNode ? getEntityDbOperations(targetSchemaNode, allNodes) : [];
          const defaultOp = ops[0];
          const varName = defaultOp
            ? `${toVarName(defaultOp.name)}Result`
            : `cachedResult${stepNum > 1 ? stepNum : ""}`;
          const instanceLabel = cr.instanceNode?.data?.label || "primary-redis-cache";
          const importPath = `@workspace/${toFolderName(instanceLabel)}`;

          return {
            id: generateId(),
            name: varName,
            type: "redis_operation",
            enabled: true,
            outputVariable: varName,
            tableNodeId: cr.schemaId || cr.cacheNodeId,
            databaseId: cr.instanceId,
            operationId: defaultOp?.id,
            functionRef: defaultOp
              ? {
                  name: defaultOp.name,
                  importPath,
                  signature: defaultOp.signature,
                }
              : undefined,
            inputBindings: [],
          };
        },
      );

      if (isConsumer) {
        onChange([...executableSteps, ...newRedisSteps]);
      } else {
        const foundReturn = steps.find((s) => s.type === "return_response");
        onChange([
          ...executableSteps,
          ...newRedisSteps,
          foundReturn || {
            id: "return-response-step",
            name: "Return Response",
            type: "return_response",
            enabled: true,
            statusCode: endpoint?.type === "POST" ? 201 : 200,
            inputBindings: [],
            outputVariable: "",
          },
        ]);
      }
    }
  }, [
    isNested,
    connectedRedis,
    executableSteps,
    isConsumer,
    onChange,
    serviceNodeId,
    endpoint?.type,
    steps,
    allNodes,
  ]);

  // Stable synchronization keys to prevent re-running connection effects on internal step property changes (e.g. checkbox toggles)
  const redisStepsKey = useMemo(
    () =>
      executableSteps
        .filter((s) => s.type === "redis_operation" && s.tableNodeId && s.tableNodeId !== "__none__")
        .map((s) => `${s.id}:${s.tableNodeId}:${s.databaseId}`)
        .join("|"),
    [executableSteps],
  );

  const dbStepsKey = useMemo(
    () =>
      executableSteps
        .filter((s) => s.type === "db_operation" && (s.tableNodeId || s.databaseId))
        .map((s) => `${s.id}:${s.tableNodeId}:${s.databaseId}:${s.functionRef?.name || s.operationId}`)
        .join("|"),
    [executableSteps],
  );

  const pushStepsKey = useMemo(
    () =>
      executableSteps
        .filter((s) => s.type === "push_to_client")
        .map((s) => `${s.id}:${s.clientDeliveryTargetPageId}:${s.clientDeliveryPageRefNodeId}`)
        .join("|"),
    [executableSteps],
  );

  // Auto-synchronize connected Redis cache nodes and edges for configured redis_operation steps
  useEffect(() => {
    if (!serviceNodeId) return;
    const redisSteps = executableSteps.filter(
      (s) => s.type === "redis_operation" && s.tableNodeId && s.tableNodeId !== "__none__",
    );
    if (redisSteps.length === 0) return;

    redisSteps.forEach((s) => {
      ensureRedisCacheConnection({
        schemaId: s.tableNodeId,
        instanceId: s.databaseId,
        serviceNodeId,
        endpointId: endpoint?.id,
        consumedEventId: consumedEvent?.id,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [redisStepsKey, serviceNodeId, endpoint?.id, consumedEvent?.id]);

  // Auto-synchronize connected Database ref nodes and function edges for configured db_operation steps
  useEffect(() => {
    if (!serviceNodeId) return;
    const dbSteps = executableSteps.filter(
      (s) => s.type === "db_operation" && (s.tableNodeId || s.databaseId),
    );
    if (dbSteps.length === 0) return;

    dbSteps.forEach((s) => {
      ensureDatabaseRefConnection({
        tableNodeId: s.tableNodeId,
        databaseId: s.databaseId,
        serviceNodeId,
        endpointId: endpoint?.id,
        consumedEventId: consumedEvent?.id,
        functionName: s.functionRef?.name || s.operationId,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dbStepsKey, serviceNodeId, endpoint?.id, consumedEvent?.id]);

  // Auto-synchronize connected PageRef nodes and edges for configured push_to_client steps
  useEffect(() => {
    if (!serviceNodeId) return;
    const pushSteps = executableSteps.filter((s) => s.type === "push_to_client");
    if (pushSteps.length === 0) return;

    pushSteps.forEach((s) => {
      ensurePageRefConnection({
        targetPageId: s.clientDeliveryTargetPageId,
        pageRefNodeId: s.clientDeliveryPageRefNodeId,
        serviceNodeId,
        endpointId: endpoint?.id,
        consumedEventId: consumedEvent?.id,
        stepId: s.id,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pushStepsKey, serviceNodeId, endpoint?.id, consumedEvent?.id]);

  return {
    connectedTransformers,
    connectedKafka,
    connectedLangGraph,
    connectedRedis,
  };
}
