import { useMemo, useEffect } from "react";
import {
  Endpoint,
  BackendNode,
  BackendEdge,
  AnyMessagingResource,
} from "@workspace/canvas/types";
import {
  ConnectedTransformer,
  ConnectedKafka,
  ConnectedLangGraph,
  ConnectedRedis,
  ConnectedServiceCall,
} from "@/types/canvas";
import { PipelineStepDraft, StepBinding } from "./types";
import {
  generateId,
  ensureRedisCacheConnection,
  ensureDatabaseRefConnection,
  ensurePageRefConnection,
  ensureLangGraphConnection,
  ensureTransformerConnection,
  ensureStorageOperationRefConnection,
  ensureServiceCallConnection,
  isAutoGeneratedStepName,
  flattenAllPipelineSteps,
} from "./utils";
import {
  getConnectedTransformersForEndpoint,
  getConnectedKafkaForEndpoint,
  getConnectedLangGraphForEndpoint,
  getConnectedRedisForEndpoint,
  getConnectedServiceCallsForEndpoint,
} from "@/lib/utils/pipelineValidation";
import { getEntityDbOperations } from "@/lib/utils/entityOperationsHelper";
import { toFolderName, toPascalCase, toVarName } from "@/lib/compiler/utils";

export interface UseCanvasStepSyncProps {
  steps: PipelineStepDraft[];
  executableSteps: PipelineStepDraft[];
  onChange: (steps: PipelineStepDraft[]) => void;
  targetId?: string;
  serviceNodeId?: string;
  endpoint?: Endpoint;
  consumedEvent?: AnyMessagingResource;
  allNodes?: BackendNode[];
  allEdges?: BackendEdge[];
  isNested?: boolean;
  isConsumer: boolean;
}

export interface UseCanvasStepSyncReturn {
  connectedTransformers: ConnectedTransformer[];
  connectedKafka: ConnectedKafka[];
  connectedLangGraph: ConnectedLangGraph[];
  connectedRedis: ConnectedRedis[];
  connectedServiceCalls: ConnectedServiceCall[];
}

export function useCanvasStepSync({
  steps,
  executableSteps,
  onChange,
  targetId,
  serviceNodeId,
  endpoint,
  consumedEvent,
  allNodes = [],
  allEdges = [],
  isNested = false,
  isConsumer,
}: UseCanvasStepSyncProps): UseCanvasStepSyncReturn {
  const connectedTransformers = useMemo(() => {
    if (!targetId || !serviceNodeId) return [];
    return getConnectedTransformersForEndpoint(
      targetId,
      serviceNodeId,
      allNodes,
      allEdges,
    );
  }, [targetId, serviceNodeId, allNodes, allEdges]);

  // Recursively collect all pipeline steps across control flow branches (if/try/loop/switch/parallel/cacheMiss)
  const allFlatSteps = useMemo(
    () => flattenAllPipelineSteps(executableSteps),
    [executableSteps],
  );

  // Auto-synchronize connected transformers into the pipeline steps
  useEffect(() => {
    if (isNested || connectedTransformers.length === 0) return;

    // 1. Sync any existing transform steps whose returnSchema or function name has updated
    let stepsChanged = false;
    const syncedSteps = executableSteps.map((s) => {
      if (s.type !== "transform") return s;
      const matchingCt = connectedTransformers.find(
        (ct) =>
          (s.transformerNodeId &&
            (ct.id === s.transformerNodeId ||
              ct.nodeId === s.transformerNodeId ||
              ct.masterId === s.transformerNodeId)) ||
          s.functionRef?.name === ct.functionName ||
          (s.functionRef?.name &&
            toVarName(s.functionRef.name) === toVarName(ct.functionName)),
      );
      if (!matchingCt) return s;

      const updates: Partial<PipelineStepDraft> = {};

      // Sync functionRef and output variable name if function name changed
      const currentFnName = s.functionRef?.name;
      if (matchingCt.functionName && currentFnName !== matchingCt.functionName) {
        const cleanFnName = toVarName(matchingCt.functionName);
        updates.functionRef = {
          ...s.functionRef,
          name: cleanFnName,
          importPath: matchingCt.isGlobal
            ? "@workspace/transformers"
            : `../transformers/${cleanFnName}`,
          isGlobal: matchingCt.isGlobal,
          inputSchema: matchingCt.inputSchema,
          returnSchema: matchingCt.returnSchema,
        };
        if (isAutoGeneratedStepName(s.outputVariable)) {
          const newVar = `${cleanFnName}Result`;
          updates.outputVariable = newVar;
          updates.name = newVar;
        }
      }

      // Sync outputSchema if differing from transformer return schema
      const currentSchema = s.outputSchema || [];
      const hasRealCtSchema =
        Array.isArray(matchingCt.returnSchema) && matchingCt.returnSchema.length > 0;

      if (hasRealCtSchema) {
        const ctSchemaFields = matchingCt.returnSchema.map((r) => ({
          name: r.name,
          type: r.type || "string",
          required: r.required,
        }));
        const schemaDiffers =
          currentSchema.length !== ctSchemaFields.length ||
          ctSchemaFields.some(
            (cf, idx) =>
              cf.name !== currentSchema[idx]?.name ||
              cf.type !== currentSchema[idx]?.type,
          );

        if (schemaDiffers) {
          updates.outputSchema = ctSchemaFields;
          if (!updates.functionRef && s.functionRef) {
            updates.functionRef = {
              ...s.functionRef,
              returnSchema: matchingCt.returnSchema,
              inputSchema: matchingCt.inputSchema,
            };
          }
        }
      }

      // Sync inputSchema and prune stale inputBindings if transformer input schema changed
      const currentInputSchema = s.functionRef?.inputSchema || [];
      const ctInputSchema = matchingCt.inputSchema || [];
      const inputSchemaDiffers =
        currentInputSchema.length !== ctInputSchema.length ||
        ctInputSchema.some((cf, idx) => cf.name !== currentInputSchema[idx]?.name);

      if (inputSchemaDiffers) {
        const cleanName = toVarName(matchingCt.functionName);
        const importPath =
          updates.functionRef?.importPath ||
          s.functionRef?.importPath ||
          (matchingCt.isGlobal
            ? "@workspace/transformers"
            : `../transformers/${cleanName}`);

        updates.functionRef = {
          name: updates.functionRef?.name || s.functionRef?.name || cleanName,
          importPath,
          isGlobal: matchingCt.isGlobal ?? s.functionRef?.isGlobal,
          inputSchema: ctInputSchema,
          returnSchema: updates.functionRef?.returnSchema || s.functionRef?.returnSchema || matchingCt.returnSchema,
        };
        if (ctInputSchema.length === 0) {
          updates.inputBindings = [];
        } else {
          const validNames = new Set(
            ctInputSchema.map((f) => f.name?.toLowerCase()).filter(Boolean),
          );
          updates.inputBindings = (s.inputBindings || []).filter(
            (b) => b.argName && validNames.has(b.argName.toLowerCase()),
          );
        }
      }

      if (Object.keys(updates).length > 0) {
        stepsChanged = true;
        return { ...s, ...updates };
      }
      return s;
    });

    // 2. Identify missing transformers to add
    const missingTransformers = connectedTransformers.filter(
      (ct) =>
        !allFlatSteps.some(
          (s) =>
            s.type === "transform" &&
            (s.functionRef?.name === ct.functionName ||
              (s.functionRef?.name &&
                toVarName(s.functionRef.name) === toVarName(ct.functionName)) ||
              s.transformerNodeId === ct.id ||
              s.transformerNodeId === ct.nodeId ||
              s.transformerNodeId === ct.masterId),
        ),
    );

    if (missingTransformers.length > 0 || stepsChanged) {
      const newSteps: PipelineStepDraft[] = missingTransformers.map(
        (ct, idx) => {
          const stepNum = syncedSteps.length + idx + 1;
          const cleanFnName = toVarName(ct.functionName);
          const outputVar = `${cleanFnName}Result` || `transformedData${stepNum}`;
          const outputSchema = Array.isArray(ct.returnSchema) && ct.returnSchema.length > 0
            ? ct.returnSchema.map((r) => ({ name: r.name, type: r.type || "string", required: r.required }))
            : [{ name: "result", type: "string", required: true }];

          return {
            id: generateId(),
            name: outputVar,
            type: "transform",
            enabled: true,
            outputVariable: outputVar,
            functionRef: {
              name: cleanFnName,
              importPath: ct.isGlobal
                ? "@workspace/transformers"
                : `../transformers/${cleanFnName}`,
              isGlobal: ct.isGlobal,
              inputSchema: ct.inputSchema,
              returnSchema: ct.returnSchema,
            },
            outputSchema,
            transformerNodeId: ct.id,
            inputBindings: [],
          };
        },
      );

      if (isConsumer) {
        onChange([...syncedSteps, ...newSteps]);
      } else {
        const foundReturn = steps.find((s) => s.type === "return_response");
        onChange([
          ...syncedSteps,
          ...newSteps,
          foundReturn || {
            id: "return-response-step",
            name: "Return Response",
            type: "return_response",
            enabled: true,
            statusCode: endpoint?.type === "POST" ? 201 : 200,
            inputBindings: [],
            outputVariable: "",
          },
        ]);
      }
    }
  }, [
    isNested,
    connectedTransformers,
    executableSteps,
    isConsumer,
    onChange,
    serviceNodeId,
    endpoint?.type,
    steps,
  ]);

  const connectedKafka = useMemo(() => {
    if (!targetId || !serviceNodeId) return [];
    return getConnectedKafkaForEndpoint(
      targetId,
      serviceNodeId,
      allNodes,
      allEdges,
      endpoint,
    );
  }, [targetId, serviceNodeId, allNodes, allEdges, endpoint]);

  // Auto-synchronize connected Kafka topics into the pipeline steps
  useEffect(() => {
    if (isNested || connectedKafka.length === 0) return;

    const missingKafka = connectedKafka.filter(
      (ck) =>
        !allFlatSteps.some(
          (s) =>
            s.type === "kafka_publish" &&
            (s.functionRef?.name === ck.functionName ||
              s.brokerNodeId === ck.brokerNodeId ||
              s.messagingResourceId === ck.topicId),
        ),
    );

    if (missingKafka.length > 0) {
      const newKafkaSteps: PipelineStepDraft[] = missingKafka.map(
        (ck, idx) => {
          const stepNum = executableSteps.length + idx + 1;
          const outputVar = `kafkaPublishResult${stepNum > 1 ? stepNum : ""}`;
          const inputBindings: StepBinding[] = [];
          if (ck.functionName === "publishKafkaEvent") {
            inputBindings.push({
              argName: "topic",
              source: {
                kind: "inline",
                value: ck.topicName || "events",
              },
            });
          }
          inputBindings.push({
            argName: ck.functionName === "publishKafkaEvent" ? "payload" : "message",
            source: { kind: "req_body", field: "" },
          });

          return {
            id: generateId(),
            name: ck.publisherName || `Publish ${ck.topicName}`,
            type: "kafka_publish",
            enabled: true,
            outputVariable: outputVar,
            functionRef: {
              name: ck.functionName,
              importPath: ck.importPath,
            },
            inputBindings,
            brokerNodeId: ck.brokerNodeId,
            messagingResourceId: ck.topicId,
          };
        },
      );

      if (isConsumer) {
        onChange([...executableSteps, ...newKafkaSteps]);
      } else {
        const foundReturn = steps.find((s) => s.type === "return_response");
        onChange([
          ...executableSteps,
          ...newKafkaSteps,
          foundReturn || {
            id: "return-response-step",
            name: "Return Response",
            type: "return_response",
            enabled: true,
            statusCode: endpoint?.type === "POST" ? 201 : 200,
            inputBindings: [],
            outputVariable: "",
          },
        ]);
      }
    }
  }, [
    isNested,
    connectedKafka,
    executableSteps,
    isConsumer,
    onChange,
    serviceNodeId,
    endpoint?.type,
    steps,
  ]);

  const connectedLangGraph = useMemo(() => {
    if (!targetId || !serviceNodeId) return [];
    return getConnectedLangGraphForEndpoint(
      targetId,
      serviceNodeId,
      allNodes,
      allEdges,
    );
  }, [targetId, serviceNodeId, allNodes, allEdges]);

  // Auto-synchronize connected LangGraph agents into the pipeline steps
  useEffect(() => {
    if (isNested || connectedLangGraph.length === 0) return;

    const missingLangGraph = connectedLangGraph.filter(
      (clg) =>
        !allFlatSteps.some(
          (s) =>
            s.type === "langgraph_invoke" &&
            (s.langGraphTargetNodeId === clg.id || s.name === clg.label),
        ),
    );

    if (missingLangGraph.length > 0) {
      const newLangGraphSteps: PipelineStepDraft[] = missingLangGraph.map(
        (clg, idx) => {
          const stepNum = executableSteps.length + idx + 1;
          const agentLabel = clg.label || "LangGraph Agent";
          const outputVar = `${toVarName(agentLabel)}Result${stepNum > 1 ? stepNum : ""}`;
          const defaultMapping: Record<string, string> = {};
          if (clg.stateChannels && clg.stateChannels.length > 0) {
            clg.stateChannels.forEach((ch) => {
              if (ch.key === "messages") {
                defaultMapping[ch.key] = isConsumer ? "event.message" : "body.message";
              } else {
                defaultMapping[ch.key] = isConsumer ? `event.${ch.key}` : `body.${ch.key}`;
              }
            });
          } else {
            defaultMapping["messages"] = isConsumer ? "event.message" : "body.message";
          }

          const memoryConfig = clg.node?.data?.memoryConfig;
          const hasMemory = Boolean(
            memoryConfig &&
            memoryConfig.enabled !== false &&
            memoryConfig.checkpointer,
          );

          return {
            id: generateId(),
            name: agentLabel,
            type: "langgraph_invoke",
            enabled: true,
            outputVariable: outputVar,
            langGraphTargetNodeId: clg.id,
            langGraphStreamingEnabled: false,
            langGraphStreamingProtocol: "sse",
            langGraphOutputMode: "full_state",
            langGraphStateMapping: defaultMapping,
            ...(hasMemory
              ? {
                  langGraphThreadIdSource: isConsumer
                    ? "event.thread_id"
                    : "body.thread_id",
                }
              : {}),
            inputBindings: [],
          };
        },
      );

      if (isConsumer) {
        onChange([...executableSteps, ...newLangGraphSteps]);
      } else {
        const foundReturn = steps.find((s) => s.type === "return_response");
        onChange([
          ...executableSteps,
          ...newLangGraphSteps,
          foundReturn || {
            id: "return-response-step",
            name: "Return Response",
            type: "return_response",
            enabled: true,
            statusCode: endpoint?.type === "POST" ? 201 : 200,
            inputBindings: [],
            outputVariable: "",
          },
        ]);
      }
    }
  }, [
    isNested,
    connectedLangGraph,
    executableSteps,
    isConsumer,
    onChange,
    serviceNodeId,
    endpoint?.type,
    steps,
  ]);

  const connectedRedis = useMemo(() => {
    if (!targetId || !serviceNodeId) return [];
    return getConnectedRedisForEndpoint(
      targetId,
      serviceNodeId,
      allNodes,
      allEdges,
    );
  }, [targetId, serviceNodeId, allNodes, allEdges]);

  // Auto-synchronize connected Redis cache into the pipeline steps
  useEffect(() => {
    if (isNested || connectedRedis.length === 0) return;

    const missingRedis = connectedRedis.filter(
      (cr) =>
        !allFlatSteps.some(
          (s) =>
            s.type === "redis_operation" &&
            (s.tableNodeId === cr.schemaId ||
              s.tableNodeId === cr.cacheNodeId ||
              (cr.instanceId && s.databaseId === cr.instanceId)),
        ),
    );

    if (missingRedis.length > 0) {
      const newRedisSteps: PipelineStepDraft[] = missingRedis.map(
        (cr, idx) => {
          const stepNum = executableSteps.length + idx + 1;
          const targetSchemaNode = cr.schemaNode || cr.cacheNode;
          const ops = targetSchemaNode ? getEntityDbOperations(targetSchemaNode, allNodes) : [];
          const defaultOp = ops[0];
          const varName = defaultOp
            ? `${toVarName(defaultOp.name)}Result`
            : `cachedResult${stepNum > 1 ? stepNum : ""}`;
          const instanceLabel = cr.instanceNode?.data?.label || "primary-redis-cache";
          const importPath = `@workspace/${toFolderName(instanceLabel)}`;

          return {
            id: generateId(),
            name: varName,
            type: "redis_operation",
            enabled: true,
            outputVariable: varName,
            tableNodeId: cr.schemaId || cr.cacheNodeId,
            databaseId: cr.instanceId,
            operationId: defaultOp?.id,
            functionRef: defaultOp
              ? {
                  name: defaultOp.name,
                  importPath,
                  signature: defaultOp.signature,
                }
              : undefined,
            inputBindings: [],
          };
        },
      );

      if (isConsumer) {
        onChange([...executableSteps, ...newRedisSteps]);
      } else {
        const foundReturn = steps.find((s) => s.type === "return_response");
        onChange([
          ...executableSteps,
          ...newRedisSteps,
          foundReturn || {
            id: "return-response-step",
            name: "Return Response",
            type: "return_response",
            enabled: true,
            statusCode: endpoint?.type === "POST" ? 201 : 200,
            inputBindings: [],
            outputVariable: "",
          },
        ]);
      }
    }
  }, [
    isNested,
    connectedRedis,
    executableSteps,
    isConsumer,
    onChange,
    serviceNodeId,
    endpoint?.type,
    steps,
    allNodes,
  ]);

  const connectedServiceCalls = useMemo(() => {
    if (!targetId || !serviceNodeId) return [];
    return getConnectedServiceCallsForEndpoint(
      targetId,
      serviceNodeId,
      allNodes,
      allEdges,
    );
  }, [targetId, serviceNodeId, allNodes, allEdges]);

  // Auto-synchronize connected inter-service endpoint calls into the pipeline steps
  useEffect(() => {
    if (isNested || connectedServiceCalls.length === 0) return;

    const missingServiceCalls = connectedServiceCalls.filter(
      (csc) =>
        !allFlatSteps.some(
          (s) =>
            s.type === "service_call" &&
            ((s.databaseId === csc.targetServiceId && (s.tableNodeId === csc.targetEndpointId || s.operationId === csc.operationId)) ||
              (s.tableNodeId === csc.targetEndpointId && s.functionRef?.name === csc.functionName) ||
              s.externalEndpointId === csc.targetEndpointId),
        ),
    );

    if (missingServiceCalls.length > 0) {
      const newServiceCallSteps: PipelineStepDraft[] = missingServiceCalls.map(
        (csc, idx) => {
          const stepNum = executableSteps.length + idx + 1;
          const serviceLabel = csc.serviceLabel || "service";
          const baseVar = `${toVarName(serviceLabel)}Response`;
          const outputVar = executableSteps.some((s) => s.outputVariable === baseVar)
            ? `${baseVar}${stepNum}`
            : baseVar;

          const defaultBindings: StepBinding[] = [];
          const targetEp = csc.targetEndpoint;
          if (targetEp?.pathParams && targetEp.pathParams.length > 0) {
            targetEp.pathParams.forEach((p) => {
              if (p?.name?.trim()) {
                defaultBindings.push({
                  argName: p.name.trim(),
                  source: { kind: "req_body", field: p.name.trim() },
                });
              }
            });
          }
          if (targetEp?.queryParams && targetEp.queryParams.length > 0) {
            targetEp.queryParams.forEach((q) => {
              if (q?.name?.trim()) {
                defaultBindings.push({
                  argName: q.name.trim(),
                  source: { kind: "req_query", field: q.name.trim() },
                });
              }
            });
          }
          if (targetEp?.requestBody?.fields && targetEp.requestBody.fields.length > 0) {
            targetEp.requestBody.fields.forEach((f) => {
              if (f?.name?.trim()) {
                defaultBindings.push({
                  argName: f.name.trim(),
                  source: { kind: "req_body", field: f.name.trim() },
                });
              }
            });
          }

          return {
            id: generateId(),
            name: outputVar,
            type: "service_call",
            enabled: true,
            outputVariable: outputVar,
            databaseId: csc.targetServiceId,
            tableNodeId: csc.targetEndpointId,
            operationId: csc.operationId,
            functionRef: {
              name: csc.functionName,
              importPath: csc.importPath,
              signature: `call${toPascalCase(serviceLabel)}${toPascalCase(`${(targetEp?.type || "GET").toLowerCase()}_${targetEp?.name?.replace(/[^a-zA-Z0-9]/g, "") || "call"}`)}(params?: Record<string, unknown>, body?: Record<string, unknown>): Promise<unknown>`,
            },
            inputBindings: defaultBindings,
          };
        },
      );

      if (isConsumer) {
        onChange([...executableSteps, ...newServiceCallSteps]);
      } else {
        const foundReturn = steps.find((s) => s.type === "return_response");
        onChange([
          ...executableSteps,
          ...newServiceCallSteps,
          foundReturn || {
            id: "return-response-step",
            name: "Return Response",
            type: "return_response",
            enabled: true,
            statusCode: endpoint?.type === "POST" ? 201 : 200,
            inputBindings: [],
            outputVariable: "",
          },
        ]);
      }
    }
  }, [
    isNested,
    connectedServiceCalls,
    executableSteps,
    isConsumer,
    onChange,
    serviceNodeId,
    endpoint?.type,
    steps,
  ]);

  // Stable synchronization keys to prevent re-running connection effects on internal step property changes (e.g. checkbox toggles)
  const redisStepsKey = useMemo(
    () =>
      allFlatSteps
        .filter((s) => s.type === "redis_operation" && s.tableNodeId && s.tableNodeId !== "__none__")
        .map((s) => `${s.id}:${s.tableNodeId}:${s.databaseId}`)
        .join("|"),
    [allFlatSteps],
  );

  const dbStepsKey = useMemo(
    () =>
      allFlatSteps
        .filter((s) => s.type === "db_operation" && (s.tableNodeId || s.databaseId))
        .map((s) => `${s.id}:${s.tableNodeId}:${s.databaseId}:${s.functionRef?.name || s.operationId}`)
        .join("|"),
    [allFlatSteps],
  );

  const pushStepsKey = useMemo(
    () =>
      allFlatSteps
        .filter((s) => s.type === "push_to_client")
        .map((s) => `${s.id}:${s.clientDeliveryTargetPageId}:${s.clientDeliveryPageRefNodeId}`)
        .join("|"),
    [allFlatSteps],
  );

  const lgStepsKey = useMemo(
    () =>
      allFlatSteps
        .filter((s) => s.type === "langgraph_invoke")
        .map((s) => `${s.id}:${s.langGraphTargetNodeId}`)
        .join("|"),
    [allFlatSteps],
  );

  const transformStepsKey = useMemo(
    () =>
      allFlatSteps
        .filter((s) => s.type === "transform" && (s.transformerNodeId || s.functionRef?.name))
        .map((s) => `${s.id}:${s.transformerNodeId}:${s.functionRef?.name}`)
        .join("|"),
    [allFlatSteps],
  );

  const storageStepsKey = useMemo(
    () =>
      allFlatSteps
        .filter((s) => s.type === "storage_operation" && (s.storageNodeId || s.bucketId))
        .map((s) => `${s.id}:${s.storageNodeId}:${s.bucketId}:${s.functionRef?.name || s.operationId}`)
        .join("|"),
    [allFlatSteps],
  );

  const serviceCallStepsKey = useMemo(
    () =>
      allFlatSteps
        .filter((s) => s.type === "service_call" && (s.databaseId || s.tableNodeId))
        .map((s) => `${s.id}:${s.databaseId}:${s.tableNodeId}:${s.functionRef?.name || s.operationId}`)
        .join("|"),
    [allFlatSteps],
  );

  // Auto-synchronize connected Redis cache nodes and edges for configured redis_operation steps
  useEffect(() => {
    if (isNested || !serviceNodeId) return;
    const redisSteps = allFlatSteps.filter(
      (s) => s.type === "redis_operation" && s.tableNodeId && s.tableNodeId !== "__none__",
    );
    if (redisSteps.length === 0) return;

    redisSteps.forEach((s) => {
      ensureRedisCacheConnection({
        schemaId: s.tableNodeId,
        instanceId: s.databaseId,
        serviceNodeId,
        endpointId: endpoint?.id,
        consumedEventId: consumedEvent?.id,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [redisStepsKey, serviceNodeId, endpoint?.id, consumedEvent?.id, isNested]);

  // Auto-synchronize connected Database ref nodes and function edges for configured db_operation steps
  useEffect(() => {
    if (isNested || !serviceNodeId) return;
    const dbSteps = allFlatSteps.filter(
      (s) => s.type === "db_operation" && (s.tableNodeId || s.databaseId),
    );
    if (dbSteps.length === 0) return;

    dbSteps.forEach((s) => {
      ensureDatabaseRefConnection({
        stepId: s.id,
        dbRefNodeId: s.dbRefNodeId,
        tableNodeId: s.tableNodeId,
        databaseId: s.databaseId,
        serviceNodeId,
        endpointId: endpoint?.id,
        consumedEventId: consumedEvent?.id,
        functionName: s.functionRef?.name || s.operationId,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dbStepsKey, serviceNodeId, endpoint?.id, consumedEvent?.id, isNested]);

  // Auto-synchronize connected PageRef nodes and edges for configured push_to_client steps
  useEffect(() => {
    if (isNested || !serviceNodeId) return;
    const pushSteps = allFlatSteps.filter((s) => s.type === "push_to_client");
    if (pushSteps.length === 0) return;

    pushSteps.forEach((s) => {
      ensurePageRefConnection({
        targetPageId: s.clientDeliveryTargetPageId,
        pageRefNodeId: s.clientDeliveryPageRefNodeId,
        serviceNodeId,
        endpointId: endpoint?.id,
        consumedEventId: consumedEvent?.id,
        stepId: s.id,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pushStepsKey, serviceNodeId, endpoint?.id, consumedEvent?.id, isNested]);

  // Auto-synchronize connected LangGraph Agent nodes and edges for configured langgraph_invoke steps
  useEffect(() => {
    if (isNested || !serviceNodeId) return;
    const lgSteps = allFlatSteps.filter((s) => s.type === "langgraph_invoke");
    if (lgSteps.length === 0) return;

    lgSteps.forEach((s) => {
      ensureLangGraphConnection({
        langGraphNodeId: s.langGraphTargetNodeId,
        serviceNodeId,
        endpointId: endpoint?.id,
        consumedEventId: consumedEvent?.id,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [lgStepsKey, serviceNodeId, endpoint?.id, consumedEvent?.id, isNested]);

  // Auto-synchronize connected Transformer nodes and edges for configured transform steps
  useEffect(() => {
    if (isNested || !serviceNodeId) return;
    const transformSteps = allFlatSteps.filter(
      (s) => s.type === "transform" && (s.transformerNodeId || s.functionRef?.name),
    );
    if (transformSteps.length === 0) return;

    transformSteps.forEach((s) => {
      ensureTransformerConnection({
        transformerNodeId: s.transformerNodeId,
        functionName: s.functionRef?.name,
        serviceNodeId,
        endpointId: endpoint?.id,
        consumedEventId: consumedEvent?.id,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [transformStepsKey, serviceNodeId, endpoint?.id, consumedEvent?.id, isNested]);

  // Auto-synchronize connected Storage Operation ref nodes and edges for configured storage_operation steps
  useEffect(() => {
    if (isNested || !serviceNodeId) return;
    const storageSteps = allFlatSteps.filter(
      (s) => s.type === "storage_operation" && (s.storageNodeId || s.bucketId),
    );
    if (storageSteps.length === 0) return;

    storageSteps.forEach((s) => {
      ensureStorageOperationRefConnection({
        storageNodeId: s.storageNodeId,
        bucketId: s.bucketId,
        serviceNodeId,
        endpointId: endpoint?.id,
        consumedEventId: consumedEvent?.id,
        functionName: s.functionRef?.name || s.operationId,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [storageStepsKey, serviceNodeId, endpoint?.id, consumedEvent?.id, isNested]);

  // Auto-synchronize connected Service Call edges for configured service_call steps
  useEffect(() => {
    if (isNested || !serviceNodeId) return;
    const serviceCallSteps = allFlatSteps.filter(
      (s) => s.type === "service_call" && (s.databaseId || s.tableNodeId),
    );
    if (serviceCallSteps.length === 0) return;

    serviceCallSteps.forEach((s) => {
      ensureServiceCallConnection({
        serviceNodeId,
        endpointId: endpoint?.id,
        targetServiceId: s.databaseId,
        targetEndpointId: s.tableNodeId,
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [serviceCallStepsKey, serviceNodeId, endpoint?.id, isNested]);

  return {
    connectedTransformers,
    connectedKafka,
    connectedLangGraph,
    connectedRedis,
    connectedServiceCalls,
  };
}
